<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Title</name>
   <tag></tag>
   <elementGuidId>bbac3308-042d-4980-954d-bc0b5cfa0fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Title_summary&quot;)[count(. | //*[@id = 'Title_summary' and @name = 'Title' and @title = 'Title']) = count(//*[@id = 'Title_summary' and @name = 'Title' and @title = 'Title'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Title_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Title_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4ad3696-6fea-46ee-a8d5-ce56d5e69fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>649ba3b9-f215-4216-aa40-8d50da1e9c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title_summary</value>
      <webElementGuid>43490b89-2d1b-4cb0-b782-55cac1249f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>6f1df160-be6e-4718-9336-f951b3e5ba18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>5e9ea080-1864-4d63-a607-6d47592c9b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DrMissMrMrsMs
</value>
      <webElementGuid>fc1dda45-0d56-4e5d-a0a3-65b09cab38fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title_summary&quot;)</value>
      <webElementGuid>a7a0ddb7-4010-48fb-8dd9-b90fa031f3b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Title_summary']</value>
      <webElementGuid>b2210232-b578-44c1-ad3d-5447a16e0774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
