<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>f783c1d7-6178-45d6-bd35-52416681a4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecordType_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RecordType_summary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;RecordType_summary&quot;)[count(. | //select[@id = 'RecordType_summary' and @name = 'RecordType' and @title = 'Type']) = count(//select[@id = 'RecordType_summary' and @name = 'RecordType' and @title = 'Type'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>47dfc8fd-5636-4c69-87cc-4241eb98f844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecordType_summary</value>
      <webElementGuid>391264c0-523d-46de-a7fa-68ff3c34b771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RecordType</value>
      <webElementGuid>3321ecf1-f468-43cc-af84-a4609c6d067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>369c1eae-6438-4c67-afc1-7485bbf56b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecordType_summary&quot;)</value>
      <webElementGuid>0e93055e-ddf6-4eb3-b487-86aecb0806c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RecordType_summary']</value>
      <webElementGuid>db2f87d5-0318-4e29-95e2-1dba15dfe8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
