<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address1(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>5bd38815-bd90-471b-b87e-62754200bbbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine1_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine1_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8da3dbb3-3c1a-4700-be24-debd808b472a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine1_summary</value>
      <webElementGuid>494dd4d0-33bf-44b0-a60d-0db5c7a7675e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine1</value>
      <webElementGuid>ef98af44-9c40-4f0f-8c37-8da233746456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>d974566f-05b3-4550-a6ce-04f191f5554a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine1_summary&quot;)</value>
      <webElementGuid>de7f6fe6-5238-49f3-9fdd-da0d77345114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine1_summary']</value>
      <webElementGuid>e5dd0acd-f6b7-4c59-90ef-3dbb67081d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>54f531d9-113b-45f8-9850-12f84a293785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>4d99e4a5-2d38-48a4-902d-2b703a570441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine1_summary' and @name = 'AddressLine1' and @title = 'Address Line 1' and @type = 'text']</value>
      <webElementGuid>2e1f5318-d21e-4c22-971c-f3e6cb6c62fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
