<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address2(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>ed05131f-0246-4391-a899-a6197b07c8e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine2_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine2_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d0d99ad-5f05-465b-b4b0-6556e1dfe04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine2_summary</value>
      <webElementGuid>3bd5596e-3c10-4ef3-b6a0-ef8e42d351d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine2</value>
      <webElementGuid>90c8d713-d989-4e51-9563-df9fa6a79821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Address Line 2</value>
      <webElementGuid>376edc3e-86be-40c0-8062-dd40481e00aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa3c7608-1791-40a9-ba51-0795c3a29c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine2_summary&quot;)</value>
      <webElementGuid>88832308-92ca-4005-9af7-0c8d85dfc801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine2_summary']</value>
      <webElementGuid>9e1a82ef-e8c6-4a5c-b002-8ebfc6503833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[4]/div[2]/input</value>
      <webElementGuid>6184a5ea-0de7-41c4-85e7-1f7327758b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[4]/div[2]/input</value>
      <webElementGuid>8a8034a6-2071-4977-a513-a3e4530a1c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine2_summary' and @name = 'AddressLine2' and @title = 'Address Line 2' and @type = 'text']</value>
      <webElementGuid>d22ae357-082a-48ff-9fa8-de95692131a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
