<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddressLine4(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>69dc6181-813c-4646-aee6-4bc0af098e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine4_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine4_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e622071-5af6-479a-ab47-03f873a05fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine4_summary</value>
      <webElementGuid>914d203b-ef40-4bb4-bed1-996a2124320d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine4</value>
      <webElementGuid>042f2a8d-ed8d-408b-91c7-08e7e354d363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Address Line 4</value>
      <webElementGuid>fcef337c-5ba0-4b90-996b-75a1e77c39b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e7e6582-9b6a-4889-97f2-195c034897ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine4_summary&quot;)</value>
      <webElementGuid>34130025-6f60-4026-bbfc-4c3c8cd4d2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine4_summary']</value>
      <webElementGuid>75db4f46-5303-4c79-accb-9828b77483d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>0a3b8413-2973-48a7-a94c-a9c12b41a8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>3d01b20a-4d1c-488c-ac68-bce2165e24a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine4_summary' and @name = 'AddressLine4' and @title = 'Address Line 4' and @type = 'text']</value>
      <webElementGuid>2fc214ca-2566-4886-99b7-0ccdc302ef43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
