<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddressLine3(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>b2ded3f9-a461-4dc3-bd03-6319e5465142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine3_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine3_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87f552fe-b1df-438f-8dc5-9559cb0e69c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine3_summary</value>
      <webElementGuid>536b6fe8-5a72-44e5-b53d-f737ae736030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine3</value>
      <webElementGuid>da18aef0-7aa3-42c5-b2cd-83d72366ab3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Address Line 3</value>
      <webElementGuid>84cb644e-80fb-41b4-b1f3-8cf04c871738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine3_summary&quot;)</value>
      <webElementGuid>a16f545f-ce77-4f01-93ea-14cbe3333d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine3_summary']</value>
      <webElementGuid>54bd97c3-76d6-4ebd-8d29-954313841c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[5]/div[2]/input</value>
      <webElementGuid>7f040f7e-0ace-4841-a3e5-b9ab13afa8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[2]/input</value>
      <webElementGuid>51f65a82-3523-457b-8389-d06ab7cfe617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine3_summary' and @name = 'AddressLine3' and @title = 'Address Line 3' and @type = 'text']</value>
      <webElementGuid>3926c295-47b2-4b3e-b02d-0009a6e35992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
