<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Longitude(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>c2ce56ba-b211-4c89-80ed-35715b4ed1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Longitude_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Longitude_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22149251-d90a-402b-ac13-1bbf7af81718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Longitude_summary</value>
      <webElementGuid>b65db2a5-be3c-4633-8838-7dc4da7447b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Longitude</value>
      <webElementGuid>76f85f9b-1691-4627-a774-5b177a863125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Longitude</value>
      <webElementGuid>4a42e0ba-3ee1-4f6a-aed2-4e2626fc43ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>badadda0-b9fa-4f79-aa4f-effa0ab3704d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Longitude_summary&quot;)</value>
      <webElementGuid>475b0775-120d-4b8f-b5f7-cbcf8c60a55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Longitude_summary']</value>
      <webElementGuid>3c02284d-f460-4185-b11f-963959c17220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[12]/div[3]/input</value>
      <webElementGuid>76db0cfe-a7cb-4e91-a549-4f3d46612ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div[3]/input</value>
      <webElementGuid>c155108d-c90a-4fcd-bb23-97ecd1253260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Longitude_summary' and @name = 'Longitude' and @title = 'Longitude' and @type = 'text']</value>
      <webElementGuid>e6254961-9678-4f47-ab51-d3186d5c579c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
