<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Postcode(Address Pop-Up)</name>
   <tag></tag>
   <elementGuidId>d3ad26cb-cf03-438a-9687-835fb86a7ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Postcode_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Postcode_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fa82cd4-e6c8-4964-855c-d3b9c0cf30d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Postcode_summary</value>
      <webElementGuid>a6e19817-64ab-419e-ae3c-02ad5e36f885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>977395a2-46eb-48b1-97af-e03dc2b2dec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Postcode</value>
      <webElementGuid>21804fdf-167e-4ed6-abd1-91ef10930a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9afd303d-5079-410f-b167-a78219e99b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Postcode_summary&quot;)</value>
      <webElementGuid>3ba2fd14-87d8-4831-aa57-f65f7387d74a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Postcode_summary']</value>
      <webElementGuid>f6a95292-f28b-41c1-918b-48dda45a178b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[10]/div[2]/input</value>
      <webElementGuid>e3ca7dd3-3ef1-44d6-8dfa-123e5ee81086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div[2]/input</value>
      <webElementGuid>31eced18-aad9-4696-bd0b-7c2e86059164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Postcode_summary' and @name = 'Postcode' and @title = 'Postcode' and @type = 'text']</value>
      <webElementGuid>3c506a50-3203-41e7-b0d5-9ecece770012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
