<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_pdf(ReportHistory)</name>
   <tag></tag>
   <elementGuidId>528595cb-8c14-433c-8de5-1edd7a5a62c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LinksWrapper']/div/div/table/tbody/tr/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ff49687-331b-420b-a763-554601a2037e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f27471e8-2fad-4619-b240-5f6e010a4e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>b4489390-4d14-480d-baef-26c1c6893ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: clue.formatColumn2($data, $parent, true, true), click: function () { $root.previewFile({ fileId: $parent.Id, fileUrl: $parent.PreviewUrl, componentName: null, fileExtension: $parent.ReportName.substring( $parent.ReportName.lastIndexOf('.') + 1), previewOnly: true, reportName: $parent.ReportName, context: 2 }); }</value>
      <webElementGuid>c3fd2452-eff0-4dca-8744-683c668ed722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pdf</value>
      <webElementGuid>400ab6f8-7506-446c-a35e-096b2e45f1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinksWrapper&quot;)/div[1]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[4]/a[1]</value>
      <webElementGuid>14ca62c0-3a3b-46ab-96ae-d90a6633f1e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LinksWrapper']/div/div/table/tbody/tr/td[4]/a</value>
      <webElementGuid>e7622d70-c189-4b34-8619-cf153284975c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'pdf')]</value>
      <webElementGuid>87efe152-8f6e-4155-a15f-ebaa8c141f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prasad'])[3]/following::a[1]</value>
      <webElementGuid>1b8efbe9-6aaf-49d3-a924-6fda386fbe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address - 15/02/2023 16:17:35.pdf'])[1]/following::a[1]</value>
      <webElementGuid>2659a273-618e-4645-8db6-356189130298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks and Activities'])[1]/preceding::a[1]</value>
      <webElementGuid>31548e01-aa17-4af7-a931-a0ea75e1e341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::a[1]</value>
      <webElementGuid>ca8c4fb9-d0aa-4d3e-b1b1-6ce6d0bcafb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pdf']/parent::*</value>
      <webElementGuid>d1f10612-05d1-4c9a-9c96-c1b4c087a445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>3ff35a53-b070-4a58-a10f-d78fec4de4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a</value>
      <webElementGuid>a8c3ab58-d65c-4e54-82d2-ee610c09386f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
