<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttachmentColumn(Rep.History Links)</name>
   <tag></tag>
   <elementGuidId>a08df895-584d-4865-899d-1b33937cdca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='LinksWrapper']/div/div/table/tbody/tr[2]/td[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73cac0a6-2fee-4728-bd38-5abfccd0a91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>af75f639-2a40-4fac-a5fa-6368d9969fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>reportPreview</value>
      <webElementGuid>9f227aca-e773-4d93-9114-5c31a91c10c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>9edd1182-ec76-4605-b3c8-71f02554a98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: clue.formatColumn2($data, $parent, true, true), click: function () { $root.previewFile({ fileId: $parent.Id, fileUrl: $parent.PreviewUrl, componentName: null, fileExtension: $parent.ReportName.substring( $parent.ReportName.lastIndexOf('.') + 1), previewOnly: true, reportName: $parent.ReportName, context: 2 }); }</value>
      <webElementGuid>ca4e8d3b-b6e0-4134-a589-4ad7d5bab548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pdf</value>
      <webElementGuid>b71a4027-bcbf-4356-a978-089294a2fbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinksWrapper&quot;)/div[1]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[2]/td[4]/a[1]</value>
      <webElementGuid>0f308a7a-4e11-4c9f-8a3a-fe48c0817b2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LinksWrapper']/div/div/table/tbody/tr[2]/td[4]/a</value>
      <webElementGuid>5c355faa-0bcf-421a-8a59-7de0f8b9ed6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'pdf')]</value>
      <webElementGuid>51987f6c-8ab1-4675-ac3b-ec8aa5fc8000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='emmal'])[4]/following::a[1]</value>
      <webElementGuid>740145d6-5f47-4fd1-a520-6e2139058b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address - 06/06/2023 13:32:29.pdf'])[1]/following::a[1]</value>
      <webElementGuid>24bbed2e-a26f-41b0-b874-a9b2b99e60a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks and Activities'])[1]/preceding::a[1]</value>
      <webElementGuid>c366a85c-377c-45fa-a20f-70e4bdc29785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachments'])[1]/preceding::a[1]</value>
      <webElementGuid>63a5b18b-c9c8-41df-959d-3b785c00cf4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pdf']/parent::*</value>
      <webElementGuid>65912df5-eff0-4cac-8dee-e526242b7756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[7]</value>
      <webElementGuid>fae941c8-0077-43c5-91c7-dbe4ed40e9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/a</value>
      <webElementGuid>d8d588f5-4315-4501-9582-e61bad97fff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
