<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Report only print</name>
   <tag></tag>
   <elementGuidId>81c8bc78-90fe-4cd4-89be-b134a14e0c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportOnly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportOnly']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;reportOnly&quot;)[count(. | //input[@id = 'reportOnly' and @type = 'radio' and @name = 'filter' and @value = 'ReportOnly']) = count(//input[@id = 'reportOnly' and @type = 'radio' and @name = 'filter' and @value = 'ReportOnly'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d6e84bd-e7cd-4a48-b89c-2701e02a634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportOnly</value>
      <webElementGuid>1e0044c8-cb43-4823-bdea-a779e711af3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f4a21265-034c-400e-99d1-f91e5daba706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter</value>
      <webElementGuid>c26a43eb-d77d-4168-8d17-147eb2f57e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ReportOnly</value>
      <webElementGuid>49625765-39aa-4498-bcb5-c934d5579abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click:function() {setNoneAsSelected(); return true;},checked: dlOp</value>
      <webElementGuid>444af2c1-72f8-4296-adf8-3b66af2129ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportOnly&quot;)</value>
      <webElementGuid>dfc6d135-8452-4c55-b971-83274e3badab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportOnly']</value>
      <webElementGuid>68937ff5-ab69-4856-8155-2bccceb0ff1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/form/div/fieldset/input</value>
      <webElementGuid>d59fa25b-59b0-449a-8f8a-8ea65e823bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>cef3359d-43e5-4618-82f6-c24d3dd19439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reportOnly' and @type = 'radio' and @name = 'filter']</value>
      <webElementGuid>01cc8e38-9d1b-4186-b235-0a2ba828f345</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
