<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MenuItem</name>
   <tag></tag>
   <elementGuidId>37ff0d9a-d35f-4469-a061-5b8203c987f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-dialog.ui-corner-all.ui-widget.ui-widget-content.ui-front.ui-dialog-buttons.ui-draggable.ui-resizable > #menuItemDialog > div > table > tbody > #menuItemTextRow > td:nth-of-type(2) > #menuItemText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='menuItemText'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3967baa2-8f73-4b8c-9639-a5cc2fdeaec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5dd95f8a-3a97-4e47-9c76-4bde61547b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Menu item text</value>
      <webElementGuid>b371634c-0da6-49cf-994d-c5ac9421598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>1a7f9112-0557-430a-94a2-df1914f34eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuItemText</value>
      <webElementGuid>bf152ec7-6aa4-4e76-b3af-12ca1349f073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-dialog-buttons ui-draggable ui-resizable&quot;]/div[@id=&quot;menuItemDialog&quot;]/div[1]/table[1]/tbody[1]/tr[@id=&quot;menuItemTextRow&quot;]/td[2]/input[@id=&quot;menuItemText&quot;]</value>
      <webElementGuid>ed600f65-2103-42ac-afba-ec4d085d5813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='menuItemText'])[2]</value>
      <webElementGuid>4a4855c6-94b3-427f-8bc3-650871a3f5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='menuItemTextRow']/td[2]/input)[2]</value>
      <webElementGuid>ca3e702f-9d88-4a80-9583-49683cba86a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>83647423-44fa-4b94-ac74-882f8a6e6467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'menuItemText']</value>
      <webElementGuid>22ed5d89-4339-4bbe-a2ae-6b0566c9fd23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
