<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu DropDown</name>
   <tag></tag>
   <elementGuidId>12d934f5-1148-4309-8ba5-646185c0809b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8dd5e09c-1ff8-4e95-b30a-ab9efc0d6bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>d7134e0a-c11b-4b56-8b58-caaee359b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>a8b3d5e5-36eb-4df5-9cf3-48774fe4e194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box</value>
      <webElementGuid>f53d0377-5c66-42b7-b4e8-47c0c19c0126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: (isDirty() == true), css: {disabled: (isDirty() == true)}, options: menuList, optionsText: 'Name', value: selectedMenu, optionsCaption: '', event: { change: function () { selectMenu(); } }</value>
      <webElementGuid>1533486e-34fa-4388-b572-785543473c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Activity: AllocationActivity: BriefingActivity: EscalatedActivity: Personnel Note PersonnelActivity: Personnel Note TypeActivity: TypeAddress: CountryAddress: TypeAssessment: OutcomeAssessment: TypeCase Charge: CategoryCase Charge: DecisionCase Classification: Document TypeCase Classification: Key WitnessCase Classification: Reason for SensitivityCase Classification: Record TypeCase Classification: Witness TypeCase Decision Request Outline: TitleCase Decision: Record Contact TypeCase: Decision Request StatusCase: Decision Request Supporting Material TypeCase: Defendant CaseTypeCase: Defendant Next CourtCase: Defendant Offender TypeCase: Defendant Remand StatusCase: Defendant Type Of CourtCase: StatusCase: TypeCase: VerdictCommunication: FormatCommunication: NatureCommunication: NetworkCommunication: Service ProviderCommunication: Test1Communication: TypeCountry and NationalityDecision: TypeDocument ClassificationEvent: Stage OutcomeEvent: Stage TypeEvent: TypeExpiry PeriodFile: TypeIncident Note: PersonnelIncident Personnel Note: PersonnelIncident: Allocated ToIncident: ComplaintIncident: Complaint RecordedIncident: CountyIncident: DistrictIncident: Further Details: Any Notes?Incident: Heads Of Complaint OutcomeIncident: Heads Of Complaint TypeIncident: How ReportedIncident: How heard of League?Incident: Note TypeIncident: Note Type - Info/AdviceIncident: Note Type - RehomingIncident: Note Type - WelfareIncident: Other OrganisationsIncident: Personnel Note TypeIncident: Police AreaIncident: Premise TypeIncident: PriorityIncident: StatusIncident: Taken ByIncident: TypeInformation: Personnel Note TypeInformation: TypeIntelligence: Action CodeIntelligence: AssessmentIntelligence: Handling CodeIntelligence: Personnel Note TypeIntelligence: SanitisationIntelligence: Security ClassificationIntelligence: Source EvaluationIntelligence: StatusIntelligence: TypeInvestigation: BranchInvestigation: MenuInvestigation: RegionInvestigation: SourceInvestigation: StatusInvestigation: TypeLink: ReasonMarking DescriptorMaterial: Class of DrugMaterial: CommodityMaterial: Custom Field 2Material: StatusMaterial: TypeMaterial: UnitNIM LevelOrganisation: StatusOrganisation: TypeOutcome: TypePerson: GenderPerson: HeightPerson: ICCCodePerson: NationalityPerson: OccupationPerson: Other Name: TypePerson: Personal Document: Document TypePerson: PreferredLanguagePerson: Record TypePerson: ReligionPerson: SelfDefinedDisabilityPerson: SelfDefinedEthnicityPerson: TitlePerson: TypePersonnelPriorityProsecution: Priority SentenceProtective MarkingRecord StatusRetention PeriodRisk Assessment: StatusSource: CategorySource: Contact MethodSource: Contact Preference MethodSource: Specialist Skill/KnowledgeSource: TypeStaff: Country ListStaff: County ListStaff: DivisionStaff: Dropdown_CustomStaff: Length Of ServiceStaff: Operations CodeStaff: Organisation TypeStaff: Police Authority InvolvedStaff: RegionStaff: TypeStatement: Personnel Note TypeStatement: TypeSubject TypeTask: StatusVehicle: Aircraft ClassVehicle: ColourVehicle: MakeVehicle: ModelVehicle: Motor Vehicle ClassVehicle: TypeVehicle: Vessel ClassVehicle: Vessel Steering ClassWhereFlagged</value>
      <webElementGuid>2395cb02-8c31-4a60-be88-57f41be61ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuEditor&quot;)/fieldset[1]/ul[1]/li[1]/div[@class=&quot;field span8&quot;]/select[@id=&quot;menu&quot;]</value>
      <webElementGuid>3cb570d3-05f6-40d9-9657-087d428b1ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='menu']</value>
      <webElementGuid>57fa08ad-5a09-4aef-8aec-d5ae458205bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='menuEditor']/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>015d50a5-6dcc-4ac2-9503-701847511d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select menu'])[1]/following::select[1]</value>
      <webElementGuid>51af612c-df7e-49bf-9546-19c9d628bdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Between:'])[1]/preceding::select[1]</value>
      <webElementGuid>dccbac95-75d6-4c30-ad02-72b2dd97a0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='and:'])[1]/preceding::select[2]</value>
      <webElementGuid>6ad201e3-013f-420e-8025-e1aeb5e473da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>241dda3a-366d-4ded-8ce6-2e937be326b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'menu' and @name = 'menu']</value>
      <webElementGuid>8dfb8cfb-5047-4061-a2d6-ca77644c0c95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
