<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WhenFoundDate</name>
   <tag></tag>
   <elementGuidId>bba9d185-961f-4db2-a9b7-522e58d1571a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WhenFoundDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WhenFoundDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d01894d-501d-4297-b9e3-b254a3d5844c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line date hasDatepicker</value>
      <webElementGuid>b7bcf424-4f0d-4717-9489-c6d483a7e8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>datepicker: model.WhenFoundDate,datepickerOptions: { maxDate: '+0d'}</value>
      <webElementGuid>9b623245-96d3-4bc3-a5eb-ddd2c783f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a8ee8e4-1cd1-4de6-9276-b0039dfb47af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-date</name>
      <type>Main</type>
      <value>The field When Found Date must be a date.</value>
      <webElementGuid>adc88a52-930c-48f0-aeed-078906870db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture</name>
      <type>Main</type>
      <value>The field When Found Date does not permit future dates.</value>
      <webElementGuid>d9fe4a5f-e698-4047-9d75-1bfc40b1ed9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dateformat</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>400d5ed9-67b3-46bf-8d64-6b332c682852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dependentproperty</name>
      <type>Main</type>
      <value>WhenFoundDate</value>
      <webElementGuid>8a8b323e-35f8-471f-885f-ab6db0d897bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dependentpropertytime</name>
      <type>Main</type>
      <value>undefined</value>
      <webElementGuid>d60a3d4a-9d80-4fda-bfb7-70e1fb4064dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-isallowfutureenabled</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>36c4ed3b-69e6-4905-af2c-5af741999560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-targetvalue</name>
      <type>Main</type>
      <value>20/01/2024 16:03:05</value>
      <webElementGuid>69859ab3-2ae3-4412-942f-0a2d13e21762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>The When Found Date field is required.</value>
      <webElementGuid>ab506f04-d98b-44e9-8371-1b1c519dcb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>IsExhibit</value>
      <webElementGuid>32705cfe-c4ce-403b-9ce1-4afe39b218d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7b9a006-4f27-4486-8e73-7d26a8a9aaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WhenFoundDate</value>
      <webElementGuid>91737472-06ac-42a7-83a1-71ca5546ca1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WhenFoundDate</value>
      <webElementGuid>d7e585fd-2a06-4995-9e79-e374cdc5a7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>When Found Date</value>
      <webElementGuid>17245952-38e7-4a10-8010-d4e8bfbd16fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>051df2a7-ae60-4fd2-b8c7-83116d255e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6853a4d3-f41f-480d-8dd3-a78414dbc46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>47fcf5bb-1df8-42e9-bc40-1e5f9415520d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WhenFoundDate&quot;)</value>
      <webElementGuid>68ee002a-a172-4a60-8c71-c792eb05a7e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WhenFoundDate']</value>
      <webElementGuid>d41e912a-2661-4bea-97f5-4a5d672fc878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[10]/div[2]/input</value>
      <webElementGuid>dfb1ccad-f431-49a9-9524-3531b084efe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div[2]/input</value>
      <webElementGuid>217f4bc5-466e-4c5b-a313-5448712b15e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WhenFoundDate' and @name = 'WhenFoundDate' and @title = 'When Found Date' and @type = 'text']</value>
      <webElementGuid>4f7e1845-a717-42d4-9811-ac6c60443a50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
