<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WhenFoundTime</name>
   <tag></tag>
   <elementGuidId>2e358cb7-04bb-4337-911d-fad17ad410dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WhenFoundTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WhenFoundTime</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9c6bbcd-7919-4a04-b732-ab44bf568628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>68e2448a-ec1d-4644-a466-7537d5d6c361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.WhenFoundTime, valueUpdate: 'afterkeydown', attr:{maxlength:'5'}, event: {blur:function(){model.WhenFoundTime(clue.makeValidShortTime(model.WhenFoundTime()));}, keydown: function(data, e){ return clue.maskShortTime(e, model.WhenFoundTime);} }</value>
      <webElementGuid>f0619fcf-3b3f-4786-a08f-429e4d5fed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7961dec0-f56d-4456-81a5-2329923af3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture</name>
      <type>Main</type>
      <value>The field When Found Time does not permit future times.</value>
      <webElementGuid>a0968c3a-f91c-47b1-853f-ec1e1679dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dateformat</name>
      <type>Main</type>
      <value>dd/MM/yyyy</value>
      <webElementGuid>5230bdd5-e128-4088-a7d3-eddc64db6732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dependentproperty</name>
      <type>Main</type>
      <value>WhenFoundDate</value>
      <webElementGuid>c2947663-c505-4e27-8d85-3ffcb1da429c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-dependentpropertytime</name>
      <type>Main</type>
      <value>WhenFoundTime</value>
      <webElementGuid>becd2e36-892c-4d21-8f79-5cf361c3b247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-isallowfutureenabled</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>cdb97464-ab9c-4e78-81c6-e9ff9d3c913a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-nofuture-targetvalue</name>
      <type>Main</type>
      <value>20/01/2024 16:03:05</value>
      <webElementGuid>4710508b-328c-447b-8f2c-dbcb587a72b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>The When Found Time field is required.</value>
      <webElementGuid>dbda015d-883a-4406-b878-845df38c6eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>IsExhibit</value>
      <webElementGuid>35f7d9ba-258c-4667-8d66-049512ed43a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c2a0e95d-b981-4ecb-a791-91b360ebbc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WhenFoundTime</value>
      <webElementGuid>e766aba3-df6c-46b0-a01a-c6ab08998586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WhenFoundTime</value>
      <webElementGuid>429cafe6-8222-42e4-94ab-3d68c3b796da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>When Found Time</value>
      <webElementGuid>54f9844d-adee-456e-b948-32562adea6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9158225b-5be1-49f1-965d-611afd273ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8752a79c-d5ac-4d1d-a8ad-e196982ece26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WhenFoundTime&quot;)</value>
      <webElementGuid>95c10408-cd3d-4e18-b752-830debfc2f60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WhenFoundTime']</value>
      <webElementGuid>b631a788-88be-41f7-aa35-fc1bb0acc0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[10]/div[4]/input</value>
      <webElementGuid>f42b67f1-2584-4491-9815-afa5b1eba252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9cd0f2c1-f086-4791-903a-759f21ac41cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'WhenFoundTime' and @name = 'WhenFoundTime' and @title = 'When Found Time' and @type = 'text']</value>
      <webElementGuid>750b4ba0-8991-4581-b46a-bdfbb44e4333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
