<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Date Reviewed</name>
   <tag></tag>
   <elementGuidId>eec64086-7969-4cc5-ba31-cf146d801886</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='custField_8459']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custField_8459</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>336550e9-d4a9-4ef2-9d71-34a99a10f877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date Reviewed</value>
      <webElementGuid>58df81de-ee3a-430c-b59e-bdbd4ec53327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='custField_8459']</value>
      <webElementGuid>332add9c-5f09-4419-ad09-a76539abcaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='customFieldsList']/tr[19]/td</value>
      <webElementGuid>68901092-5c9a-4a1b-878a-17a2f1d9b11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::td[1]</value>
      <webElementGuid>e6dd606e-97ef-4952-a2c6-acc5b1643f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boolean'])[1]/following::td[2]</value>
      <webElementGuid>92760c72-cf8c-4360-94ad-35bb6c153964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/preceding::td[1]</value>
      <webElementGuid>eb9ab957-716f-4acc-9363-4b43295f5f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FreeText'])[1]/preceding::td[2]</value>
      <webElementGuid>88cc164a-5cb8-43a6-baa1-3d48c9f1d728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Date']/parent::*</value>
      <webElementGuid>8e57aed6-c07c-4460-8210-4f1438bbc555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td</value>
      <webElementGuid>38e79fd5-8ff5-44b2-985a-dae7abe7f074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'custField_8459']</value>
      <webElementGuid>40689dda-29ee-41b5-9574-a8c9f9f380bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
