<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot password_logon</name>
   <tag></tag>
   <elementGuidId>8656b4a3-ad2d-46f8-bdb6-6390140f8d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d82f107-f9da-4ca0-86e7-b799d56eea27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logon</value>
      <webElementGuid>1818c683-cc8a-4e9c-8f3f-91aa922bcb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fbe059e8-24bb-491c-8b68-f6f726481956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log On</value>
      <webElementGuid>d296b572-3019-4eb6-9b77-f92aed229642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logon&quot;)</value>
      <webElementGuid>b2752ea7-2c00-4f5c-a80f-45d38ba61c30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logon']</value>
      <webElementGuid>73dcf92d-9c7a-41f0-92cf-1d269a8cd108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>7e36bd40-d34d-49ff-94d8-ace013415982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'logon' and @type = 'submit']</value>
      <webElementGuid>5e03673a-211a-436b-a351-653c378eff77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
