<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find matching Users to redact</name>
   <tag></tag>
   <elementGuidId>9e6042ab-206c-4605-a34c-d91fb179e1a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#findUsersToRedact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='findUsersToRedact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f261f99-8e6b-45fc-a161-60cf2e73f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0584a1cf-0b5b-47ed-b910-50eae6e587d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>findUsersToRedact</value>
      <webElementGuid>73e72795-9482-45a3-887c-41d0915c828f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: () => clue.redaction.render($data.model, 20, 'searchUsers')</value>
      <webElementGuid>aa8d48e4-6040-468f-85ae-870fd832db34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find matching Users to redact</value>
      <webElementGuid>5bef749f-b035-4b24-aaa8-ae2abdbef93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findUsersToRedact&quot;)</value>
      <webElementGuid>2b435ffc-143f-42cf-94b7-a94c12fb6ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='findUsersToRedact']</value>
      <webElementGuid>e261fd68-d75f-4936-ba2a-91918b9e435c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset[2]/ul/li[2]/div[3]/a[3]</value>
      <webElementGuid>a1bf9ba2-0f89-4a6e-8d02-aa7d5a8ceba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find matching Users to redact')]</value>
      <webElementGuid>9a6d279f-f63d-4a6d-9cf4-4d6cbca6f427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mark'])[1]/following::a[3]</value>
      <webElementGuid>b8cd7006-2abf-4bb7-b6cb-d7bdb9b2e86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forename'])[1]/following::a[3]</value>
      <webElementGuid>063aa93e-d995-4e73-9ebd-94b2f36abac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Fields'])[2]/preceding::a[1]</value>
      <webElementGuid>1344233f-a461-47a3-8376-198e4c7d3597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find matching Users to redact']/parent::*</value>
      <webElementGuid>f1904a91-7832-440a-a5d6-56b6edd2a702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>a5c60856-42d6-4c42-a410-3d705412a928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>266fd904-6b65-48ab-afc2-ae524b2add95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'findUsersToRedact']</value>
      <webElementGuid>ab118946-fbc3-4d24-ba2a-496513fcfd4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
