<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields_goSelectLink</name>
   <tag></tag>
   <elementGuidId>ed16ebad-784b-4276-abe3-78727543e6b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='goSelectLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#goSelectLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0403a3b4-d94b-4393-a0a8-185e80a60c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>7b44ad13-ff74-472f-a186-8ee8934f51a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>601ecf47-7c77-476b-be87-697a6f952ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>80328093-1bf9-456e-849e-5afe5654f959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>a5773936-9e40-4add-857b-f570af99706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: disableGoButton, css : {disabled: disableGoButton}</value>
      <webElementGuid>585ce5ec-e21d-4769-8a46-0c0383319b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goSelectLink&quot;)</value>
      <webElementGuid>71549069-583b-4e8d-8885-5967ddbe2892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='goSelectLink']</value>
      <webElementGuid>9b454a5e-3a6b-4d0f-9b73-de461814e9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form3']/p[2]/input</value>
      <webElementGuid>6d6d7a6b-3dbc-45ff-9806-5c946c7014e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/p[2]/input</value>
      <webElementGuid>63e1f6b4-2665-480d-8054-02b0a3b799f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'goSelectLink' and @type = 'submit']</value>
      <webElementGuid>3c4f57e2-b3c9-4579-9e3d-895c9d1599f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
