<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields_freeText</name>
   <tag></tag>
   <elementGuidId>786e4659-6372-4375-b4bc-29b09cfbc89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='freeText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#freeText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7465269-599a-4718-a8b0-b185fc276958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>52a10fdd-8ca6-4acd-83dc-0270db9441df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>bc558f56-c517-4ad6-8324-a0cae96b0422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>108fbb0c-50f7-4eed-9de2-e4684c5f38d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3daff185-2197-4281-bfc6-0bc8311c09d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: freeText, event: { keyup: function (data,event) { showGo(event); return true; } }</value>
      <webElementGuid>7995b673-b5dc-45a4-ac9d-c85a771ee6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freeText&quot;)</value>
      <webElementGuid>310d0653-5ae0-4ad8-afe8-ab424b41650d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='freeText']</value>
      <webElementGuid>f2ddbd93-8dcb-42a0-bb36-9d8b20f0d13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form3']/div[2]/fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>5b6622fd-5df0-4c68-868e-9ff95eef67b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>dff2471a-c106-4cdb-a18e-5d9f935e8ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'freeText' and @name = 'freeText' and @type = 'text']</value>
      <webElementGuid>808abb57-f73d-44a3-927c-51464abb2812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
