<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IsMainAttachment(File Pop-Up)</name>
   <tag></tag>
   <elementGuidId>4f08d411-9fce-4e14-9ed6-c7dbf9148dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsMainAttachment_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsMainAttachment_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fe3a267-6c6d-4ebc-b5f6-f902006f052c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { id: 'IsMainAttachment_summary'}, disable: _selectMainAttachment, css:{disabled: _selectMainAttachment},  checked: fileArray()[page()].model.IsMainAttachment</value>
      <webElementGuid>82b1d426-8d67-4e9f-9578-cefef1489226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsMainAttachment_summary</value>
      <webElementGuid>e4170d71-32b6-4478-ab3f-395b5a296fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsMainAttachment</value>
      <webElementGuid>eafaefe3-848b-45ad-ae52-ee68029a251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db3d3603-f442-49b4-8dd6-1a95ac41e188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsMainAttachment_summary&quot;)</value>
      <webElementGuid>f3f63e8c-858e-479b-be43-a4af4560555c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsMainAttachment_summary']</value>
      <webElementGuid>6061a04b-1e36-40c7-9ea7-b694ca9a6492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-13']/div/form/fieldset[2]/ul/li[3]/div[2]/input</value>
      <webElementGuid>fae52bb6-36ad-40b5-bd04-6e4ebda2b118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li[3]/div[2]/input</value>
      <webElementGuid>35fa7645-e318-4ad7-90fc-c9232cdd3be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsMainAttachment_summary' and @name = 'IsMainAttachment' and @type = 'checkbox']</value>
      <webElementGuid>35e2cfef-64a0-498a-a5e4-0cdd6aebd14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
