<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IsMainImage(File Pop-Up)</name>
   <tag></tag>
   <elementGuidId>10537f17-9a99-4353-b89a-fff8f2f58662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IsMainImage_summary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;IsMainImage_summary&quot;)[count(. | //input[@data-bind = concat(&quot;disable: _applyToAllChecked(), css:{disabled: _applyToAllChecked()}, attr: { id: &quot; , &quot;'&quot; , &quot;IsMainImage_summary&quot; , &quot;'&quot; , &quot;}, checked: fileArray()[page()].model.IsMainImage&quot;) and @id = 'IsMainImage_summary' and @name = 'IsMainImage' and @type = 'checkbox']) = count(//input[@data-bind = concat(&quot;disable: _applyToAllChecked(), css:{disabled: _applyToAllChecked()}, attr: { id: &quot; , &quot;'&quot; , &quot;IsMainImage_summary&quot; , &quot;'&quot; , &quot;}, checked: fileArray()[page()].model.IsMainImage&quot;) and @id = 'IsMainImage_summary' and @name = 'IsMainImage' and @type = 'checkbox'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IsMainImage_summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3239f2f2-99b7-455e-8ad6-7d47c6ce1b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: _applyToAllChecked(), css:{disabled: _applyToAllChecked()}, attr: { id: 'IsMainImage_summary'}, checked: fileArray()[page()].model.IsMainImage</value>
      <webElementGuid>3cf11e03-5e46-42be-bec5-b0c9c6a1d764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsMainImage_summary</value>
      <webElementGuid>270e7eb5-b72e-4145-b66d-c7cc5c57afd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsMainImage</value>
      <webElementGuid>422b105a-9348-44b9-a106-531a8d06645d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>28df5a04-c253-4b62-ae5e-4f8b87700384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97257afb-36d1-4d31-b0f9-cb36cd08ada2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsMainImage_summary&quot;)</value>
      <webElementGuid>317a45c3-b693-470d-8e75-2d2080664ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IsMainImage_summary']</value>
      <webElementGuid>250f87de-7ac9-4916-a1fc-6565067010bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset[2]/ul/li[2]/div[2]/input</value>
      <webElementGuid>8b7f7ab9-0f0b-4210-b071-6e157893f00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/input</value>
      <webElementGuid>529dfb2e-bb8b-4307-b558-92367da824fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'IsMainImage_summary' and @name = 'IsMainImage' and @type = 'checkbox']</value>
      <webElementGuid>857625f2-e8fd-4347-be7d-5e98ddd50437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
