<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subtype(File Pop-Up)</name>
   <tag></tag>
   <elementGuidId>21006568-447f-4b37-b12f-6895c86d32cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubType_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SubType_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45a79fc0-489a-40f7-b86c-68d807055b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>e3002949-b8a7-480a-af2b-72d06dbf440f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { id: 'SubType_summary'}, options: clue.filteredLookup('ae2d85b1-1016-4c40-813c-6335c5e30b56', model.SubType(), model.Type()), optionsText: 'Value', optionsValue: 'Value', value: model.SubType</value>
      <webElementGuid>4b2ef1fc-03ba-487f-b621-faeb4f2aaba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubType_summary</value>
      <webElementGuid>a0a6dff1-e4a1-47bf-b631-3e312fefdcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubType</value>
      <webElementGuid>d85e5529-f2c1-4dd1-980c-e7e5843a0789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Subtype</value>
      <webElementGuid>71e27c39-f125-47fd-a740-61c98eaeca8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubType_summary&quot;)</value>
      <webElementGuid>caf490ca-139c-46f3-a20f-9037bdb33823</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SubType_summary']</value>
      <webElementGuid>5f5144ea-d268-40da-82c5-6e0fb6bdffa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-13']/div/form/div[2]/fieldset/ul/li[2]/div[2]/select</value>
      <webElementGuid>c71da8b4-3f36-4d2e-b123-98bada242c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[2]/following::select[1]</value>
      <webElementGuid>826ad9bf-d663-467b-8020-5f7c92ac3b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[3]/preceding::select[1]</value>
      <webElementGuid>d5feba25-c977-4e79-9ff9-177025a7f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/select</value>
      <webElementGuid>ed00c602-58c5-4892-beee-36b014b40c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SubType_summary' and @name = 'SubType' and @title = 'Subtype']</value>
      <webElementGuid>7b34e393-5544-4310-a3e8-0b242a126608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
