<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Another Column btn(New View)</name>
   <tag></tag>
   <elementGuidId>bea510ee-f3b8-45fd-ba09-9e376f30da1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ViewDetails_Columns_AddField</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Columns_AddField&quot;)[count(. | //button[@id = 'Columns_AddField' and @type = 'button']) = count(//button[@id = 'Columns_AddField' and @type = 'button'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ViewDetails_Columns_AddField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f4dda0f-0b2b-4ee6-9a41-4a31771a14bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center rounded-md border border-transparent py-1 sm:py-2 px-2 sm:px-4 text-sm font-medium text-blue-800 hover:bg-sky-100 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2</value>
      <webElementGuid>4a34f456-8f7d-4a90-a6ae-344f12958cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Columns_AddField</value>
      <webElementGuid>8112454e-06c0-4f67-8ed4-0adf706cd3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73e725b8-93be-400d-8cce-0fda9c43396e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Columns_AddField&quot;)</value>
      <webElementGuid>259a20fb-7832-46c2-b832-8ef695d8551a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ViewDetails_Columns_AddField']</value>
      <webElementGuid>8b52eb4d-fc37-4cdf-80d1-90943f1e57e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='columns']/div/div/div/div[2]/div/div/div[3]/button</value>
      <webElementGuid>acde086d-de45-4550-bc91-571012a2bc54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide'])[4]/following::button[1]</value>
      <webElementGuid>5c046730-f735-46c7-945a-102afabe3607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[5]/following::button[2]</value>
      <webElementGuid>e804727d-7453-45fd-82a1-90348936a3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply changes'])[2]/preceding::button[1]</value>
      <webElementGuid>3494fd56-fbcc-4972-8683-d4d883c2d2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>29f81fa3-effd-4949-864f-bad68af1ea08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ViewDetails_Columns_AddField' and @type = 'button']</value>
      <webElementGuid>e727976d-1dcc-40d1-b071-9c07e3ac3466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
