<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Columns(New View)</name>
   <tag></tag>
   <elementGuidId>1cbef00a-ca01-4192-b920-3c68bac51baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columns-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='columns-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d0ea8f16-6edf-42b8-b860-c5f4881bafdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columns-tab</value>
      <webElementGuid>0073cd28-e4fe-47e3-b0d1-87cddd901848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>columns-tab</value>
      <webElementGuid>6764063a-c796-4532-a969-ad675b8350a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#columns</value>
      <webElementGuid>9bd6764f-42bf-4fd8-a8e3-31a154e897da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>2ec53ce2-3917-4a55-8027-3ce448a82324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Columns
                </value>
      <webElementGuid>b71d0eac-e35e-4e57-9c75-5374abe70c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columns-tab&quot;)</value>
      <webElementGuid>c63ff6a9-047d-4bed-aa66-b4aee1eca08e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='columns-tab']</value>
      <webElementGuid>5ebee935-fcd4-47a8-a523-8164bb6da6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='NotesSearch']/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>9f7cf043-2e7b-407a-a1ae-b11e33873326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Columns')]</value>
      <webElementGuid>7e05994e-31d5-4e61-aa38-0100ee451a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[1]/following::a[1]</value>
      <webElementGuid>1f19ae39-f66c-44e1-8578-3e045db0691b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search notes'])[1]/following::a[2]</value>
      <webElementGuid>42519437-66fd-403c-9b43-cb486d18a797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::a[1]</value>
      <webElementGuid>e5ce4d37-f8e0-4e0d-94d8-99f105464537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters'])[2]/preceding::a[2]</value>
      <webElementGuid>361854ec-95cf-438e-a6bd-5f5a8c29fe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Columns']/parent::*</value>
      <webElementGuid>0b5e4598-eaa5-4d1e-9a87-b42fd09f0d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#columns')]</value>
      <webElementGuid>a55fc64f-6ea8-4f28-90af-73cd451d9a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>a1aacec3-de67-4872-9ffc-1e8b84d867f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'columns-tab' and @name = 'columns-tab']</value>
      <webElementGuid>1868719d-c0ed-40df-84e2-55384269e19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
