<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HideBtn(View)</name>
   <tag></tag>
   <elementGuidId>4f4e288b-0b14-42d3-be9a-359d47928f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ViewDetails_Columns_Columns_Data_1__Hide</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'ViewDetails_Columns_Columns_Data_1__Hide' and @onclick = 'hideShowSearchColumn(this)' and @type = 'button' and (text() = 'Hide' or . = 'Hide')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ViewDetails_Columns_Columns_Data_0__Hide']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4a5134f-2ad1-4c54-9139-e6887cdbd821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center rounded-md border border-transparent py-1 sm:py-2 px-2 sm:px-4 text-sm font-medium text-blue-800 hover:bg-sky-100 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2</value>
      <webElementGuid>0ea3eeb8-0570-4dc4-a09e-091c48e3f819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ViewDetails_Columns_Columns_Data_1__Hide</value>
      <webElementGuid>0fd56691-2e92-468e-8ff0-f01183cba75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideShowSearchColumn(this)</value>
      <webElementGuid>91f99a4c-576e-46d7-8d43-afccca3a0514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f602103-0231-44fe-8b0f-584dadb63db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>db1b588c-55d9-4efd-b534-03569269f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ViewDetails_Columns_Columns_Data_1__Hide&quot;)</value>
      <webElementGuid>865cea40-ff89-4d27-a2cc-5586cb5970ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ViewDetails_Columns_Columns_Data_1__Hide']</value>
      <webElementGuid>8c21e638-c3cc-42b2-9031-633485c1d268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ViewDetails_Columns_Columns_Data_1_']/div[3]/div/div/button</value>
      <webElementGuid>7fed1fa1-9362-4cdf-bfee-6227c4b62e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[3]/following::button[1]</value>
      <webElementGuid>08cb2ac2-e564-4c06-9ba7-6ae577d41d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[3]/following::button[1]</value>
      <webElementGuid>573a653e-80a4-4bfa-85e7-4ec18d16fefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move up'])[3]/preceding::button[1]</value>
      <webElementGuid>6a33f208-6741-43e2-b3cb-2551a98f4c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move down'])[3]/preceding::button[2]</value>
      <webElementGuid>7d33ef5b-f6c4-4506-90de-dfbc922da29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div/div/button</value>
      <webElementGuid>ceff9192-a3dd-4b70-bd27-e49567006840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ViewDetails_Columns_Columns_Data_1__Hide' and @type = 'button']</value>
      <webElementGuid>600ab6a0-cf5b-42df-987d-b3ae65f2c453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
