<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OpenNotes</name>
   <tag></tag>
   <elementGuidId>3fee8fcc-e1af-4bac-8b33-587aa28fed18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1474cc8-bf62-46bc-ad48-96c16d783e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c4c31313-fabb-4d85-98f9-4f573f6c718f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute z-10 left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-sky-500 focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2 sm:left-6</value>
      <webElementGuid>6fcfac77-25a5-4541-805b-a7bb48604114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes&quot;)/div[@class=&quot;flex flex-col h-screen lg:h-full&quot;]/div[@class=&quot;-mx-2 pb-4 overflow-auto&quot;]/div[@class=&quot;inline-block min-w-full align-middle lg:px-2.5&quot;]/div[@class=&quot;shadow border-sm ring-1 ring-black ring-opacity-5 md:rounded-lg&quot;]/table[@class=&quot;min-w-full table-auto border-separate&quot;]/tbody[@class=&quot;divide-y divide-gray-200 bg-white&quot;]/tr[@class=&quot;cursor-pointer relative hover:bg-gray-100/[0.3]&quot;]/td[@class=&quot;relative border-b border-gray-200 w-12 px-6 sm:w-16 sm:px-8&quot;]/input[@class=&quot;absolute z-10 left-4 top-1/2 -mt-2 h-4 w-4 rounded border-gray-300 text-sky-500 focus:ring-2 focus:ring-offset-2 focus:ring-sky-500 focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2 sm:left-6&quot;]</value>
      <webElementGuid>e2b3780a-4785-4d1a-9a53-9a55a1227052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>4867778e-49de-4bc4-a5af-9c18425a4e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Notes']/div/div/div/div/table/tbody/tr/td/input</value>
      <webElementGuid>47b8bdac-8aca-47c3-8a8d-90fa7c2f1424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>054af092-323f-4026-a2a8-463571ed8c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>0e4344f1-b874-461d-acc7-8c734f5285b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
