<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DateTime of Occurrence</name>
   <tag></tag>
   <elementGuidId>89c6a657-4849-492b-b54e-3324fe77ba26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OccurrenceDateTime_picker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OccurrenceDateTime_picker</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;OccurrenceDateTime_picker&quot;)[count(. | //*[@id = 'OccurrenceDateTime_picker' and @name = 'OccurrenceDateTime_picker' and @type = 'text' and @class = 'datepicker-input block w-full border-transparent border-r-gray-300 rounded-l-md bg-gray-50 py-2 pl-2 focus:border-sky-500 focus:ring-sky-500 text-sm invalid:ring-red-500 invalid:border-red-500 invalid:bg-red-50']) = count(//*[@id = 'OccurrenceDateTime_picker' and @name = 'OccurrenceDateTime_picker' and @type = 'text' and @class = 'datepicker-input block w-full border-transparent border-r-gray-300 rounded-l-md bg-gray-50 py-2 pl-2 focus:border-sky-500 focus:ring-sky-500 text-sm invalid:ring-red-500 invalid:border-red-500 invalid:bg-red-50'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ff3241b-c632-48b4-91de-05813738b631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OccurrenceDateTime_picker</value>
      <webElementGuid>4f650522-d51b-4f6b-94dc-c2edeac07e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OccurrenceDateTime_picker</value>
      <webElementGuid>1cf7889b-0d32-49df-8125-baf96befa68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value-target</name>
      <type>Main</type>
      <value>OccurrenceDateTime</value>
      <webElementGuid>2327d2d5-f023-464d-99fb-3f9c16badfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>13/04/2023</value>
      <webElementGuid>51319a6d-2d63-4c43-96e2-da0cb01ccf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datepicker-format</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>f7919414-9eac-4e0a-9e60-ddd52042ca12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfuture-date</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>d8b085d7-3e40-4648-bc11-bf168635c80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d5026b9b-be3e-4ccb-89e4-62aac368b5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker-input block w-full border-transparent border-r-gray-300 rounded-l-md bg-gray-50 py-2 pl-2 focus:border-sky-500 focus:ring-sky-500 text-sm invalid:ring-red-500 invalid:border-red-500 invalid:bg-red-50</value>
      <webElementGuid>4a672b3a-bcd7-4daf-a2c5-5e307ff7b7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select date</value>
      <webElementGuid>d84906e5-613a-4985-96de-f1a3431c7e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OccurrenceDateTime_picker&quot;)</value>
      <webElementGuid>43867c3d-f846-44e2-80e3-42ca36a179dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OccurrenceDateTime_picker']</value>
      <webElementGuid>dafa8001-7d46-45e4-89f7-b848e5f48ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noteCrudModal']/div/main/div[5]/div/div/div/input</value>
      <webElementGuid>64b9796d-bb93-4d60-ad8c-7feb9cc33916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[5]/div/div/div/input</value>
      <webElementGuid>1b0f9264-02ce-4440-bdbf-3f9ff6748405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OccurrenceDateTime_picker' and @name = 'OccurrenceDateTime_picker' and @type = 'text']</value>
      <webElementGuid>fcd4bf1e-1524-402a-91fd-ca13d4bc9ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
