<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Search Box(New UI)</name>
   <tag></tag>
   <elementGuidId>b4c40a80-4d67-4a40-81db-c0b2f14d71b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchBox_InputText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchBox_InputText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76216286-1ea8-4ba3-b0ed-bddbeb850571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchBox_InputText</value>
      <webElementGuid>dcb434f2-81f8-47d6-9ca2-3472d0379589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchBox.InputText</value>
      <webElementGuid>569e53a9-548e-487c-b231-53c188de2ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40042ba8-b875-49b2-ae7d-6240419c1812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full min-w-[14rem] border rounded-md border-gray-300 py-2 pl-2 pr-10 focus:border-sky-500 focus:ring-sky-500 text-sm</value>
      <webElementGuid>113d31df-a96d-47b1-9d89-545af9469514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search Box</value>
      <webElementGuid>f39cb8ef-ea04-477b-9f32-0a81d131edfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchBox_InputText&quot;)</value>
      <webElementGuid>3a5a3fa9-3bb9-4071-a037-8c1be8e54b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchBox_InputText']</value>
      <webElementGuid>8f3fd91f-8d7c-4b96-a8d6-12e0d84c7f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PageSearchForm']/div/div/div/div/input</value>
      <webElementGuid>d7a8662b-cd6d-4267-acdf-05e22ddfbf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>7d16a62d-3410-46fa-bd1c-70e79f9e8cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchBox_InputText' and @name = 'SearchBox.InputText' and @type = 'text']</value>
      <webElementGuid>82b7b1a3-608d-4d4a-8e36-a670b3fab0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
