<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sort Radio Btn(New View)</name>
   <tag></tag>
   <elementGuidId>08433d94-e998-4325-bf30-ee48ca577a1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ViewDetails_Columns_SortBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ViewDetails_Columns_SortBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0613eff4-ebd3-44fd-9c62-bc5100156320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ViewDetails.Columns.SortBy</value>
      <webElementGuid>2ffe24d0-74b9-4628-a730-e55977920e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ViewDetails_Columns_SortBy</value>
      <webElementGuid>09d76846-adf1-4d4d-9742-8083c618cb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>286841cc-3b76-4bfd-99b4-c97e7da9c163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 border-gray-300 text-sky-600 focus:ring-sky-500 peer</value>
      <webElementGuid>6edc0d6a-ae3f-4b1e-91d3-0640bb072888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ViewDetails_Columns_Columns_Data_0_&quot;)/div[@class=&quot;flex w-full sm:w-40 pl-2.5&quot;]/div[@class=&quot;flex items-center&quot;]/input[@id=&quot;ViewDetails_Columns_SortBy&quot;]</value>
      <webElementGuid>e02c006d-039d-4344-9503-c8e5a0d41fa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ViewDetails_Columns_SortBy']</value>
      <webElementGuid>36e04122-d013-46d2-a8e3-79652408b2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ViewDetails_Columns_Columns_Data_0_']/div[3]/div/input</value>
      <webElementGuid>a00788a2-d95e-4f28-93fb-0041299c562c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>eecb0dc5-9858-4880-b26d-59ea6405fce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ViewDetails.Columns.SortBy' and @id = 'ViewDetails_Columns_SortBy' and @type = 'radio']</value>
      <webElementGuid>ace50fb5-3e72-4f31-b656-fa6b2cdb4596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
