<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ViewName(New UI)</name>
   <tag></tag>
   <elementGuidId>6a1aebf8-d3d3-45b8-babe-988530a1a1c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Settings_ViewName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Settings_ViewName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a1b9773-c330-4b6a-83d8-581367ca37c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Settings_ViewName</value>
      <webElementGuid>4b045a41-4b78-41ec-8371-5363c3bc8905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Settings.ViewName</value>
      <webElementGuid>63e1bf88-e269-489e-9f83-9ef610e00cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add view name</value>
      <webElementGuid>03be5ba9-a560-4fb6-85e6-6d77928c3073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1f0edb0-fc3f-4bfd-8644-0c773391b1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Settings_ViewName&quot;)</value>
      <webElementGuid>247cb037-7d74-4012-8994-537e3e445898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Settings_ViewName']</value>
      <webElementGuid>88d73b51-5d8f-4c3b-8135-f6c5996dd633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='settings']/div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>c18ca637-ab80-4de6-aebf-151a332e3765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>090035b3-6865-4163-a93c-304cbd1a8c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Settings_ViewName' and @name = 'Settings.ViewName' and @type = 'text']</value>
      <webElementGuid>973ee404-fd5b-4169-8482-a674f08657d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
