<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CloseDate(Case Pop-up)</name>
   <tag></tag>
   <elementGuidId>1d0fe905-3f24-4f63-b5d4-5117482ccd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='closedate_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closedate_summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e104965a-cc58-4f4d-83d3-fd751a925ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line date hasDatepicker</value>
      <webElementGuid>37c42c5c-fa86-45c2-822e-c85251a4cdeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { id: 'closedate_summary'}, datepicker: model.CloseDate</value>
      <webElementGuid>a76722ec-016f-43d6-99a7-ec8332d14487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closedate_summary</value>
      <webElementGuid>d091f6ae-155d-42d5-9cec-48881d389852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CloseDate</value>
      <webElementGuid>a3eed1ba-d3fb-41c2-960f-831abae7da3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close Date</value>
      <webElementGuid>91802283-11f0-45fc-aa59-33f24bff7a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b56b029-db00-4749-b767-2d28b116da52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25aa8f36-bddf-4e67-9114-214516e2afe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>25835bf3-c371-489b-a5dd-3b8585c0bbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closedate_summary&quot;)</value>
      <webElementGuid>36e56e69-3e7c-4909-a917-0cfca387cf12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='closedate_summary']</value>
      <webElementGuid>9680720e-4e33-4f88-ba9f-4f94a4153d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/div/form/fieldset/ul/li[8]/div[2]/input</value>
      <webElementGuid>2b249c20-75c5-47db-b8f7-a7675c6cd88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[8]/div[2]/input</value>
      <webElementGuid>5d1a16d5-a6ce-4963-9731-ef46f932ca5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'closedate_summary' and @name = 'CloseDate' and @title = 'Close Date' and @type = 'text']</value>
      <webElementGuid>da9121f4-5083-4903-b1f1-9eb92337c92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
