<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select Type(Case Pop-up)</name>
   <tag></tag>
   <elementGuidId>b80563da-0b8d-406f-8f53-1744d5184e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Type_summary&quot;)[count(. | //*[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']) = count(//*[@id = 'Type_summary' and @name = 'Type' and @title = 'Type'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Type_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>406ba7c3-3e45-4c3b-8409-10865bf1f67b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>c0ead952-c714-4945-9e21-6523cdd8337f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr:{id: 'Type_summary'}, options: clue.filteredLookup('249aa86d-2a2c-4323-b453-16a64fee064b', model.Type), optionsText: 'Value', optionsValue: 'Value',  value: model.Type,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'4c14f159-cb25-47bb-af3e-adec30df122d', model.Subtype, model.Type);}}</value>
      <webElementGuid>0943f91c-f844-4e86-b347-6e861739d739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>a4602c9b-e5b4-4367-9250-e837822233c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_summary</value>
      <webElementGuid>8ab10d07-86ea-401e-8ed8-522651149418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>c764d69b-24a1-4e20-9fa0-baf0cef9b5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>0a7a9112-dbb3-4fa4-8402-47911bb37a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type_summary&quot;)</value>
      <webElementGuid>5ce23c20-a65a-4427-aaba-e176380703da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Type_summary']</value>
      <webElementGuid>ee113d81-e4cf-4769-95d7-ecad3a9662a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/div/form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>33efe56a-58d0-4121-892e-991316521131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[5]/following::select[1]</value>
      <webElementGuid>9c01a072-8a53-4eee-acc5-04a0ec6fa789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[3]/preceding::select[1]</value>
      <webElementGuid>ce3156d0-b552-467d-8708-339fe6211821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>132957dc-0c9a-4656-a09a-0bdd0c353077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']</value>
      <webElementGuid>1028e3a4-0b8a-4f5f-ba54-da0c8f83bf09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
