<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StartDate(Case Pop-up)</name>
   <tag></tag>
   <elementGuidId>f2ef4613-af83-4ac3-b32b-65744ac28107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startdate_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startdate_summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f33cda8-132a-4058-8626-be6e96dba8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line date hasDatepicker</value>
      <webElementGuid>4132652b-945a-4815-8903-404a49520c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: 'startdate_summary'}, datepicker: model.StartDate</value>
      <webElementGuid>cb2df7af-0de9-4b0f-b1ba-ac7b3b81a22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startdate_summary</value>
      <webElementGuid>8fbf7872-3f20-47f6-a0aa-36948fc22f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartDate</value>
      <webElementGuid>aa981cf1-2e2f-4e12-9d05-5cb670647dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Start Date</value>
      <webElementGuid>16257927-260e-4c2e-a2eb-a20a76ef6adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29ed6a84-fcac-4e83-bdd3-da4b246aac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>im-insert</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29bb9048-95e9-449a-a473-f3f82b225b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>671046b1-d561-4aff-935c-3b39d180665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startdate_summary&quot;)</value>
      <webElementGuid>3e8ddd88-3e33-4821-9bdc-96f4be719620</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startdate_summary']</value>
      <webElementGuid>4fe1d2b0-f687-49b7-93cb-9b4e75fe014f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/div/form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>383795c7-d0ad-47d1-8648-55af8a93a5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>d6a24ba8-fbbe-4c67-8c8b-9d5fde95d9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'startdate_summary' and @name = 'StartDate' and @title = 'Start Date' and @type = 'text']</value>
      <webElementGuid>0e197f74-ee08-42b2-bf83-b1cf1b79f47c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
