<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AllocatedToField(Task Pop-Up)</name>
   <tag></tag>
   <elementGuidId>699f91cc-604a-42a4-9fb6-b3ea62726be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AllocatedToTeamAsText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AllocatedToTeamAsText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22aef62d-a5a6-4143-932c-17033ac04c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>ff773f3b-cf91-485d-a4c8-013dbcd6bce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>visible: toggleAllocateVisible, options: model.RedactTeams(), value: model.AllocatedToTeamAsText, optionsCaption: 'Select a Team'</value>
      <webElementGuid>13039d4c-ff75-47ee-b737-ecc0152884cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8fac5027-2b2e-4185-acd4-e599590999d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-fieldmanagementrequired</name>
      <type>Main</type>
      <value>The To field is required.</value>
      <webElementGuid>5f16eb3a-42af-4ca4-b8c9-267f620b24d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-fieldmanagementrequired-dependentproperty</name>
      <type>Main</type>
      <value>AllocatedToTeamAsText_summary</value>
      <webElementGuid>953cab6d-1b17-4488-85e6-9b85a0cc4071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AllocatedToTeamAsText</value>
      <webElementGuid>deef28e5-ece9-4de1-805b-ec40049ef820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AllocatedToTeamAsText</value>
      <webElementGuid>eb8847b9-5510-46ca-9134-384e1141eef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Allocated To</value>
      <webElementGuid>aa716b5b-223d-4365-a40c-26bfe94e0971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a TeamRedact
</value>
      <webElementGuid>320f26f8-880e-4fdc-ad18-35bd3d33a27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllocatedToTeamAsText&quot;)</value>
      <webElementGuid>df5735d7-d8c9-4c85-9fd2-3915d7d3eba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AllocatedToTeamAsText']</value>
      <webElementGuid>cf6caec8-1e2b-45ca-9b2f-319a40cea091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/div/form/fieldset/ul/li[8]/div/select</value>
      <webElementGuid>c72b5221-87ee-415a-ad4b-61471e66428c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allocated To:'])[1]/following::select[2]</value>
      <webElementGuid>4141e76a-e3fe-46a8-96b3-fdfe4b42211f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[2]</value>
      <webElementGuid>4dc8f0f1-bdcf-4f5b-af93-1d70a0961290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allocated By:'])[1]/preceding::select[1]</value>
      <webElementGuid>2732227b-7698-44e7-8a46-0514bb3fc4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prasad'])[2]/preceding::select[1]</value>
      <webElementGuid>5b9324ee-bcbb-46fe-8c08-2afd70b84498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/select</value>
      <webElementGuid>31979ecb-8d43-4bc8-a6fd-a4ed092b4e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AllocatedToTeamAsText' and @name = 'AllocatedToTeamAsText' and @title = 'Allocated To']</value>
      <webElementGuid>ba9ff095-6e29-4f23-b369-0e8c23acb4cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
