<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notes(Task Pop-Up)</name>
   <tag></tag>
   <elementGuidId>2c2133eb-5203-469d-9435-1147198b832e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Notes_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Notes_summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d5330e65-c5c7-4676-84e3-1c28dbee86d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>67506a3b-e7a1-4d01-bcd7-2785ca645b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Notes_summary</value>
      <webElementGuid>48b751fe-655a-468e-902a-ab3ee7b9f9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>d1580a09-5d64-40ca-b367-18530527fff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>b3f0405e-8920-460a-9c1b-5ae74a06d824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes_summary&quot;)</value>
      <webElementGuid>dd1607b4-18d7-422e-85fd-f10a7f7afd81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Notes_summary']</value>
      <webElementGuid>58ce026f-69fb-424f-892f-f0468c85d83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/div/form/fieldset/ul/li[4]/label/span[2]/textarea</value>
      <webElementGuid>2b803b54-32ad-45ce-a877-68c06f405269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/textarea</value>
      <webElementGuid>4fd5bb53-574b-41be-a3d0-159767fb8583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Notes_summary' and @name = 'Notes' and @title = 'Description']</value>
      <webElementGuid>2ae5647e-d705-4e84-a21b-13fdf24cffad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
