<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomFields_Section</name>
   <tag></tag>
   <elementGuidId>d01aec79-c995-40c2-b133-86d2e50db794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>fieldset:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[5]/fieldset[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fieldset</value>
      <webElementGuid>fa3662e8-a62f-4dc1-8c87-33e9d2b435b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[5]/fieldset[2]</value>
      <webElementGuid>341102d7-a8ee-4ae7-9b31-571a43ec5a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset[2]</value>
      <webElementGuid>8c3a3507-0d11-4013-a145-6907fcf5b8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>tes</value>
      <webElementGuid>9199a4bc-5b25-4086-9206-9971bf27db28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/fieldset[2]</value>
      <webElementGuid>87a578ee-fa7a-4255-9f4d-8b98e21ca09f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
