<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>moveToBottom(CustomFields)</name>
   <tag></tag>
   <elementGuidId>fbc8bc9c-2a5b-4247-a6bc-5bebf7df89fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moveToBottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='moveToBottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4b967ce-91dd-4616-b047-3acc9d0d9647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moveToBottom</value>
      <webElementGuid>7f5d274f-8d94-4e95-9e4e-9457d13c3890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moveButtons1 fas fa-arrow-to-bottom fa-2x</value>
      <webElementGuid>d1e981c1-d62c-48de-bd44-4e8c20070af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { height:'34px', width:'20px'},click: moveToBottom, disable:!isToBottomEnabled(),  css: { disabled: !isToBottomEnabled() }</value>
      <webElementGuid>baeac932-1ded-44cc-8c43-6af00d72c92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>34px</value>
      <webElementGuid>12ca5545-300f-4b0d-9564-128444170cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>9ebf1f78-57af-464f-bede-a3a229b45f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moveToBottom&quot;)</value>
      <webElementGuid>9399d791-9df6-4732-bc98-354db2685a01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='moveToBottom']</value>
      <webElementGuid>3aa965b8-c3e1-4202-b48f-2ac0ed303118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customfieldEditor']/fieldset[2]/div[2]/button[4]</value>
      <webElementGuid>5c5ebfba-35d5-4129-b964-8a83d8c120a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>0c12d9fc-2f54-471f-b3d5-a711676b87b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'moveToBottom']</value>
      <webElementGuid>a6abbf2c-705f-4029-85c0-121c0b8640eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
