<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>personTitle</name>
   <tag></tag>
   <elementGuidId>0369c38d-f63c-42e6-933c-ac0864fa9151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/h3[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>4b3d9219-ec1b-485a-a150-cd9683212c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: summaryName(model.Title,model.Forename,model.Surname)</value>
      <webElementGuid>84c54290-3ea5-4a78-8d17-e8ab85760865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dr. Ford ANNIE</value>
      <webElementGuid>c1d4c7c6-a5e8-4dd5-843f-c549d085649a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;recordTitle&quot;]/h3[2]</value>
      <webElementGuid>69843761-8c0b-463a-944b-a8b7a08c8001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/h3[2]</value>
      <webElementGuid>5d3c12aa-f49d-4aa2-9b76-f005efb30786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[618]'])[1]/following::h3[1]</value>
      <webElementGuid>02412cd4-2069-4bba-ac9b-3a8b3baaec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Person Details'])[1]/following::h3[2]</value>
      <webElementGuid>d49d3487-40ce-40fc-b989-dc79194e094b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Rehomer)'])[1]/preceding::h3[1]</value>
      <webElementGuid>c282cba7-eff9-4d63-831d-be9465684d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Welfare Caller)'])[1]/preceding::h3[2]</value>
      <webElementGuid>803d9751-d8c3-4d17-998b-3d2e453ab50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dr. Ford ANNIE']/parent::*</value>
      <webElementGuid>ae6c513f-2f9a-4256-868e-fd85b999cc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[2]</value>
      <webElementGuid>5b5f5497-b5c6-499e-8e17-ff3b77a94c47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
