<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Linkfield_Register</name>
   <tag></tag>
   <elementGuidId>152f3583-3a8e-40af-bb1b-dce704db844f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-1']/form/fieldset/ul/li[9]/div[2]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@class = 'combo-box' and @data-bind = concat(&quot;options: clue.lookup(&quot; , &quot;'&quot; , &quot;e71a256d-a1c7-4f13-9068-c9f855dba2d1&quot; , &quot;'&quot; , &quot;), value: model.LinkComponentName&quot;)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f8b90b24-a534-42c9-bdfd-47083ddc94a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box</value>
      <webElementGuid>3bf361c8-5e8f-4a48-b50e-d5d115416fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c31a8935-c1f5-4c20-b097-45277cc93f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('e71a256d-a1c7-4f13-9068-c9f855dba2d1'), value: model.LinkComponentName</value>
      <webElementGuid>4c30610d-dcf2-4921-a647-2b4e5be179a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-1&quot;)/form[1]/fieldset[1]/ul[1]/li[9]/div[@class=&quot;field span7&quot;]/select[@class=&quot;combo-box&quot;]</value>
      <webElementGuid>218e1ffa-984f-47cb-9c21-66c8051185ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/form/fieldset/ul/li[9]/div[2]/select</value>
      <webElementGuid>bcd140a6-2be7-41f3-946a-10f4325e544a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::select[1]</value>
      <webElementGuid>301865cb-d7a1-4303-88f0-1aa725776342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>c65154b4-59b3-47fb-9099-82a7781823bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div[2]/select</value>
      <webElementGuid>87eb84f8-93a7-47e6-b31f-01447cde6ec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
