<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title(Select Event Pop-Up)</name>
   <tag></tag>
   <elementGuidId>c8b46cad-5258-4d4d-a797-642b717a9c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Title&quot;)[count(. | //input[@class = 'text-box single-line' and @data-bind = 'value: model.Title, event: { keyup: function (data,event) { showGo(event); return true; } }' and @id = 'Title' and @name = 'Title' and @title = 'Title' and @type = 'text']) = count(//input[@class = 'text-box single-line' and @data-bind = 'value: model.Title, event: { keyup: function (data,event) { showGo(event); return true; } }' and @id = 'Title' and @name = 'Title' and @title = 'Title' and @type = 'text'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bf12b3b-53eb-415a-b199-5601ee7a8fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>c1b6d1b7-0742-4658-99e7-048abbbb145a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Title, event: { keyup: function (data,event) { showGo(event); return true; } }</value>
      <webElementGuid>24a437f2-165a-498e-8fdb-1dc609fa36ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>9ee9ea14-48e8-4151-b5f5-13ea6c507266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>aa83fd15-207d-4974-9c9c-b85cc6b1faf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>d85a1cc1-3d94-442e-8f05-7ab809058f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a48d03d2-7b28-4380-9c85-61ccc1bd44a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title&quot;)</value>
      <webElementGuid>e247aace-ed07-4c9f-91e0-2efb555edb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Title']</value>
      <webElementGuid>d2d3addc-c186-4acf-8970-66ae9d2d2943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/fieldset/ul/li[2]/div[2]/input</value>
      <webElementGuid>ae2b6cd6-bef0-46ee-a297-bdf1aa962d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/input</value>
      <webElementGuid>f0c280e7-9ae4-4795-b35f-cd3c7f1f0d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Title' and @name = 'Title' and @title = 'Title' and @type = 'text']</value>
      <webElementGuid>ad1b1725-3028-4183-b4f7-bd674076b9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
