<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields(Pop-Up)</name>
   <tag></tag>
   <elementGuidId>76bb1f1d-104b-40b8-b4a6-b935b1ab73a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='freeText']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#freeText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc105347-fd33-4528-995d-ca791c6f45dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>01e55352-1b45-4f18-b91d-c0a0e8efcf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>a43e272f-dc68-4569-979f-45e72e9e87e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>03a4a281-a837-4055-b436-7f65447a6429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14b990b2-b2a6-4b3f-b131-2866eecbc0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: freeText, event: { keyup: function (data,event) { showGo(event); return true; } }</value>
      <webElementGuid>6e47605e-428a-4e20-bc92-2980535e743a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freeText&quot;)</value>
      <webElementGuid>a0d0fb46-1109-467f-b44c-d7d14d79e1ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='freeText']</value>
      <webElementGuid>cedd2ddb-2c75-4f5a-a223-d2db82648037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[2]/fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>5c5579d5-c0ea-4a67-b305-5a4c871a20ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>74d8dba4-7796-4fee-84d8-f3390d13211f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'freeText' and @name = 'freeText' and @type = 'text']</value>
      <webElementGuid>9bfed9f3-ec1e-4dea-8917-cf23f582788a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
