<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Currency</name>
   <tag></tag>
   <elementGuidId>bc299e7a-b34d-4240-bb63-2a39d66a0d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='custField_8458']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custField_8458</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e5cab8a5-37bc-46ca-b386-ec15b251d1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amound in £</value>
      <webElementGuid>3852752d-c617-4ae0-8f39-c9a030c0dfe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='custField_8458']</value>
      <webElementGuid>7ee10f5f-fe73-4af1-ab4c-2f7118d6320a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='customFieldsList']/tr[18]/td</value>
      <webElementGuid>843a5f89-0dcd-47ed-80ba-7e08cb93ef13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boolean'])[1]/following::td[1]</value>
      <webElementGuid>90c10206-5b83-4b68-8366-17feadcaf21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Conditional) Owned'])[1]/following::td[2]</value>
      <webElementGuid>8e84ebd7-12c9-4ad3-86a4-84d272696540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::td[1]</value>
      <webElementGuid>b1b68606-5a29-41de-9526-58db1535ef18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/preceding::td[2]</value>
      <webElementGuid>e4e27c1a-cc38-472c-822e-cd8e479aef0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Currency']/parent::*</value>
      <webElementGuid>962883bf-092e-4be6-98ff-4f17993e370c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td</value>
      <webElementGuid>2c0d0d55-932a-4f0b-8744-922b484475c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'custField_8458']</value>
      <webElementGuid>ff2c5f90-6fe0-4148-8a69-66247bf88b94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
