<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outcome</name>
   <tag></tag>
   <elementGuidId>48bb3fd1-ef5d-41ec-ac54-d86f287b66d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[2]/ul/li[2]/ul/li[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Outcome' or . = 'Outcome')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70692ecd-70cc-4f89-b6f0-9398dcdba3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jersey/Outcome/Index/0</value>
      <webElementGuid>75bb7673-fd12-4ea0-b58d-eaef9fa9739a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outcome</value>
      <webElementGuid>e4b38e2a-ad2f-4ce1-952d-f2300eb172f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;nav&quot;]/ul[1]/li[@class=&quot;span3&quot;]/ul[1]/li[13]/a[1]</value>
      <webElementGuid>d4077c6e-a3be-4e6a-9f5c-1a83cf7c9521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/ul/li[2]/ul/li[13]/a</value>
      <webElementGuid>b4e70905-2952-4960-b215-352c34b55ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Outcome')]</value>
      <webElementGuid>c8d04f52-e343-494e-8b45-1f1f74d5d3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/following::a[1]</value>
      <webElementGuid>8a380e99-8fda-4b71-8149-d119a5e6259a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[1]/following::a[2]</value>
      <webElementGuid>d8f41bcb-0071-4518-bd90-cba0bda32f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Person'])[1]/preceding::a[1]</value>
      <webElementGuid>725d0b05-4e63-4efd-931e-93eda6994461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Source'])[1]/preceding::a[2]</value>
      <webElementGuid>03402be3-e30d-498a-9003-52deb14fed70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outcome']/parent::*</value>
      <webElementGuid>74ae04ab-1ecb-4910-8891-0333ebb9b392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jersey/Outcome/Index/0')]</value>
      <webElementGuid>f69d2655-f65a-490a-8b05-f55ead9e5e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/a</value>
      <webElementGuid>a1b77a3d-d505-4020-803d-1220ce9de058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
