<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IntelligenceURN Hyperlink</name>
   <tag></tag>
   <elementGuidId>3728cbfb-fdc8-4644-95b8-1ec7bc497a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form1']/div/fieldset/ul/li[3]/div[2]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.field.span10 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87eee11d-bf8e-4698-a4fd-f5847f54122c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[1]/fieldset[1]/ul[1]/li[3]/div[@class=&quot;field span10&quot;]/span[1]/a[1]</value>
      <webElementGuid>af0b6b79-ac37-4da0-b485-7ecbfd9441c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset/ul/li[3]/div[2]/span/a</value>
      <webElementGuid>d859eff1-da19-4280-87ed-7ad99fd13956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'JCIS-21-H59DFX')]</value>
      <webElementGuid>9fed539d-8bbe-4b3b-b739-5d349c542e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intelligence URN'])[1]/following::a[1]</value>
      <webElementGuid>1e35787f-7b0c-48f6-bd5b-8ba399536c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JCIS-21-H59DFX'])[2]/preceding::a[1]</value>
      <webElementGuid>12258d3d-f389-4539-b55b-287e69d99e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JCIS-21-H59DFX']/parent::*</value>
      <webElementGuid>c81ecfb8-8abb-4a29-8489-ac505869d4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jersey/Intelligence/Details/0/41552')]</value>
      <webElementGuid>0111fdd1-d307-438c-8a40-3274fca00b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/span/a</value>
      <webElementGuid>dab69fed-83cf-4391-bebe-b5df2d426ec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
