<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_Subject</name>
   <tag></tag>
   <elementGuidId>5fcdab81-67ff-40d4-815f-1ac0a987fe24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field.span8 > #Surname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Surname_summary&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Surname&quot;)[count(. | //*[@id = 'Surname' and @title = 'Surname']) = count(//*[@id = 'Surname' and @title = 'Surname'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a05a5c2-94dd-4b8f-94ad-e9bdcef1d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>b0a02ae1-b82c-4ec5-b502-040427c9e6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>49d45d70-c295-440c-95b0-2c56e53a4186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>9e6c1a6e-a588-45e7-9b03-783abc58b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname&quot;)</value>
      <webElementGuid>1c37a85f-a85a-40a2-9317-591858d05e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b15d209e-ac5f-4851-ae78-cd15e0cd0433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Surname'])[2]</value>
      <webElementGuid>96956cb3-0984-4db2-8d4a-913f133c9a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>6b8b656e-c891-4eb1-a0a3-0e2c24d0e56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>3fb2d447-c4ec-48ef-a643-5c95d7abae4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname' and @name = 'Surname' and @title = 'Surname' and @type = 'text']</value>
      <webElementGuid>f80b8e02-f8cf-48a4-928b-dd9025cd2be9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
