<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forename</name>
   <tag></tag>
   <elementGuidId>cac155f4-f84f-4e76-a254-02664fe2a527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Forename_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Forename_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc729026-0c62-4abf-93a3-f649130b5a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>3d726e97-275f-440d-8597-f56821dd452a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr:{id: 'Forename_summary'}, value: model.Forename, style: {textTransform: 'capitalize'}</value>
      <webElementGuid>6f0c5970-820c-4c51-badb-7689d5bb490a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>571bd72b-734e-4135-8601-248657f493e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Forename(s) must be a string with a maximum length of 100.</value>
      <webElementGuid>56c18b7e-8535-4166-8ee9-c7be40096997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>92c9716d-3d47-47e3-912f-bd941e7ba174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Forename_summary</value>
      <webElementGuid>e5ba33b9-5786-4806-a5a5-bc4798534944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>c830aafd-5439-4433-913e-58412e55fabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Forename(s)</value>
      <webElementGuid>4ed81f6e-3e96-410c-9f1e-fb37077439d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06160f45-4805-488d-94af-4fb7276c69e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Forename_summary&quot;)</value>
      <webElementGuid>47abe55a-11e5-4ec3-a31c-73f19a128d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Forename_summary']</value>
      <webElementGuid>4aad6b5b-8c72-4e35-967b-38da069c8c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-8']/div/form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>5cd2d553-0778-466c-aeba-f3ed5cde110d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>369b5bc2-0c77-4ea6-9a07-8a3d5b2d81f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Forename_summary' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text']</value>
      <webElementGuid>8ffbf82b-fb67-42e5-8b04-edbc7a168487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
