<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Case Links(Inv. Summary page)</name>
   <tag></tag>
   <elementGuidId>aab4dbbd-ea22-4eb3-b9bd-c40c49eb3d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;LinksWrapper&quot;)/fieldset[3]/div[@class=&quot;listMarginTop0&quot;]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[2]/td[@class=&quot;clickable&quot;]/a[1][count(. | //a[(contains(text(), 'CA00002') or contains(., 'CA00002'))]) = count(//a[(contains(text(), 'CA00002') or contains(., 'CA00002'))])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'CA00002')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.listMarginTop0 > div.list.maxWidth > table > tbody > tr:nth-of-type(2) > td.clickable > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c725f13-e0fa-4c7e-a620-64d245eb04a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tennis/Case/</value>
      <webElementGuid>e72974b8-6da7-4f14-9791-388c8185cd6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { href: (($root.model.$type() == 'InvestigationViewModel' || $root.model.$type() == 'IntelligenceViewModel' || $root.model.$type() == 'IncidentViewModel') &amp;&amp; $data.$type == 'OrganisationSummaryLinkViewModel' ? $parent.targetDetailsUrl.replace('Person', 'Organisation') : ($data.$type == 'OrganisationSummaryLinkViewModel' ? $parent.targetDetailsUrl.replace('Person', 'Source') : $parent.targetDetailsUrl)) + '/' + $root.model.ContainerId() + '/' + Target.Id }, text: $data.InvestigationNo || '...', click: function (m, e) { e.stopPropagation(); return true; }</value>
      <webElementGuid>1c45c345-4509-4e75-8af9-49191c1684b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA00002</value>
      <webElementGuid>1ce29995-1c93-4ffd-9c1d-dfc32a800888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinksWrapper&quot;)/fieldset[3]/div[@class=&quot;listMarginTop0&quot;]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[2]/td[@class=&quot;clickable&quot;]/a[1]</value>
      <webElementGuid>15e2973c-60cc-460f-8e7f-5c6c17d8ad92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LinksWrapper']/fieldset[3]/div/div/table/tbody/tr[2]/td/a</value>
      <webElementGuid>a16fcf08-33b5-48fc-bdb7-e9f22ab1908d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CA00002')]</value>
      <webElementGuid>a49b5cc7-4f8c-4207-a990-f6610171ee69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tennis/Case/Details/150/60493')]</value>
      <webElementGuid>7b91f120-1dc2-43ec-a183-949d4579585c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/table/tbody/tr[2]/td/a</value>
      <webElementGuid>53fc960a-0ded-4870-b398-8392bb674d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
