<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Case Link(Record Links)</name>
   <tag></tag>
   <elementGuidId>c8d60af1-96f1-4292-83b9-b32d55c2c956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.listMarginTop0 > div.list.maxWidth > table > tbody > tr > td.clickable > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;LinksWrapper&quot;)/fieldset[3]/div[@class=&quot;listMarginTop0&quot;]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases'])[1]/following::a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f94c97f1-759d-46e4-bb21-c44441324fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/league/Case/Details/11/110728</value>
      <webElementGuid>4fee08af-87f6-4d3c-b0db-c6efd0616713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { href: ($parent.$type == 'OrganisationSummaryLinkViewModel' ? $parents[1].targetDetailsUrl.replace('Person', 'Organisation') : ($parent.$type == 'SourceSummaryLinkViewModel' ? $parents[1].targetDetailsUrl.replace('Person', 'Source') : $parents[1].targetDetailsUrl )) + '/' + ($parent.$type === 'InvestigationLinkViewModel' ? $parent.Target.Id : $root.model.ContainerId()) + '/' + $parent.Target.Id }, text: clue.formatColumnWithDefault($data, $parent, true, true, 'Details'), click: function (m, e) { e.stopPropagation(); return true; }</value>
      <webElementGuid>170f2566-b099-4aa0-bd6e-9316ba820595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>694</value>
      <webElementGuid>8a5cddff-9290-4924-bd97-539b7b4c6ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LinksWrapper&quot;)/fieldset[3]/div[@class=&quot;listMarginTop0&quot;]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      <webElementGuid>d1e88a75-b85b-42da-b58e-c62c3a23ad76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LinksWrapper']/fieldset[3]/div/div/table/tbody/tr/td/a</value>
      <webElementGuid>df1daa20-f20d-4dab-bdce-187aae9eecc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'694')]</value>
      <webElementGuid>d1ec4b33-f2b1-4705-b87e-fb8f5251393f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases'])[1]/following::a[6]</value>
      <webElementGuid>52ac5693-c408-4146-bce5-fa9c2dd6c2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 5 of 14 records'])[1]/following::a[6]</value>
      <webElementGuid>0443bed9-8450-49dc-943f-b60a54ffdb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Civil'])[1]/preceding::a[1]</value>
      <webElementGuid>52400b73-0d3c-48df-8397-7e6a613c6fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[2]/preceding::a[1]</value>
      <webElementGuid>e81257f7-44d9-4136-a6d0-62dd11e1b9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='694']/parent::*</value>
      <webElementGuid>fe3cb291-cd51-45ea-9906-c60e323afb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/league/Case/Details/11/110728')]</value>
      <webElementGuid>0be9317b-2172-497d-8a0f-6271dcaf855d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/div/table/tbody/tr/td/a</value>
      <webElementGuid>d29a18d1-6be5-462b-8f72-f8ecc0705ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
