<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_goSelectLink</name>
   <tag></tag>
   <elementGuidId>c874934a-83d9-45b6-a485-9ce0718e8e91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form4 > p > #goSelectLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='goSelectLink'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eb1483c-98fd-4ab7-a7c8-f7819d0b3b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>d42f4e44-8043-4290-b6e3-27015bfa93d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>515d96e3-cb24-4e3d-9226-d21ed3907379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5a6f56b1-2f07-4fea-8a1f-25be61bffbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>c29f7886-c7ae-446f-9a85-a5ab3e27934b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: disableGoButton, css : {disabled: disableGoButton}</value>
      <webElementGuid>500cf304-1797-4c01-b519-305089af1256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form4&quot;)/p[1]/input[@id=&quot;goSelectLink&quot;]</value>
      <webElementGuid>f7adb9c7-97a8-4862-9ec2-2784869cec50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'goSelectLink' and @type = 'submit']</value>
      <webElementGuid>b89f6017-f3ff-46b8-98fc-e485f716e375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
