<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>incidentTitle</name>
   <tag></tag>
   <elementGuidId>b863c257-6e08-4168-a32b-af1f17da4c6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/h3[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>ed0ea0ee-ab03-4356-9285-43d5b64882c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: summary(['Subject'],{ period: false })</value>
      <webElementGuid>b6f20bcf-36ad-4b3e-83cf-f9f6a54af9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incident relating to an illegal betting syndicate</value>
      <webElementGuid>95dc6ef1-c145-4118-9f32-077f5d568dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;recordTitle&quot;]/h3[2]</value>
      <webElementGuid>ad2a771f-a374-4712-b4d3-c4f21f9ac703</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/h3[2]</value>
      <webElementGuid>14d5d522-fb7d-47cf-9489-37119df3687b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[862]'])[1]/following::h3[1]</value>
      <webElementGuid>5aa60618-ec46-4a26-a64e-010169474dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident Details'])[1]/following::h3[2]</value>
      <webElementGuid>36fc9d12-ca7f-4c17-aa82-57590c0640fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security Classification'])[1]/preceding::h3[1]</value>
      <webElementGuid>4ea16685-85b1-435b-b559-007cfa2e0df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incident relating to an illegal betting syndicate']/parent::*</value>
      <webElementGuid>ecc65332-7f90-41b6-8078-bf4a460a2a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[2]</value>
      <webElementGuid>dc3a35bf-eabd-43a6-ac2a-656150f70134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
