<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Priority(Incident Pop-Up)</name>
   <tag></tag>
   <elementGuidId>6235cfaa-518b-41c6-954b-93023c3c96e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Priority_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Priority_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8f02a4b3-25b1-4fca-b6f0-c00545178595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Priority_summary</value>
      <webElementGuid>e349627e-cfab-455c-bb09-136bd63da27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Priority</value>
      <webElementGuid>d4ccfbda-836e-4ef6-b1f6-805cd702529d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Case Priority</value>
      <webElementGuid>74548dce-d73a-49ca-ac23-f3a40ce5d748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Priority_summary&quot;)</value>
      <webElementGuid>4df74659-b91a-48b8-9fed-2ac236a2be0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Priority_summary']</value>
      <webElementGuid>09f92610-e93d-4d07-af21-96200ae304ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset/ul/li[12]/div[4]/select</value>
      <webElementGuid>a6f4af49-015d-4d82-bc8c-084e9e849b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Priority'])[1]/following::select[1]</value>
      <webElementGuid>61d9f997-1295-44d7-973f-bad570d99234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/preceding::select[1]</value>
      <webElementGuid>e16abd0d-3435-44b8-bc18-76c11ede84fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div[4]/select</value>
      <webElementGuid>eb1ebfd0-2214-4a63-bfad-0928adfad424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Priority_summary' and @name = 'Priority' and @title = 'Case Priority']</value>
      <webElementGuid>4bf3debc-9948-45bd-a156-0ee9be2aa5e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
