<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subtype(Incident Pop-Up)</name>
   <tag></tag>
   <elementGuidId>c77c7961-bab4-4701-9bb6-3ac6000f7526</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubType_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SubType_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed223e0e-6b11-47bf-8eae-a1a8bf5e8182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubType_summary</value>
      <webElementGuid>08358134-05bb-4d26-b643-3dde1b7bab67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubType</value>
      <webElementGuid>458114d0-a261-4bef-b007-33d8c236da29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Subtype</value>
      <webElementGuid>4fb8cffb-85b7-49ce-a118-5e5a435d0dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubType_summary&quot;)</value>
      <webElementGuid>eb8499c9-1f7e-4ff8-9c76-e4b8cabb9f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SubType_summary']</value>
      <webElementGuid>dbac7a67-20cb-4f33-b753-ac40abd088ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset/ul/li[2]/div[2]/select</value>
      <webElementGuid>9ec4f21c-d4ca-4585-93ca-4e4c19755911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[2]/following::select[1]</value>
      <webElementGuid>bc8cf350-9889-4a72-a9a6-859719e5e526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference'])[2]/preceding::select[1]</value>
      <webElementGuid>90d585cb-b9aa-426b-85f8-0d22c00345f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[2]/div[2]/select</value>
      <webElementGuid>3b84776d-0f5f-40fb-800f-983cc7d14868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SubType_summary' and @name = 'SubType' and @title = 'Subtype']</value>
      <webElementGuid>e6014c61-9d85-4b86-926a-82100aea3213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
