<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TakenBy_TypeAhead(Incident Pop-up)</name>
   <tag></tag>
   <elementGuidId>7d81cc25-2987-42c1-9326-4bf5ef471afe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TakenBy_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TakenBy_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4783c597-12a3-49f6-aa24-1067fd46c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TakenBy_summary</value>
      <webElementGuid>41a47739-0ddc-4922-bdfb-65d61d8eeccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TakenBy</value>
      <webElementGuid>93c1eca1-a902-48b1-9c0c-5891f2d10c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af678376-d3db-46a1-9754-0db7d197f51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee18cd82-c4a9-4a70-b49d-4f80c5b52bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typeahead_added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b42766a5-995e-41a4-a32d-85ab0e71dc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TakenBy_summary&quot;)</value>
      <webElementGuid>b1b47844-04db-4cdf-af6d-bfed07e6c6f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TakenBy_summary']</value>
      <webElementGuid>d821b9ba-865e-471f-8c83-2d2597a9dcc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[4]/div[4]/span/input</value>
      <webElementGuid>bb8cd4dd-057a-4c11-8812-da8cebde8ade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>3636f27f-4203-49af-9495-8961625595f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TakenBy_summary' and @name = 'TakenBy' and @type = 'text']</value>
      <webElementGuid>fd0ce71d-896a-42bd-84ed-746827e9070b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
