<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TakenBy(Incident Pop-Up)</name>
   <tag></tag>
   <elementGuidId>d7d6cdc8-4def-4ee9-88b0-dfaff47d0afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TakenBy_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TakenBy_summary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;TakenBy_summary&quot;)[count(. | //select[@id = 'TakenBy_summary' and @name = 'TakenBy' and @title = 'Taken By']) = count(//select[@id = 'TakenBy_summary' and @name = 'TakenBy' and @title = 'Taken By'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>74020667-2987-44ed-928c-cc2e11769d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TakenBy_summary</value>
      <webElementGuid>0cf1c254-c538-4118-87a0-b7423df3b548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TakenBy</value>
      <webElementGuid>e04b776a-f68f-485e-8c56-518019c62f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Taken By</value>
      <webElementGuid>3d60b6f8-fe4f-4bab-bf2d-7202634c2c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TakenBy_summary&quot;)</value>
      <webElementGuid>641d6c37-71a4-4c72-be4a-f45bbe56f334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TakenBy_summary']</value>
      <webElementGuid>b033bcdf-cbf8-4397-b816-7df212badc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset/ul/li[4]/div[4]/select</value>
      <webElementGuid>e184c128-3893-4455-975a-988322e43035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taken By'])[2]/following::select[1]</value>
      <webElementGuid>6c615d62-7648-4d01-a080-3afae8b5cc10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How Reported'])[1]/preceding::select[1]</value>
      <webElementGuid>7243a8af-b266-416e-bb96-008ed19ea4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>5b2c3404-87b4-4d7a-923f-724a13ad7a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TakenBy_summary' and @name = 'TakenBy' and @title = 'Taken By']</value>
      <webElementGuid>8a3758dd-7999-4f05-a941-056ab98c8750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
