<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title(Incident Pop-Up)</name>
   <tag></tag>
   <elementGuidId>108efd5f-fe73-4f04-acd2-423f6ea22054</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Subject_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Subject_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4bcc1f7-0520-4d09-947f-3d7f7a077501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subject_summary</value>
      <webElementGuid>fdd63df5-799d-4a06-a991-3bff61c56b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>32af22f9-8123-4eec-8454-9a08e3297c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>f1836080-65f8-4bf9-9bf8-e0b71081d155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f41130a-7d9c-48f5-a453-452ad0b3ec1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subject_summary&quot;)</value>
      <webElementGuid>bed85f85-edad-4c0c-a7d3-86971f175d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Subject_summary']</value>
      <webElementGuid>8f099d84-b9e3-4146-8ce9-063125e04ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset/ul/li[9]/div[2]/input</value>
      <webElementGuid>cf4603c3-2f15-4407-be57-ead70fbf6283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[9]/div[2]/input</value>
      <webElementGuid>f1690c29-8d54-4f95-a0e1-fcdecc7ae52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Subject_summary' and @name = 'Subject' and @title = 'Title' and @type = 'text']</value>
      <webElementGuid>e3dd73ac-d92c-4675-a512-8a122e56c5a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
