<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Type(incident Pop-Up)</name>
   <tag></tag>
   <elementGuidId>43dc1397-5f82-4f2c-a8dc-df1655f1f84b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecordType_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RecordType_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>70582622-1f8a-4851-b151-e7958f7457c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>81efa96b-61d7-4d82-af75-13a9cc6152b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr:{id: 'RecordType_summary'}, options: clue.filteredLookup('676a17f4-c2e4-42ac-8bd7-6c1a62114844', model.RecordType), optionsText: 'Value', optionsValue: 'Value', value: model.RecordType,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'74ba829d-a57c-4df4-92b8-ecc21a335f85', model.SubType, model.RecordType);}}</value>
      <webElementGuid>3573e68a-694d-43b8-b0be-25a7e760614f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecordType_summary</value>
      <webElementGuid>d4cb00d1-9819-4ee0-b9a2-1667e1a36a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RecordType</value>
      <webElementGuid>fe145214-ef55-440d-ab69-8a8ec7188b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>4da1a46a-966a-4cb2-8f9a-a9387c5a886a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BadgerDeer HuntingDog FightingFox HuntingHare CoursingHare HuntingNotifiable AssociationOtherOther HuntingOther Wildlife CrimeShootingSnaringTrapping
</value>
      <webElementGuid>c6074a57-e0cf-48f2-8b41-1b1363d549de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecordType_summary&quot;)</value>
      <webElementGuid>e27e852a-bca8-4345-b3f3-7f9c473fe5e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RecordType_summary']</value>
      <webElementGuid>d853e0ce-fab6-4344-bc69-e7906b94d58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-4']/div/form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>fecb882c-6e1c-4efd-b41c-e9d4f71d1f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[4]/following::select[1]</value>
      <webElementGuid>f8160809-9d5c-4e57-aa26-5aef0339de50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[2]/preceding::select[1]</value>
      <webElementGuid>099546ba-5459-41ce-b862-467f275aedbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>06eb85c2-415f-4cee-be5e-fd3028ac7d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RecordType_summary' and @name = 'RecordType' and @title = 'Type']</value>
      <webElementGuid>7292a904-8a50-4fc2-b443-08c5bc33ff1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
