<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference_Reference</name>
   <tag></tag>
   <elementGuidId>d4a9c528-f981-40e9-b484-924c81fdb145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4095b810-891b-4e11-a07b-1d38fc41eed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>e8a3c202-66a4-4e82-b1d9-019bbac69e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Reference, attr:{maxlength: '25'}</value>
      <webElementGuid>dbb40127-414f-443e-9b8b-82454b9cfc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76395a7c-4683-4f0d-b3c0-602897e96f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>The Reference field is required.</value>
      <webElementGuid>6ba11ff6-3853-4a0a-9a15-c233029cdfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>IsExhibit</value>
      <webElementGuid>a044c1ed-4cc3-4fa5-8f93-8ea187cdea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-targetvalue</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5544cef0-9fd5-4801-8028-73dc5cf29827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>598341cd-8116-4788-b51f-f84ce55ab4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>bbb82cfa-690a-4862-b936-6a00427fce99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>aaee8fd4-cc06-463f-9e2c-c41cc3ce2298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ac85ee0-15e0-4397-beeb-95bc06e170ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>e72d2db4-12ba-4492-b4ef-f1714f9dc57e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reference&quot;)</value>
      <webElementGuid>fa483fd3-110b-4868-85ad-2621653d5330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Reference']</value>
      <webElementGuid>334a8cb4-8071-4fc1-a6f8-77e0a498235a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>4c57e183-2233-4c7d-a61a-5c0bde3a313f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div[2]/input</value>
      <webElementGuid>09e7a26f-cb4a-45ac-aa08-e70b826fe9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Reference' and @name = 'Reference' and @title = 'Reference' and @type = 'text']</value>
      <webElementGuid>3081dcbf-869a-4eb6-aed1-7eb348945b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
