<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields_goSelectLink</name>
   <tag></tag>
   <elementGuidId>c6d40fcf-3592-4c68-ab86-d1b697b97a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goSelectLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='goSelectLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4830e4b-4418-4429-9fa2-e7da4211f239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>d87489f1-656f-405a-b12c-714c92af6f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>471ad7c0-6fc1-4119-a110-e4d5b994391c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f51b5a4d-48d3-45f4-932f-80fc52e7d144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>95cb8a7c-a323-4b86-b692-8a5001d25c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: disableGoButton, css : {disabled: disableGoButton}</value>
      <webElementGuid>dc53fec9-f022-4069-92cc-d00352cd305a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goSelectLink&quot;)</value>
      <webElementGuid>c4d54079-b939-4e66-8b23-9f7d327267a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='goSelectLink']</value>
      <webElementGuid>dbf5d32b-7f2f-4095-ad34-985223ed84e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/p[2]/input</value>
      <webElementGuid>28b84ebc-5dfc-42d9-bd7d-a1efe1b25062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/p[2]/input</value>
      <webElementGuid>3114a0ce-e3dc-4736-be0e-64c43936e2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'goSelectLink' and @type = 'submit']</value>
      <webElementGuid>6bd66bb6-0e94-4d19-8e41-01dea3a6b543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
