<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CashDrugsElectronicsStewartWeapons</name>
   <tag></tag>
   <elementGuidId>de2f5194-a97c-4024-93bd-c5490108747d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c2507474-b475-4244-afb6-11005a2d6ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>e85548fb-5ff3-4218-bb2c-6bcba374c9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.filteredLookup('ddd1d42e-fd0f-454a-bddb-6d489dafa1c2', model.Type), optionsText: 'Value', optionsValue: 'Value', value: model.Type,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'3a985c33-c3e6-4989-b72f-052846c74ea7', model.Subtype, model.Type);}}</value>
      <webElementGuid>0d8110f4-7cae-4c5b-8cd1-7ac898fd2f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>8684f72e-9e0b-4580-8bd2-45de0d4fa1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>aebba260-b667-4834-ad9e-3262d9af7e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>5e78274e-e0e9-472c-9a26-59745c29aa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CashDrugsElectronicsStewartWeapons
</value>
      <webElementGuid>91871ab9-579c-4e12-bf0e-8f667983cb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type&quot;)</value>
      <webElementGuid>e684fb3b-9e45-4d18-93a5-b5afa06b6519</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Type']</value>
      <webElementGuid>87d676e0-55e5-4a5a-aa72-41cd85ad0622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>6a142cd1-cc0e-4816-9253-74e4b3de909b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>5cbe1214-b3d7-4483-ba79-5dc940f0280a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[1]/preceding::select[1]</value>
      <webElementGuid>708a5172-407c-4a0d-addf-942550d39414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>bbcc0212-8e03-46be-b363-3c8744198d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Type' and @name = 'Type' and @title = 'Type']</value>
      <webElementGuid>63f64e41-4e79-49ee-a019-624406895a7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
