<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CrossRegisterViews ChkBx</name>
   <tag></tag>
   <elementGuidId>2e7e5594-3557-4aa7-adad-af3e709edc26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advOptCrossRegisterViews</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advOptCrossRegisterViews']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cbc5782-4b7e-48bc-a7ca-7398448c1795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptCrossRegisterViews</value>
      <webElementGuid>472388bc-fc99-4626-976e-02be75222974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ad14e6f6-2b92-4f86-a811-0aa47717cae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: selectedView().IsCrossRegister, click: function() { if (selectedView().IsCrossRegister){ selectedView().DashboardOrder = false; clearBulkSelections(); }; updateAvailableColumns(includedFields()); setDirty(true); dummy.notifySubscribers(); return true; }</value>
      <webElementGuid>26a07e84-6fb6-4e9c-b30d-1e01f60ef574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptCrossRegisterViews&quot;)</value>
      <webElementGuid>3201a0dd-a841-4137-8f5e-54e6f108450e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advOptCrossRegisterViews']</value>
      <webElementGuid>38f71364-58d2-46cb-8bc6-dfcd512e6576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedOptionsDiv']/ul/li/input</value>
      <webElementGuid>febd99f2-9157-4a3e-bf0f-92aac4c7df76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>c1d8300a-7307-4a15-9624-8529142e84d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advOptCrossRegisterViews' and @type = 'checkbox']</value>
      <webElementGuid>ec9f933c-b6b8-4642-b852-1ecf60493960</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
