<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SortExpand</name>
   <tag></tag>
   <elementGuidId>837c6923-d49e-4612-8df8-7b43cb783ed8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advOptSortClose</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;advOptSortOpen&quot;)[count(. | //*[@id = 'advOptSortClose']) = count(//*[@id = 'advOptSortClose'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='advOptSortClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>24a30ff5-4847-4260-84e2-2738efb39e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptSortOpen</value>
      <webElementGuid>566ba578-4f95-4525-a550-ad2edb387263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h3-options advancedOptions</value>
      <webElementGuid>a74eb7ea-4e66-4a1c-ac4a-07deca243564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: toggleSortButton, visible: sortAreaVisible, event: { 'keyup': function(vm, e) { clue.tabIndexedOnKeyPress(vm.toggleSortButton, e); } }</value>
      <webElementGuid>833fa0fa-cc68-47ce-bcdb-9f6bd33715af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9431edd0-d895-41c2-886d-c8048b357755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort </value>
      <webElementGuid>b3a38543-899d-4aae-a03b-f60dd94ca8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptSortOpen&quot;)</value>
      <webElementGuid>711a0a17-5d84-498d-962a-b2499c46c764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='advOptSortClose']</value>
      <webElementGuid>3c1fbc7f-3383-445a-99fb-8ef5eaf9f59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedOptionsDiv']/div[7]/h3</value>
      <webElementGuid>7cd33b87-5893-42ca-a478-f18807b9d161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SELECTED COLUMNS'])[1]/following::h3[1]</value>
      <webElementGuid>ee260fa7-70c9-49be-a50b-2252a70e90bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AVAILABLE COLUMNS'])[1]/following::h3[1]</value>
      <webElementGuid>f3f59cbc-09b5-48af-b857-a2ed541e2df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[2]/preceding::h3[1]</value>
      <webElementGuid>164e8db0-2862-4a76-949a-ecc8c4281935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[2]/preceding::h3[2]</value>
      <webElementGuid>b47663c4-c70c-4af5-bc2b-0d3170256559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sort']/parent::*</value>
      <webElementGuid>1744e43a-a04e-4997-a3d8-195c99d18e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/h3</value>
      <webElementGuid>8a4dab05-7ddc-4096-8472-2568bd3b07ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'advOptSortClose']</value>
      <webElementGuid>72bcc2b9-1a18-4c6f-aba0-60b90c55d3b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
