<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Browse(SelectFilePop-Up)</name>
   <tag></tag>
   <elementGuidId>61fcc075-26e7-4534-af36-17a427f6d696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Criteria'])[1]/preceding::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;form2&quot;)/div[2]/ul[1]/li[1]/div[@class=&quot;droppable&quot;]/a[1][count(. | //a[@href = '#' and @data-bind = concat(&quot;click: function() { document.getElementById(&quot; , &quot;'&quot; , &quot;files&quot; , &quot;'&quot; , &quot;).click(); return true;}&quot;) and (text() = 'Browse' or . = 'Browse')]) = count(//a[@href = '#' and @data-bind = concat(&quot;click: function() { document.getElementById(&quot; , &quot;'&quot; , &quot;files&quot; , &quot;'&quot; , &quot;).click(); return true;}&quot;) and (text() = 'Browse' or . = 'Browse')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9131d107-d456-416c-90e1-3aae28ad0365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a78e8c78-c99b-4642-b7d7-e1a7f6f940fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: function() { document.getElementById('files').click(); return true;}</value>
      <webElementGuid>f76ae472-736e-4cc8-9a63-9e8c67d80f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse</value>
      <webElementGuid>d82717e6-6dec-4b0d-97bf-1964d24f1785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form2&quot;)/div[2]/ul[1]/li[1]/div[@class=&quot;droppable&quot;]/a[1]</value>
      <webElementGuid>c96fc0f7-15de-4b30-a243-a240f5a80a33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[2]/ul/li/div/a</value>
      <webElementGuid>2e756763-3e87-46ca-a444-a6ab0fc9f8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Browse')])[2]</value>
      <webElementGuid>239933af-d2f0-4d57-8149-ed20385b556c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File'])[2]/following::a[1]</value>
      <webElementGuid>8110547b-b754-410a-b3ea-676b8b005657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Criteria'])[1]/preceding::a[1]</value>
      <webElementGuid>38e0e746-fa99-4463-91b2-51989822f977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[85]</value>
      <webElementGuid>4ec1bf58-be8e-4fe3-ae17-e141afcf4437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div/a</value>
      <webElementGuid>1173bdc3-eaea-4828-a696-50953d12a995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
