<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields</name>
   <tag></tag>
   <elementGuidId>a68e6778-07ce-483f-b4f0-568334e78f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#freeText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='freeText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db662c38-e7ba-4611-8366-5a7a340ec6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>34a15ef6-b8bb-4336-a912-05ea1f695aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>freeText</value>
      <webElementGuid>c68415e1-8948-4da8-89a6-cf645364a3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;freeText&quot;)</value>
      <webElementGuid>eb36f91e-d941-4f51-9e4d-427dbd7bfb2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='freeText']</value>
      <webElementGuid>c8aff449-e750-42e5-a41f-cc570a1d8ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[2]/fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>5de4f754-9e57-4efa-8983-c827c6e6f7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/ul/li/div[2]/input</value>
      <webElementGuid>5bd1e79d-4b68-4727-a484-5639e5b11d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'freeText' and @name = 'freeText' and @type = 'text']</value>
      <webElementGuid>b5d9d63b-c5ae-4536-99ef-1421e7ad4b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
