<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search All Fields_goSelectLink</name>
   <tag></tag>
   <elementGuidId>40ad22ef-eaac-4568-8b79-af4cdd84be57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goSelectLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='goSelectLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5569e564-1ec1-460d-836c-6c7c957235fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>a7ca1600-315b-4732-b131-7f089b210ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goSelectLink</value>
      <webElementGuid>a7ea6583-38c0-4d27-98b7-7f24f299190c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>13735241-ff5a-42e1-988a-7fb2af03f454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go</value>
      <webElementGuid>7e3b5e3a-fa22-41a2-8768-81288c0535d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: disableGoButton, css : {disabled: disableGoButton}</value>
      <webElementGuid>03c0b0f6-54d9-4f5d-b732-8ecfdb3e0d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goSelectLink&quot;)</value>
      <webElementGuid>61209452-420f-4f0f-b49f-e1e70c325efd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='goSelectLink']</value>
      <webElementGuid>75e870cd-afe8-4b8d-b3f9-e0e529a85e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/p/input</value>
      <webElementGuid>664d7e7b-a851-4808-aa6f-809937fc4e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/p/input</value>
      <webElementGuid>aaed91bc-6a93-4897-922d-0104e9a40dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'goSelectLink' and @type = 'submit']</value>
      <webElementGuid>d71327d6-ce1f-46e9-a4fb-a93ef0a3b239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
