<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FileType</name>
   <tag></tag>
   <elementGuidId>ee699cd8-016a-4bba-9f3c-415181132dc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Type_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Type_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f46d29ea-4435-4e9f-8e61-ad51fca0ef4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_summary</value>
      <webElementGuid>b7aacb0d-cd79-425c-97d2-70a412e78f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>eaed567e-3dc3-4d00-8a70-bac153cf3ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>4d50714e-f79e-4b2d-bef3-660395872f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type_summary&quot;)</value>
      <webElementGuid>8dd0cc06-db81-46aa-8af3-331c3b5562a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Type_summary']</value>
      <webElementGuid>34100376-3d2b-4dae-bc99-d2b47c8a64ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-6']/div/form/div[2]/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>b5381bfd-58eb-40e1-b81a-af961c142643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[3]/following::select[1]</value>
      <webElementGuid>1c135e1b-6fc0-42de-ac39-6b2132008937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[2]/preceding::select[1]</value>
      <webElementGuid>a7714747-62de-4254-a3e5-366ae94ddcd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>9a9bdc2a-ea68-41c4-85a8-687fe59c922b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']</value>
      <webElementGuid>851b72c2-951e-4f3c-a287-d6a67a7d6e50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
