<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_5336</name>
   <tag></tag>
   <elementGuidId>50bd9540-e53d-4f7f-bb19-040eae427e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.clickable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form2']/div[3]/div/table/tbody/tr/td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;form2&quot;)/div[3]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;clickable&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>8115005a-0331-4d77-8831-8e13756fc042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: clue.formatColumn2($data, $parent, true), css: 'clickable', click: function () { $root.select($parent); }</value>
      <webElementGuid>30722823-08c1-41cb-8760-3ca404dba452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable</value>
      <webElementGuid>4b54d3fa-09e3-4378-97f4-2e76fdf9d384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3f354df7-12db-494f-adfe-e0bce86b849b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form2&quot;)/div[3]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[@class=&quot;clickable&quot;]</value>
      <webElementGuid>242c558d-5197-4e8e-bb5b-2b77d847e1a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[3]/div/table/tbody/tr/td</value>
      <webElementGuid>ffeaab0d-7728-49e7-80b6-3004385d6e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      <webElementGuid>bdb9c45c-a674-4746-b358-98c46ee1fa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results (495)'])[1]/following::td[1]</value>
      <webElementGuid>a36432ee-8d57-4d98-949a-c18139871dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Material'])[3]/preceding::td[1]</value>
      <webElementGuid>e5eb45a7-ce7a-4c2c-b130-8ea7eb754d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lois Lane picture'])[1]/preceding::td[2]</value>
      <webElementGuid>c65a31c8-e88f-46c1-8436-de902a017563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5336']/parent::*</value>
      <webElementGuid>d0528131-e558-4743-b507-8e1eec8e6eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td</value>
      <webElementGuid>5aceaced-75ee-44cc-8f6e-9ee2a8a08e15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
