<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname</name>
   <tag></tag>
   <elementGuidId>e13b1523-32a8-4d18-8b05-d2735ad7e509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Surname'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440dfedf-e5a6-49bd-848d-ca9166fe4be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Surname</value>
      <webElementGuid>e58e032f-2294-4b7b-b881-9f81564c1618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>31d3bd5c-fdbe-4b94-930c-116342a4bd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>8d8d58ea-b152-4c0d-8b58-5efa94872a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>4ba31452-9d0d-4414-99b1-1662754326a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form2&quot;)/div[2]/fieldset[1]/ul[1]/li[3]/div[@class=&quot;field span8&quot;]/input[@id=&quot;Surname&quot;]</value>
      <webElementGuid>19c698d1-2b9b-4be7-96b3-a32050a0efe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Surname'])[2]</value>
      <webElementGuid>2987174c-ccc5-4c13-a33f-3397be54b248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[2]/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>66ea41b1-97f6-45e8-a72e-6bcc354d4bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>3feb0807-0c30-46b5-9014-a7b67beb95a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname' and @name = 'Surname' and @title = 'Surname' and @type = 'text']</value>
      <webElementGuid>9b668603-ea20-49d4-a7ac-691497c095ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
