<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forename(s)</name>
   <tag></tag>
   <elementGuidId>592cf297-46b8-45c5-a4b5-28ce2d1aca8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc29e4b8-348c-4451-8fa0-4fcc8608bfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.FirstName</value>
      <webElementGuid>d5b57416-6cee-48e3-b61c-7bf7a8395629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>33578d36-6b34-4316-a8f5-ee91a64b0c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>92551734-b463-447c-b6bf-7a99f0f1c36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Forename(s)</value>
      <webElementGuid>8b83d984-de47-42a8-8fee-c221a655d913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FirstName&quot;)</value>
      <webElementGuid>91694ae7-2c0a-4919-a84b-b4fb0ffcbb15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FirstName']</value>
      <webElementGuid>6057acd0-2bad-4d02-a9dd-a5bcfae036c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div[2]/fieldset/ul/li[2]/div[2]/input</value>
      <webElementGuid>64a3a18d-c0fe-47ca-8ae9-9d365a556f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/input</value>
      <webElementGuid>0f7efa19-a309-48ce-9a91-01c13382a225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FirstName' and @name = 'FirstName' and @title = 'Forename(s)' and @type = 'text']</value>
      <webElementGuid>e4c39114-f52a-4116-95db-855b34e90cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
