<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Person_HRSearch</name>
   <tag></tag>
   <elementGuidId>7b989087-0fc1-4ea7-b444-2fae17f016b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AmazonHRSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AmazonHRSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c53c86da-24fa-4cdc-a555-ee3a52ad8ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>858b1658-dba0-4a01-ae64-5f949674d32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AmazonHRSearch</value>
      <webElementGuid>b7aeb344-c27d-489e-be88-ca39b061a76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AmazonHRSearch</value>
      <webElementGuid>619ae4e7-4786-4176-a65d-fac594e77417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AmazonHRSearch&quot;)</value>
      <webElementGuid>5444b216-0a83-467a-a2c8-e5c26b470275</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AmazonHRSearch']</value>
      <webElementGuid>1aedfee1-e0f2-4faa-b117-524e931e1509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div/input</value>
      <webElementGuid>7428682f-68c5-4ace-9db4-465f2750591e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>746243e0-7acd-43d4-9a7c-e7d2b9313589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'AmazonHRSearch' and @id = 'AmazonHRSearch' and @title = 'Add details for a Person from Amazon HR database']</value>
      <webElementGuid>2ee66804-b83b-42aa-aa2e-be09740fc1b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
