<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Person Search</name>
   <tag></tag>
   <elementGuidId>99003435-6d8c-4766-930c-75427d890e7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ui-id-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61576846-fbfb-4e21-a681-b321d90e48bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-2</value>
      <webElementGuid>a38f2220-cc41-4e3a-9611-973495b3b590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Person Search</value>
      <webElementGuid>c8f3044b-8e3b-4a44-ae4d-ff92ff380d18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ui-id-2']</value>
      <webElementGuid>6316b8df-2cb4-4965-a092-1de69f498277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ui-id-2', '&quot;', ')')])[1]/following::span[1]</value>
      <webElementGuid>867f0cd9-956c-49f4-84f4-fcc2ddf8be99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[1]</value>
      <webElementGuid>443add12-bc6b-428f-871e-201e7597f642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::span[1]</value>
      <webElementGuid>4e6321a3-a81c-4c39-8488-5cd42aca7d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please correct the following:'])[2]/preceding::span[3]</value>
      <webElementGuid>7d6dc0f1-df76-4048-b9af-a0eceb4b7fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Person Search']/parent::*</value>
      <webElementGuid>1df04c66-14c5-458c-9ea4-c1b9bee126e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span</value>
      <webElementGuid>7e8acff4-5593-4a56-af63-7129b4115aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ui-id-2']</value>
      <webElementGuid>2a983a12-adde-484f-91cd-d840d56c1b0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
