<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Person</name>
   <tag></tag>
   <elementGuidId>05fa3913-1eb3-47eb-9a6a-5801dd0e20b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Configuration']/div/div/div/table/tbody/tr[12]/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50cadcd7-31d5-46c5-be0e-f99c6e1d89ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Person</value>
      <webElementGuid>77a84412-e4d3-49ee-874a-682b8f97656a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Person</value>
      <webElementGuid>ba508f78-5f65-4157-8809-3277f364835b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Configuration']/div/div/div/table/tbody/tr[12]/td/div</value>
      <webElementGuid>5152fa56-2aae-4c6e-b8d8-3ff89c2c76b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scottish Criminal Justice'])[1]/following::div[1]</value>
      <webElementGuid>d62677e2-67b2-4d70-b948-c4c056b1f88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sanction'])[1]/following::div[1]</value>
      <webElementGuid>ecce3472-7efd-4f9c-ae2e-50048a82df06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[11]/preceding::div[2]</value>
      <webElementGuid>c7e5fecd-92fd-45b1-9e52-23ecddd3a067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div</value>
      <webElementGuid>81d38763-11b3-4daf-a0ad-e0192f0883cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
