<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subject</name>
   <tag></tag>
   <elementGuidId>2f1a47a6-711b-483a-86f3-23fff766327b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Configuration']/div/div/div/table/tbody/tr[14]/td/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>742d4738-ed05-43f3-86c0-28e8d045b2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>b4482e01-45ba-44cd-a443-b26c1968c390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subject</value>
      <webElementGuid>737771f7-0aa6-4b8d-84b5-689530a09e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Configuration']/div/div/div/table/tbody/tr[14]/td/div</value>
      <webElementGuid>32de70f6-dee0-437b-9fe0-6be3d92aa68e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serving Police Officer'])[2]/following::div[1]</value>
      <webElementGuid>ab092631-f9d9-45ee-bd83-382bcdb62e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviewer'])[1]/following::div[1]</value>
      <webElementGuid>e280ea95-818b-4b1a-973a-3d156e0e85fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bettor'])[2]/preceding::div[2]</value>
      <webElementGuid>7640fb10-4b11-47ee-a940-f4b62991c43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subject']/parent::*</value>
      <webElementGuid>96823c5b-75b8-4190-9483-51f14780b7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td/div</value>
      <webElementGuid>f4b86c2d-d36c-4fa1-8968-f1c2ed69f97e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
