<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DocumentName</name>
   <tag></tag>
   <elementGuidId>f1d2c9fb-5548-472a-82a0-19ef1dc327bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DocumentName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DocumentName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df988bf-74e3-47f9-bc0e-f570154923f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>71e989f5-3fe6-4746-8a2f-91ce7b58d85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.DocumentName</value>
      <webElementGuid>61b768f4-bbb9-49a9-8155-8f8e64bc46f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b259861f-dbcd-4cd3-8185-8cddf601dcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Document Name field is required.</value>
      <webElementGuid>534f3855-c06e-4609-bd64-e4bc1d83734f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DocumentName</value>
      <webElementGuid>2fd0b4d6-882d-4c9c-bc32-d37604f3e59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DocumentName</value>
      <webElementGuid>5507cebc-3047-4157-a28d-6ef9923a6f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Document Name</value>
      <webElementGuid>5621beae-3035-40f9-8ceb-c66e98f69fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb8635e3-48e6-4158-9948-784cc61fdea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DocumentName&quot;)</value>
      <webElementGuid>61911ad0-6acd-4ce4-bb5d-92d67bb414a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DocumentName']</value>
      <webElementGuid>a8b8e074-dc38-4977-9f19-366a84ad7a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-2']/form/fieldset/ul/li[4]/div[2]/input</value>
      <webElementGuid>e1e1c10a-2376-4391-bd24-b1f0d91d8a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/input</value>
      <webElementGuid>96582786-8b80-4c67-80cf-db0249ebd7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DocumentName' and @name = 'DocumentName' and @title = 'Document Name' and @type = 'text']</value>
      <webElementGuid>3856e6c5-f42f-4f85-af65-1dc20cf0d4d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
