<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TBC_1</name>
   <tag></tag>
   <elementGuidId>cbbda254-5a14-4b28-8ea2-f74979e60e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'TBC' or . = 'TBC')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='resultsBody']/tr/td[7]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.unfulfilled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8e02de1f-fd1f-4c8b-893a-88112cc6ef24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $parents[2].format(result[field.Name], field), css: {unfulfilled: !$parents[2].isCriteriaFulfilledFlat(result) }</value>
      <webElementGuid>69a9b5bd-a092-4257-be31-a12ee4eb3a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unfulfilled</value>
      <webElementGuid>c2bfc3d9-47f5-4999-9f12-fac7567ee78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TBC</value>
      <webElementGuid>ab87ea56-14e7-4064-ba88-530ccab99cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsBody&quot;)/tr[1]/td[7]/span[@class=&quot;unfulfilled&quot;]</value>
      <webElementGuid>e5e79e33-db4a-432a-ad0a-ff76a7bb0f58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td[7]/span</value>
      <webElementGuid>d8319861-9d70-4631-ad1f-0887fbfa6107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash found -21133154'])[4]/following::span[1]</value>
      <webElementGuid>845ca3bb-1a5b-4fd6-8bc3-fc186765bf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash found -21133154'])[3]/following::span[2]</value>
      <webElementGuid>9f049993-0e9e-45a9-a2c6-fff4763327cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M00018'])[1]/preceding::span[1]</value>
      <webElementGuid>24cc617b-ff0d-43fb-a9ae-5be0112bf84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash found -20165955'])[1]/preceding::span[1]</value>
      <webElementGuid>193cde7a-22bb-423f-b3fc-0dd334dd11a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TBC']/parent::*</value>
      <webElementGuid>824f8129-81f7-4df7-8a96-85b033e765be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/span</value>
      <webElementGuid>f2e6c24b-f1b5-4af2-8064-a580331637c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
