<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title(Assessment Pop-Up)</name>
   <tag></tag>
   <elementGuidId>d4441597-9c82-46c1-8c9e-e73390ec4f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Title_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a99d705a-1f17-4252-93ef-f33cd394d254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title_summary</value>
      <webElementGuid>84057e46-e934-44e6-a1f1-77fd89aeac12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>1a1b8481-da6e-4de7-9d47-729bee1f0759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>3178a426-fb6d-4c8a-87c0-fc5e8bd3ca93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43934839-cd74-4e5f-8ab6-158858d68322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title_summary&quot;)</value>
      <webElementGuid>015e6c40-31b7-481d-8758-f0c60f736c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Title_summary']</value>
      <webElementGuid>2971e7b1-b8d7-4b80-b720-19954c4a9af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[3]/label/span[2]/input</value>
      <webElementGuid>73810b29-222f-422f-b259-6251bff27ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/span[2]/input</value>
      <webElementGuid>df2d5541-ae7f-4283-8a96-db4e60c2e9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Title_summary' and @name = 'Title' and @title = 'Title' and @type = 'text']</value>
      <webElementGuid>1947eecd-bac5-4e8d-a327-331820b3345b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
