<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Case Record_CA00001</name>
   <tag></tag>
   <elementGuidId>db325f5d-9b3d-461f-af91-bb3cac874149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='resultsBody']/tr/td[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19209a4e-063b-4d96-a04e-4ac9f8a92145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Case/Details/60/31</value>
      <webElementGuid>c97eda54-88a1-460e-93d4-79e67e178c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: result.invNo || '...', attr: { href: $parents[1].detailsUrl + '/' + 60 + '/' + result.Id }, click: function (m, e) { e.stopPropagation(); return true; }</value>
      <webElementGuid>d561f137-59e8-4c00-9b08-3b6558b84aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CA00001</value>
      <webElementGuid>baa9b23e-f063-49d6-aca4-17bd739529e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsBody&quot;)/tr[1]/td[3]/a[1]</value>
      <webElementGuid>8cfdb71f-2d45-4b0a-b4e3-0f8f62773f9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td[3]/a</value>
      <webElementGuid>0bc7b4f9-9eed-4ce9-a0be-fbe5ee5910eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CA00001')]</value>
      <webElementGuid>9043b23e-28b2-4b49-91d5-a26919c597e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[1]</value>
      <webElementGuid>d7d419d4-a1a1-4f90-873b-94fd56edf63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created outside this Investigation. Restrictions apply from your current location.'])[1]/following::a[7]</value>
      <webElementGuid>750d14df-90c6-4d32-80e2-f4c6967bbee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::a[1]</value>
      <webElementGuid>d4a28666-942e-4949-a9d7-baa1587bffe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QA2Test'])[2]/preceding::a[1]</value>
      <webElementGuid>075fdd0c-d26a-4535-b48e-81095c5938f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CA00001']/parent::*</value>
      <webElementGuid>b80aee81-ef5d-4fa2-be6c-b56edf7193e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Case/Details/60/31')]</value>
      <webElementGuid>72faa298-453f-49c5-ab78-2d0bc4df8468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>624eed62-4d1d-42db-b690-40203c8ee084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
