<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Sync_Case</name>
   <tag></tag>
   <elementGuidId>db59f5ea-d02c-483f-a750-148a8f356ee2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sync']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sync</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'sync']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd674f80-bfed-48ef-af44-25ec60c8001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a8e18188-d78f-46bb-ad68-743c8d843ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sync</value>
      <webElementGuid>ab1f2754-72eb-43f8-81e3-b6b4f862975f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sync</value>
      <webElementGuid>e436a07f-be59-4fd1-a7e7-5145c7af7f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>visible: model.ContainerId(), event: {click: function()
                                {
                                    clue.syncCase($data, $data.caseClassification, true);
                                }}</value>
      <webElementGuid>520fb03b-55ce-454a-8e70-19bb5c476667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sync&quot;)</value>
      <webElementGuid>3290e174-6cae-4c95-81b7-a2f0329836a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sync']</value>
      <webElementGuid>47e3a4d9-656a-4233-87d0-3e8c782db256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span[4]/input</value>
      <webElementGuid>0944da91-c5f9-4310-a042-ac498b10e24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/input</value>
      <webElementGuid>1981b647-035b-4ad8-b86c-a9803c7f0107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'sync']</value>
      <webElementGuid>4bbf5e51-ad95-439e-a77b-da7023d69f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
