<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Move_To_position</name>
   <tag></tag>
   <elementGuidId>54782e7f-cdaa-4b2f-b5c2-92ac27195073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#position-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='position-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>314be6df-1da9-439e-8a56-2d272bd91f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>position-id</value>
      <webElementGuid>ab5aa9bd-9130-421d-aed3-00d593f296fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>341fea25-b047-4755-8159-e718f3d3b6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>position-name</value>
      <webElementGuid>aa24332f-4f2e-44ae-a8cb-038fd5e6e8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full border rounded-md border-gray-300 py-2 pl-2 focus:ring-transparent focus:outline-none focus-visible:ring-sky-500 text-sm disabled:bg-gray-50 invalid:border-red-500 invalid:bg-red-50</value>
      <webElementGuid>1879cc38-1891-401f-b028-92332dfc22bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a4fcd48-fb60-4272-adae-9473cc4a8c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>61</value>
      <webElementGuid>1c4484fd-2964-49de-90ec-bb8596f78308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;position-id&quot;)</value>
      <webElementGuid>8586f573-55f5-457f-b5f2-02530b7608bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='position-id']</value>
      <webElementGuid>fa6f1aa3-dc6c-4b85-ba26-ab076664caf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-position-form']/form/input</value>
      <webElementGuid>acccdaf4-f811-4558-860e-d61415396be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/input</value>
      <webElementGuid>2e6d559e-da90-491a-8ebc-87b2d82f459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'position-id' and @type = 'number' and @name = 'position-name']</value>
      <webElementGuid>535ffd01-1d5d-4c85-970e-db6ab7c0f0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
