<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Checkbox-4</name>
   <tag></tag>
   <elementGuidId>da4640ae-af7a-4510-ac38-8dc5c6ab8bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cb-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98efe4cb-75f1-45e2-951f-c7b9ebcfd347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-3</value>
      <webElementGuid>f357ee1b-3d60-44c1-839c-a2a9e1cf6421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>06bd77d4-a937-461b-95f4-af015bcf2f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectRow(event,380)</value>
      <webElementGuid>c1fc0adc-1e16-4713-8c29-21a96c3d7f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>af37c3bb-a2f5-47b1-8ba0-afa88d31f88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute left-4 top-1/2 -mt-2 sm:left-6 h-4 w-4 rounded border-gray-300 text-sky-600 focus:ring-sky-500 focus:outline-none focus-visible:ring-sky-500 focus-visible:border-sky-500 disabled:bg-gray-300 disabled:cursor-not-allowed</value>
      <webElementGuid>c3b29764-eec0-457b-a4af-87410af0df97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-3&quot;)</value>
      <webElementGuid>323edede-aa18-440c-b130-7b803b4c0e29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-3']</value>
      <webElementGuid>5f73e7b1-06f8-4dd1-9f1e-7fab343fd210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr[4]/td/label/input</value>
      <webElementGuid>ecfb5340-4304-41c8-b17c-3d7564d6e8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/label/input</value>
      <webElementGuid>16084bd5-8559-44cb-ab42-993d6126a413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb-3' and @type = 'checkbox' and @title = 'checkbox']</value>
      <webElementGuid>0f0a8011-b5a7-40b5-a651-282873cd993d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
