<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContainsOperator(CaseClas.)</name>
   <tag></tag>
   <elementGuidId>231ae2ae-241a-476b-82fb-e1f4fdc4b66e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='advOptFilterOperator0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advOptFilterOperator0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8edc4c2e-1f75-40ca-8010-27dd7f0aedc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box edit</value>
      <webElementGuid>f83b90f7-a7f9-4937-afd0-3988fd2f44c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advanced Options Filter Operator</value>
      <webElementGuid>1bb0fc2a-b5bf-4a7b-9e92-e96e5a0c3226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: 'advOptFilterOperator' + $index()}, options: $parent.operators()[$parent.components[$parent.componentNames.indexOf($data.component())].FilterFields[$data.fields.indexOf($data.field())].FieldType], value: $data.operator, event: {change: function(){$parent.isDirty(true);$parent.isSearched(false); if ($data.operator() == $parent.operatorsEnum.isEmpty || $data.operator() == $parent.operatorsEnum.isNotEmpty){$parent.clearValue($data);} if ($parent.isLookup($data) &amp;&amp; ($data.operator() == $parent.operatorsEnum.equals || $data.operator() == $parent.operatorsEnum.notEquals)){$data.value('');} return true; } }</value>
      <webElementGuid>5c5606e9-d462-4bca-806c-3953aeb22c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptFilterOperator0</value>
      <webElementGuid>934ccf45-5d6a-4114-bb07-0bd5d22d8b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ContainsDoes not contain</value>
      <webElementGuid>30f7a6d1-794d-4e4f-be9f-6f6769916286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptFilterOperator0&quot;)</value>
      <webElementGuid>754cd48c-68c7-4a69-992b-5098d1c0ea92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='advOptFilterOperator0']</value>
      <webElementGuid>0dd0fa5c-821f-47aa-a5de-438c1d0c35fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterDiv']/div/div/table/tbody/tr/td[4]/select</value>
      <webElementGuid>fc5f054e-61d8-4b91-9eda-36959eeea14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::select[3]</value>
      <webElementGuid>adf4554f-65f6-4208-919f-7bf23f5aae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/following::select[3]</value>
      <webElementGuid>634a11b1-b5c2-4493-8ffd-aaa5b0153f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/select</value>
      <webElementGuid>667cacef-76a1-4d17-a29c-e61899c8655b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'advOptFilterOperator0']</value>
      <webElementGuid>9acbb0bb-0eb4-4bdf-8115-397135ed8263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
