<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save as a new view(CaseClas.)</name>
   <tag></tag>
   <elementGuidId>c6178c91-6d45-4f39-941c-6166bafa9f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@class = 'button' and @type = 'button' and @title = 'Save these changes as a new view' and @data-bind = 'click: saveAs, visible: !(selectedView().Id > 0 &amp;&amp; selectedView().UserId > 0) &amp;&amp; (isDirty() || filter.isDirty())' and (text() = 'Save these changes as a new view' or . = 'Save these changes as a new view')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>820f6f10-fe84-4484-9ee8-dd4538e27ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c3beeb6-2e62-48ac-85a9-08bf621ea77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b6c806a8-eb08-4acf-a812-55dbbb47abd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save these changes as a new view</value>
      <webElementGuid>8fcf6bd6-6795-4c26-ba92-94c5b698f29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: saveAs, visible: !(selectedView().Id > 0 &amp;&amp; selectedView().UserId > 0) &amp;&amp; (isDirty() || filter.isDirty())</value>
      <webElementGuid>ad93310b-8dbc-4089-aa5b-eb6fc98c8fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save these changes as a new view</value>
      <webElementGuid>57d521cb-693a-4952-b1bd-d809461138cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filterDiv&quot;)/p[@class=&quot;right&quot;]/button[@class=&quot;button&quot;]</value>
      <webElementGuid>e62303f9-cc9d-4a8d-a712-2726a7d960ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>30971a21-a713-4f1c-8963-3e12d35213df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterDiv']/p/button[3]</value>
      <webElementGuid>4dd36a3a-369d-4cd4-a8a0-560960e2626e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As'])[1]/following::button[1]</value>
      <webElementGuid>b3234c72-9411-4fca-8f07-08c84f9d39a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[2]</value>
      <webElementGuid>cf8cfd0e-7515-4a3b-bd06-a60255ae3d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::button[1]</value>
      <webElementGuid>69c60f69-dfb6-4e20-af84-c22ec91782cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::button[2]</value>
      <webElementGuid>c37e05f1-1004-4e37-85e8-7ec1cb278a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save these changes as a new view']/parent::*</value>
      <webElementGuid>1c19992a-a8ad-44ea-bf25-1fcfef4c3ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>f57d9db4-b3bb-49d2-b906-95b6d5b8001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Save these changes as a new view']</value>
      <webElementGuid>3822a770-6446-4ac6-ba69-fdde0f8979c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
