<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FilterField(CaseClas.)</name>
   <tag></tag>
   <elementGuidId>e22b062f-b3b1-4eb3-a35a-5168c02494f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='advOptFilterField0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advOptFilterField0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b0fcbdb-d986-41b3-9745-9a4329eb186a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box edit</value>
      <webElementGuid>4d51899a-4314-4be7-ba2a-e8af1aba55b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advanced Options Filter By Field</value>
      <webElementGuid>bf0d2df2-0729-4c67-b439-642dccd41ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: 'advOptFilterField' + $index()}, options: $data.fields, value: $data.field, event: {change: function() {$parent.clearValue($data); if($parent.isBoolean($data)){$data.valueLookup(true);} $data.operator($parent.operators()[$parent.components[$parent.componentNames.indexOf($data.component())].FilterFields[$data.fields.indexOf($data.field())].FieldType][0]); return true; } }</value>
      <webElementGuid>c2220bb4-e274-4f97-aaa3-6249b18a223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptFilterField0</value>
      <webElementGuid>88644ded-78da-47cd-99d3-5a2096c9c8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[Any field]Browser Event HandlersClassificationConfirm WorkflowContainer IdDate Last UpdatedDescription and RelevanceDisabled FieldsDocument NameDocument TypeDynamic ControlsDynamic Field BehaviourHintsIdKey Witness?Last Updated ByNo Direct ContactNo.Preview UrlPrevious ConvictionsPrimary Alternate ContactPrimary ContactPrimary Contact IdReason for SensitivityReasons Why Assists/UnderminesRecord StateRecord VersionSecondary Alternate ContactSecondary ContactSecondary Contact IdSelected WorkflowTypeType of Witness</value>
      <webElementGuid>f740fce5-a4c1-4e8e-a29c-3e5112d219e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptFilterField0&quot;)</value>
      <webElementGuid>1a5018ce-149e-4dd5-8a43-6d6125aa90fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='advOptFilterField0']</value>
      <webElementGuid>0fd012de-8873-4917-8ecd-2969a32eb3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='filterDiv']/div/div/table/tbody/tr/td[3]/select</value>
      <webElementGuid>ed347606-9d0e-4173-9598-b9205c388843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::select[2]</value>
      <webElementGuid>b747ae81-4347-4715-a3e4-91c1490d2b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/following::select[2]</value>
      <webElementGuid>ff050be2-631b-45c5-9927-f306e2bf8d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>64e63c1c-2098-46cb-83da-66119f46225d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'advOptFilterField0']</value>
      <webElementGuid>0ed600d3-c54f-40df-8e1d-fe9a725b6a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
