<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>URNLink(Inv)</name>
   <tag></tag>
   <elementGuidId>2aeeb0d2-1ddf-4544-81e0-7ebd3857936a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.clickable > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='resultsBody']/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;resultsBody&quot;)/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1277d2ee-8227-4a0b-9a6a-11467d4a3b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/jersey/Investigation/Details/30404/30404</value>
      <webElementGuid>62fa697e-a051-42c7-a4fe-af49deb7a2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $parents[2].format(result[field.Name], field) || '...', attr: { href: $parents[2].detailsUrl + '/' + result.Id + '/' + result.Id }, click: function (m, e) { $parents[2].setRowHighlightDetails(result); e.stopPropagation(); return true; }</value>
      <webElementGuid>00fb19d6-52f4-4ec9-bfdf-6d53d78867db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>182</value>
      <webElementGuid>b52e1405-2810-495d-937e-aaeeb29134a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsBody&quot;)/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      <webElementGuid>c5efb9f1-d5f4-4373-87e0-913a42b41b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td[2]/a</value>
      <webElementGuid>00b36738-5745-49e6-9978-7104e3112da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'182')]</value>
      <webElementGuid>f06007c6-dff4-43dc-b439-0c27f7718788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created in an Investigation. Restrictions apply from your current location.'])[1]/following::a[5]</value>
      <webElementGuid>3fc7a8e4-eab7-4c3a-a82d-23c2227e7dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dark Skies'])[1]/preceding::a[1]</value>
      <webElementGuid>39b9a2bb-3303-4da7-a3b8-ed8688d638dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0 selected records)'])[1]/preceding::a[1]</value>
      <webElementGuid>b911ea17-aa24-434e-9d85-e075e8786453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='182']/parent::*</value>
      <webElementGuid>20b12be2-194f-4591-99b2-3d23e8170ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/jersey/Investigation/Details/30404/30404')]</value>
      <webElementGuid>e89e23d4-592e-407d-bdd3-d858a08cb799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>120658fb-3fae-45fd-aecd-216cc5f51ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
