<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_print</name>
   <tag></tag>
   <elementGuidId>4fb83028-562c-474a-b529-422b98a2b439</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#print</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='print']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c83e0cc-77cc-4da7-a36a-f58929ca0c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>10def4c3-c399-4100-b281-ac3e6ec6e959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>print</value>
      <webElementGuid>6e45c36a-5ea3-4720-b761-0e3d8a2861f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Print</value>
      <webElementGuid>4eb3fbdd-0af6-47c6-a6d1-3217fc93254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: function() {printRecord(($('#AvailablePrintLayoutSelector option:selected').text().length > 0) ? $('#AvailablePrintLayoutSelector option:selected').text() : settings.AvailablePrintLayouts[0].Name, null, null, null, null, printOutputType(),settings.AvailablePrintLayouts[$('#AvailablePrintLayoutSelector option:selected').index()].Type !== null ? true: false,settings.AvailablePrintLayouts[$('#AvailablePrintLayoutSelector option:selected').index()], false, {'showFilePreview':true,'context':8}  )}, css: { hidden: !availablePrintLayouts().length}</value>
      <webElementGuid>e1a0f262-c8bd-4fb2-95c2-9a79819f5a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;print&quot;)</value>
      <webElementGuid>ed67429e-ceb2-4f2d-a865-758bbb729948</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='print']</value>
      <webElementGuid>39f6d7ec-9755-4b30-b691-515d00a4be83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span/input[3]</value>
      <webElementGuid>e697e65b-4892-4f72-b451-97a5f0882cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>d92802e5-4d9e-417e-befa-4150443a1df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'print']</value>
      <webElementGuid>736aca1d-fa22-42db-9291-4f3d6942872d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
