<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit Button(Record)</name>
   <tag></tag>
   <elementGuidId>c60f31c5-7d5f-4cff-9520-cd2572db192e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form1']/ul/li/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09662919-31da-447d-bdc5-ffb7afbdbcc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bf94bd1-08d2-4994-84f3-c25dd0e7b140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>1b36dae6-40a9-47d3-a540-9cddad878e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>7ecfc76b-59d8-4a81-8eb7-b5828adf9e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: editRecord, css: { hidden: !settings.EditUrl }</value>
      <webElementGuid>710e3bca-9baa-4e0b-ab9f-e47c50ee8171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit&quot;)</value>
      <webElementGuid>183a3396-5b18-47eb-a58d-ae32eb8d52b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='edit']</value>
      <webElementGuid>d253f045-bb2c-4740-b7ee-b21d79feb76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span/input</value>
      <webElementGuid>ac97dd5b-148d-467f-8a69-1128ae3750c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span/input</value>
      <webElementGuid>986e9922-6c8b-4c7b-9e28-230e46da5ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'edit']</value>
      <webElementGuid>b62e2c1b-7a0b-446c-807e-882c1e70a788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
