<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OK(Print Pop-Up)</name>
   <tag></tag>
   <elementGuidId>37a3e007-f85d-444d-bbb4-902f5ed18bd1</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Clue - Address Details/input_Ok.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ok']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Clue - Address Details/input_Ok.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ace0c50-69b5-48bd-8b7d-796bbded64b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>e5f10414-42ed-488f-8a39-4bbef8830064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f74f40ac-9716-4e19-ab29-1f2acaba1b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>0f70e5b8-43e6-47f4-bd29-bdffbd428582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ok&quot;)</value>
      <webElementGuid>f4ceeb16-de45-46ce-906f-60c4322eceab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ok']</value>
      <webElementGuid>b732f8d6-febc-4af8-ba64-a645092800b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/form/p/input</value>
      <webElementGuid>cd2d851a-a0cb-4c6c-9a7f-98c2c7dc459b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>aee0ad5a-9dc8-44d0-ad2c-6ad4a12501b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ok' and @type = 'button']</value>
      <webElementGuid>ceae80b8-24a8-43b3-9e87-ce36394d236e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
