<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MainImagePresent</name>
   <tag></tag>
   <elementGuidId>b14d1f89-6b3c-4a6a-a26f-ec26d9451e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.personThumbnail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form1']/div/fieldset/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>efc56ed9-6673-40fd-afd4-f0bcfbd3dc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>personThumbnail</value>
      <webElementGuid>76366163-f1c7-4a6e-a5dc-b3fb4d86c984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { src: model.ThumbnailUrl() + '?maxHeight=210&amp;maxWidth=260', height: model.ThumbnailHeight, width: model.ThumbnailWidth }</value>
      <webElementGuid>3f8d8c11-99b1-45a4-b958-a1dee828e865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/league/api/PersonApi/ViewThumbnail/40376?maxHeight=210&amp;maxWidth=260</value>
      <webElementGuid>009bc494-f59c-40f7-b1a6-592d91a12942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[1]/fieldset[1]/img[@class=&quot;personThumbnail&quot;]</value>
      <webElementGuid>2079090d-e210-4165-9fe2-da04436d43e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset/img</value>
      <webElementGuid>018e4884-44c2-4d11-bc14-c39b86909fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/img</value>
      <webElementGuid>9ec03ee0-9304-4b78-aec1-c1d02774ab60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
