<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveReportHistory Check-Box</name>
   <tag></tag>
   <elementGuidId>93f1cb7d-5b3d-4519-9e5f-4bad261e63d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SaveReportHistory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SaveReportHistory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0f4383c-3e4f-4a59-a529-c7b94d16fe34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3843d5b-836d-4f4c-9123-bbb27b10da02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Save a copy of this report to history</value>
      <webElementGuid>f1e83bf8-6769-4a2a-8432-807e3f8e00a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SaveReportHistory</value>
      <webElementGuid>e0a3697c-bfc4-497c-ab74-8c0e35ff17ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: saveToReportHistory</value>
      <webElementGuid>348dbbc6-6519-4930-8b5c-9c47539846aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SaveReportHistory&quot;)</value>
      <webElementGuid>6a026e16-a310-4bed-8bef-ad657f8d262d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SaveReportHistory']</value>
      <webElementGuid>4c6269d7-dfc0-426a-ac6c-5466ed1f3e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/form/input</value>
      <webElementGuid>76010818-01a5-4f1c-a500-b08a653ef1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>9451aded-1a55-42bb-ba96-28e2264b8e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'SaveReportHistory']</value>
      <webElementGuid>0cf12d11-c98b-4681-9fdc-1314e5ce3cc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
