<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>URN SearchResults</name>
   <tag></tag>
   <elementGuidId>dc27dcdc-8f9a-4d76-ace6-f4838d98223a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='resultsBody']/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.clickable > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2dadf194-4c3c-4ab1-abf7-e083a1db49fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $parents[2].format(result[field.Name], field) || '...', attr: { href: $parents[2].detailsUrl + '/' + 0 + '/' + result.Id }, click: function (m, e) { $parents[2].setRowHighlightDetails(result); e.stopPropagation(); return true; }</value>
      <webElementGuid>bca40d4a-e531-4bd1-b339-3cc96ac9cf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsBody&quot;)/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      <webElementGuid>1fcac0ea-fc28-4115-a3ea-6dc75fe07838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td[3]/a</value>
      <webElementGuid>f13f3db2-a25d-4858-a1ec-a51cdc9a85cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'214')]</value>
      <webElementGuid>5c3972a6-3f6c-4dc5-96fc-b0ac48b8a457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[18]</value>
      <webElementGuid>ee00b4db-8471-4b6a-802b-cbec814d3f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created in an Investigation. Restrictions apply from your current location.'])[1]/following::a[24]</value>
      <webElementGuid>0844ea79-d292-4f71-a067-0045689d0dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BP1 3JY'])[1]/preceding::a[1]</value>
      <webElementGuid>695a5805-4677-4b12-8b60-0fa5959ffd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0 selected records)'])[1]/preceding::a[2]</value>
      <webElementGuid>b6725441-cf18-4910-9884-73c0553948c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='214']/parent::*</value>
      <webElementGuid>3320abce-88b3-4e4a-bf56-d612fdc8455f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/league/Address/Details/0/90754')]</value>
      <webElementGuid>8befee9a-32e8-4852-9703-ee97feb4b0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>639ad443-b01a-4e50-839a-5e804b7d1b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
