<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__previous</name>
   <tag></tag>
   <elementGuidId>0163f33f-1c59-4320-88e6-fe8a3e7572a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#previous</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='previous']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02ddfa76-4aea-41f7-ac7c-dd1068453f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59c54f75-3ba5-4d40-95f6-4b35b22a5737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>previous</value>
      <webElementGuid>f5c73745-8b01-4b8d-804b-036157215c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Previous attachment</value>
      <webElementGuid>68af7c50-9ef5-4048-9cf3-729a72d239dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 relative inline-flex items-center px-2 py-1 border border-grey-400 rounded-full text-gray-800 focus:outline-none</value>
      <webElementGuid>895b202a-c102-4f07-bf8c-4e04f9c55e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;previous&quot;)</value>
      <webElementGuid>6dca60c9-d008-4713-8b9c-1c4f66a77e38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='previous']</value>
      <webElementGuid>fff9d4d2-76a9-46bb-97d0-11453b6ed12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navigation']/button</value>
      <webElementGuid>8dc75e7e-8d30-4ca7-96dd-3a4752d5bd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properties'])[1]/following::button[1]</value>
      <webElementGuid>14d136d0-252a-4b2c-abf1-38d27a6c6eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button</value>
      <webElementGuid>65b5df44-fec3-4475-8db5-8cee49619344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'previous']</value>
      <webElementGuid>09803f1c-a3f5-4902-b379-4cdca0765e12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
