<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RecordPerm Save</name>
   <tag></tag>
   <elementGuidId>da289b3a-0738-4efd-9508-b9c8425b9e31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;save&quot;)[count(. | //input[@id = 'save' and @type = 'submit']) = count(//input[@id = 'save' and @type = 'submit'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3be117f2-9c93-4ea0-bf24-420fc705b5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>a0bfb6ea-e995-4428-bdb0-3d8176f5da12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2ec5f518-0fc6-43cd-b5fd-fbc82c97a308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>56772eb9-b8f1-4804-899a-e270ecc10597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save&quot;)</value>
      <webElementGuid>373e3387-82c2-4943-b451-d4369628b9c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save']</value>
      <webElementGuid>02ea520d-d277-49e6-8c6a-8c17f655fe77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='recordPermissionsEditor']/p/input</value>
      <webElementGuid>7d116961-898a-43cc-aa15-6c0916357f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>f7e2617f-7aa1-4e87-a049-9b9cd1b46f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'save' and @type = 'submit']</value>
      <webElementGuid>0e421e79-e1e0-4c2b-b27d-8ef555ed2dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
