<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_personSave</name>
   <tag></tag>
   <elementGuidId>52e865ed-c29f-410e-a1ac-1b032b1a8f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;personSave&quot;)[count(. | //*[@id = 'personSave' and @value = 'Save']) = count(//*[@id = 'personSave' and @value = 'Save'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personSave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f2b0886-7525-4806-b59b-9a1a624861d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6f00ff7c-4c27-4efe-8044-a52939a4ec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personSave</value>
      <webElementGuid>7414b2bf-cc0b-4fc4-a458-b5fd7adeba35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ecb6388f-283c-4932-b391-9036623591af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personSave&quot;)</value>
      <webElementGuid>5f8ff71f-41fd-421b-ba5b-32f1d8a19011</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personSave']</value>
      <webElementGuid>fef8fb2c-5a68-4cc7-b012-2033d41073bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-7']/div/form/p[3]/input</value>
      <webElementGuid>ca86faec-6fc7-4fb0-9de4-0c4b266860c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>1ce302a6-116f-4239-ad2c-1d9b69981a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'personSave']</value>
      <webElementGuid>6c0c46fb-be34-4f26-b1f0-f1d5894d98b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
