<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname</name>
   <tag></tag>
   <elementGuidId>ede05839-ab86-470d-ade5-5ad77deecb79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Surname_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Surname_summary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Surname_summary&quot;)[count(. | //input[@id = 'Surname_summary' and @name = 'Surname' and @title = 'Surname' and @type = 'text']) = count(//input[@id = 'Surname_summary' and @name = 'Surname' and @title = 'Surname' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>716b2d7e-4eb6-4b3b-ac9b-1e6f581b36c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname_summary</value>
      <webElementGuid>673ffcd6-767f-452a-b30a-177042a2af9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>cec0e048-cbab-4314-b65f-51053a9218b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>152476e7-c380-43de-bd9a-968fde02bc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>338a7b47-8068-44fd-ad00-f1e75f1a0bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname_summary&quot;)</value>
      <webElementGuid>7caea572-328a-436b-86d3-ea0f5a2eac0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Surname_summary']</value>
      <webElementGuid>0b3585f7-ecd3-4a25-85dd-60a02dddf4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-7']/div/form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>8c03daf8-e07d-4455-8e16-d846eeb3be25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>3226b1e4-18d7-4881-a0de-c4ab6ee1d805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname_summary' and @name = 'Surname' and @title = 'Surname' and @type = 'text']</value>
      <webElementGuid>3a226dd7-da8b-4820-9d62-594aba78d61d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
