<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forename</name>
   <tag></tag>
   <elementGuidId>553e9630-79a4-4ab4-ba62-f92f7724fbfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Forename_summary&quot;)[count(. | //input[@id = 'Forename_summary' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text']) = count(//input[@id = 'Forename_summary' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Forename_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Forename_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd63de8b-277c-4c9b-b7d5-55dcf1529f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Forename_summary</value>
      <webElementGuid>fd85c6cc-a120-4dd8-9584-c6a32e71c1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>2d67eda4-b409-4178-a72c-d790ca112380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Forename(s)</value>
      <webElementGuid>efe01b07-f232-4ee3-82e0-c27e167952bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d64a6da-a790-41ed-8108-bc727cb12f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Forename_summary&quot;)</value>
      <webElementGuid>6700b3d6-6570-456d-aff2-85b61ca61dad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Forename_summary']</value>
      <webElementGuid>58f16d71-c2d3-499b-8799-d0008d2b2f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-7']/div/form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>9d801825-391f-4a61-9355-ec7615169d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div[2]/input</value>
      <webElementGuid>cb240083-8061-4d5e-bce6-c3008434fc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Forename_summary' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text']</value>
      <webElementGuid>dd3de975-b607-40fb-a55b-e4641218e81f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
