<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>0eb48eaf-6201-4b8e-b702-e12eb64fb25c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#RecordType_summary</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RecordType_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RecordType_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f56a91a-8fda-436b-97f1-47add405ad76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecordType_summary</value>
      <webElementGuid>6a6040ac-51e4-4c25-bc6d-18b130606011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RecordType</value>
      <webElementGuid>58b1f6e9-182b-40bb-8b06-2b4f91be66c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>5e11ce40-d40d-4df7-a633-2dfde6c7f52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecordType_summary&quot;)</value>
      <webElementGuid>212ad432-57e7-45f8-885a-91d33a841f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#RecordType_summary</value>
      <webElementGuid>636f0246-cd4e-401b-ba0d-cc6e7ba98a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RecordType_summary']</value>
      <webElementGuid>6339f127-2899-44a7-a3c4-5ca86435effa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
