<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Title</name>
   <tag></tag>
   <elementGuidId>33a04f4a-44cf-42d4-a1cf-89eadfb76706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Title_summary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Title_summary&quot;)[count(. | //select[@id = 'Title_summary' and @name = 'Title' and @title = 'Title']) = count(//select[@id = 'Title_summary' and @name = 'Title' and @title = 'Title'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d64b478-77ad-492a-86d3-838b7e7dec9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title_summary</value>
      <webElementGuid>86fbc306-0b24-4cdf-badd-703bc5305f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>220c3a18-23c9-44b7-adb8-b848159d25a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>d6224165-35f6-4bfc-8c74-bdd5799edd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title_summary&quot;)</value>
      <webElementGuid>2bb5c3ca-b3a7-4bd1-9d53-0fe2721af760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Title_summary']</value>
      <webElementGuid>0a381c19-6f35-4371-8fea-e1afc26512b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-7']/div/form/fieldset/ul/li[5]/div[2]/select</value>
      <webElementGuid>517a3f0b-3eda-4c35-a4aa-6ea7f28fc478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[2]/following::select[1]</value>
      <webElementGuid>4c4e65da-77e4-4c22-a351-bd3006c564b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/preceding::select[1]</value>
      <webElementGuid>6ba3c022-aad1-40ca-9e80-e6402d905ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[5]/div[2]/select</value>
      <webElementGuid>b7ee1f2c-0a13-4591-9c5b-8064083ceae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Title_summary' and @name = 'Title' and @title = 'Title']</value>
      <webElementGuid>6eeb33bc-8934-469e-8112-277ba65c7081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
