<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RetainFor</name>
   <tag></tag>
   <elementGuidId>17f5d1e4-b70c-46b6-b90b-426aa8de2510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RetainPeriod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RetainPeriod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6d8ad900-0bdc-45b3-a27c-6f3b93ca698d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>8732e2f2-41ac-4a51-87f7-e0e90869abef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('385c9875-54f2-4535-9eef-44062a301900', model.RetainPeriod()), value: model.RetainPeriod, event: {change: function () {if (model.RetainPeriod() != null){model.RetainDate(clue.addPeriodToDate(new Date(), model.RetainPeriod(), true));}} }</value>
      <webElementGuid>811d0ba3-01c5-4687-9d4e-47c7d8b7b121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RetainPeriod</value>
      <webElementGuid>637905c2-365f-4c88-8c40-7e290d7d4e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RetainPeriod</value>
      <webElementGuid>0b5c193b-75b8-4627-b53b-2dfaaf0c47e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Retain For</value>
      <webElementGuid>a53c6e46-834c-4520-a6f4-742890eb43a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Year6 Years10 Years100 Years
</value>
      <webElementGuid>5d2e060e-3e09-4271-af70-002212ce58b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RetainPeriod&quot;)</value>
      <webElementGuid>e53e32cd-bef2-48dc-bff4-0f36d45d1385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RetainPeriod']</value>
      <webElementGuid>41162e7d-7501-42b0-945c-b0bc909ffc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset[3]/div[2]/ul/li[7]/div[2]/select</value>
      <webElementGuid>edb29f88-c103-4e64-b9ea-ad73b93541e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retain For'])[1]/following::select[1]</value>
      <webElementGuid>f9581776-d0a9-41bd-83cb-790636fa225a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on'])[2]/preceding::select[1]</value>
      <webElementGuid>d3ab8c0f-1b4c-48a5-8592-97c66853ff01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div[2]/select</value>
      <webElementGuid>c1e40289-722e-4bc3-9d6b-b7ac4e94ccfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RetainPeriod' and @name = 'RetainPeriod' and @title = 'Retain For']</value>
      <webElementGuid>f7a68520-8e65-4bd1-a18c-d3a2a7e82642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
