<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>3e8b6993-0f4b-4c79-9349-9debe92a4c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>278f0edd-58a7-4acf-8f64-11c3b758bd2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>8c01ae51-d422-4cfd-8138-53d227fd5749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.filteredLookup('6a773443-e224-4321-abe2-1deee3a75ef5', model.Type), optionsText: 'Value', optionsValue: 'Value', value: model.Type, event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'023495e8-6529-49d7-9621-822abba2183a', model.SubType, model.Type);}}</value>
      <webElementGuid>b4fdf086-3a45-4bed-a53b-fb6f5aa17cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da2b65e0-6d50-47c1-9630-d88923047d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Type must be a string with a maximum length of 255.</value>
      <webElementGuid>f27b6119-591c-4d4f-9e9a-88f0f689d044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>7539555c-ab30-4672-b645-dcddfe527629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>13f44a10-810f-4905-b7a0-3dcbaeb7550c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>c432c52d-ee55-448b-840b-c3fc303b48fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>ceec5da3-62d2-403a-9386-a8ca4c1d97e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arnold Clarkton
</value>
      <webElementGuid>3790d865-8770-46c0-9742-cac2f376fe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type&quot;)</value>
      <webElementGuid>7f117dc9-0163-446e-9714-e900ae4bb116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Type']</value>
      <webElementGuid>86b2136b-b162-4f47-85ea-d74fc1516ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[3]/div[2]/select</value>
      <webElementGuid>da83b897-8efc-41fe-bdc8-378840401190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>f5ab2336-82b8-4fb1-8650-185d8ddf0fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype'])[1]/preceding::select[1]</value>
      <webElementGuid>6a5c905a-3560-445d-a42a-71b1ae8aa646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>c465a08e-2219-4d28-8cba-f179e75c74bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Type' and @name = 'Type' and @title = 'Type']</value>
      <webElementGuid>45610227-2792-4001-8b2f-27ec29da19d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
