<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ReviewAfter</name>
   <tag></tag>
   <elementGuidId>9a32c5fe-34d8-4d88-bf81-b5cd4e73f0ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReviewPeriod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ReviewPeriod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd2e3bae-8677-4f67-81cf-06629d774026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>9a0d5edf-e6fc-404e-ae2a-f4860ff57100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('a54a367e-aa4b-4644-93a9-e887f54e2b1d', model.ReviewPeriod()), value: model.ReviewPeriod, event: {change: function () {if (model.ReviewPeriod() != null){model.ReviewDate(clue.addPeriodToDate(new Date(), model.ReviewPeriod(), true));}} }</value>
      <webElementGuid>b0c665f4-0a18-4907-97ca-e492ed37c58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReviewPeriod</value>
      <webElementGuid>c9d9d620-eb2a-4a45-ad2a-c2abe395f02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReviewPeriod</value>
      <webElementGuid>ba8e289d-a290-4fad-8737-150aaae6dfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Review After</value>
      <webElementGuid>e3b28779-9e08-4c3a-8b1c-18ad3414a6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Month1 Week1 Year3 Months3 Years5 Years6 MonthsDillanStewartThorley
</value>
      <webElementGuid>6a9280da-8d12-4aa0-9ad6-e61fa8ccf3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReviewPeriod&quot;)</value>
      <webElementGuid>dd57b9ab-069c-4326-8836-bfde62bc2c98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ReviewPeriod']</value>
      <webElementGuid>c367d46e-d6c8-4e1b-b8d2-dd4fa50e76bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[5]/div[2]/select</value>
      <webElementGuid>beb63b2e-a93c-4d26-ae57-c6975cf12651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review After'])[1]/following::select[1]</value>
      <webElementGuid>baac3136-552a-4d62-8eee-c926d9baea7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on'])[1]/preceding::select[1]</value>
      <webElementGuid>3dc75ceb-4203-4671-8461-a14c1475c466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[2]/select</value>
      <webElementGuid>923995d8-0151-4300-bb12-ed66c040e524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ReviewPeriod' and @name = 'ReviewPeriod' and @title = 'Review After']</value>
      <webElementGuid>aa340657-a16f-457a-9594-2aff1dd011e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
