<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FilterField</name>
   <tag></tag>
   <elementGuidId>2724d1c6-7234-4d2e-9048-122e476f5193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;advOptFilterField0&quot;)[count(. | //select[@id = 'advOptFilterField0']) = count(//select[@id = 'advOptFilterField0'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc1487c4-aaaf-404d-8d1f-8b77f2bc7fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptFilterField0</value>
      <webElementGuid>9dc3684e-64db-4596-aaa7-af8c1fdcbde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptFilterField0&quot;)</value>
      <webElementGuid>4c92e3d9-69de-44f4-9fd5-01b9d1b1fa4e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
