<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_preview</name>
   <tag></tag>
   <elementGuidId>d465058f-021f-4708-90be-a8fbe2701756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='preview']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;preview&quot;)[count(. | //input[@type = 'button' and @id = 'preview']) = count(//input[@type = 'button' and @id = 'preview'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60d64a83-9701-4b91-84d5-befd6a7787b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9462cd42-9a5e-4da7-a4e0-6d23e48e39ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview</value>
      <webElementGuid>e84baa2b-0872-4861-b1c4-1ff2d5ff5ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>9e318bac-85ad-4685-90f3-de7e4b01763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { hidden: !settings.EditUrl || !availableSchedulePrintLayouts().length },click: function() {printRecord(($('#AvailableSchedulePrintLayoutSelector option:selected').text().length > 0) ? $('#AvailableSchedulePrintLayoutSelector option:selected').text() : settings.AvailableSchedulePrintLayouts[0].Name, null, null, null, null, null, false, null, false, {'showFilePreview':true,'context':9} )}</value>
      <webElementGuid>f973e768-faf2-4e67-aeab-44b5fd1ef418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview&quot;)</value>
      <webElementGuid>53aad06a-9f66-4a58-a6e1-d60e8acfaeeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='preview']</value>
      <webElementGuid>716d224f-ad59-491b-9c32-e6ccda09ef0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span[5]/input</value>
      <webElementGuid>ba469eed-2b0d-42ca-8cf4-b9ed762e0344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input</value>
      <webElementGuid>9c9fffeb-89f5-4ac0-913f-488bcf9df94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'preview']</value>
      <webElementGuid>66252f85-ab6f-450c-bb1f-8909cae49855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
