<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reasons_Why_AssistsUndermines(Case Classification)</name>
   <tag></tag>
   <elementGuidId>4af01634-9ec0-4408-889d-f8cf5d28db3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reasons</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Reasons']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fa6cc900-78a0-429e-985b-203d6a915f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reasons</value>
      <webElementGuid>906e34bd-f8ec-4cba-9ba3-5c9edd1fc38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reasons</value>
      <webElementGuid>093b7c1e-d875-45b4-97c6-18305badde7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reasons Why Assists/Undermines</value>
      <webElementGuid>ae41be86-2331-41b7-90bc-d0a3b403cdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reasons&quot;)</value>
      <webElementGuid>402088b3-b62a-4da4-bbbf-246db8a104f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Reasons']</value>
      <webElementGuid>a0a682d3-bf37-4bd5-9752-029c0bfadf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-1']/form/fieldset/ul/li[3]/div[2]/textarea</value>
      <webElementGuid>1271d823-9416-4bab-89fa-b1dffdff7a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/textarea</value>
      <webElementGuid>9b7419f4-ac3d-43cc-b1e4-a4b77a8b0e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Reasons' and @name = 'Reasons' and @title = 'Reasons Why Assists/Undermines']</value>
      <webElementGuid>00e659ff-5f39-4970-86e7-9500bf898e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
