<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchBox(Preview Modal)</name>
   <tag></tag>
   <elementGuidId>9e43c25c-4a94-4e4b-be0b-1b7d8b22c8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[4]/div[4]/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SearchPanel__input&quot;][count(. | //*[@placeholder = 'Search document' and @tabindex = '0']) = count(//*[@placeholder = 'Search document' and @tabindex = '0'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SearchPanel__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75e8117d-3b97-4f9c-ae1a-6e5ebb14cb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>575b3b03-e1b5-432c-9015-7470fac41cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search document</value>
      <webElementGuid>331417d1-ffd0-44a1-aa9a-19abb99933db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchPanel__input</value>
      <webElementGuid>ad55acbb-da63-4019-aa69-8aabcda3c833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0f8b2694-7ef2-4941-9976-a3bd0ca891b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SearchPanel__input&quot;]</value>
      <webElementGuid>50638ac4-fb02-4a87-b702-296731e919cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>/html/body/div[1]/div[1]/div[4]/div[4]/div[2]/div[1]/div[1]/input</value>
      <webElementGuid>df15b9bc-d1a7-4cfe-8a23-f9b628ce604f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchPanel__input']</value>
      <webElementGuid>b2014bb0-111c-4263-9b36-cad74a9e92c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[4]/div[4]/div[2]/div/div/input</value>
      <webElementGuid>cff128d6-dbba-4d7b-938e-bcb6504049e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9bed170e-b21f-43d9-98f6-8828c70b9c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'SearchPanel__input']</value>
      <webElementGuid>501f3012-c8f0-4bdc-ba72-eefc22acfced</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
