<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete(view)</name>
   <tag></tag>
   <elementGuidId>f512c91f-0451-49d6-898f-c35664bff10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advOptDelete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advOptDelete</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;advOptDelete&quot;)[count(. | //*[@id = 'advOptDelete' and @title = 'Delete']) = count(//*[@id = 'advOptDelete' and @title = 'Delete'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ac70c3b-11a5-4920-9f73-d950d5eb70a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>34808e71-f7dc-4817-ab35-b2a36a1a0711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptDelete</value>
      <webElementGuid>e4e78dfc-6922-44fd-8f6e-5d9d2e5652a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>185a0913-724f-485b-b4f5-bbf376abdfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>b8f9e277-ea33-4d99-877d-61ef0ffc3ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: deleteView, visible: selectedView().Id > 0 &amp;&amp; selectedView().UserId > 0</value>
      <webElementGuid>802138e9-3cfe-4b0a-afd0-16f11734efdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptDelete&quot;)</value>
      <webElementGuid>eca3d2eb-824a-412d-bd69-097d9a22f7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advOptDelete']</value>
      <webElementGuid>cd26ddbb-9af8-4fd7-a33b-243a3274b50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedOptionsDiv']/p/button[7]</value>
      <webElementGuid>79aea3ff-dede-429f-acdc-dfe1883e1fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save these changes as a new view'])[1]/following::button[1]</value>
      <webElementGuid>6a167e1d-18bd-43e8-8aba-23b2a6a37f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As'])[1]/following::button[2]</value>
      <webElementGuid>f70a5141-da71-47e3-80a2-0cc2326a4b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display in new tab'])[1]/preceding::button[1]</value>
      <webElementGuid>4b3eab2c-8f5c-4d22-9e27-17ca4eeb3e76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/preceding::button[2]</value>
      <webElementGuid>c0f4130b-58c8-45de-8074-722c412910bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]</value>
      <webElementGuid>d91d95d0-42d5-4adb-8cd3-378278238dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advOptDelete' and @type = 'button' and @title = 'Delete']</value>
      <webElementGuid>67fa65a8-63cf-4ee3-aa4e-f5428cd4f313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
