<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save new view btn(View)</name>
   <tag></tag>
   <elementGuidId>b59a41a3-bc82-4a5f-800c-65c35ceafd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advOptSaveNewView']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;advOptSaveNewView&quot;)[count(. | //*[@id = 'advOptSaveNewView' and @type = 'button' and @title = 'Save these changes as a new view']) = count(//*[@id = 'advOptSaveNewView' and @type = 'button' and @title = 'Save these changes as a new view'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advOptSaveNewView</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd95622-50fc-4d09-a6c1-3d280de1eeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cda1867-686c-4607-bb1e-32c6b48d17b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptSaveNewView</value>
      <webElementGuid>11d39a60-ecad-4031-9110-f95bf409292a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d51649f7-6cbe-44bf-962d-5c0b68e4da76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Save these changes as a new view</value>
      <webElementGuid>aceabc0e-0866-4b6a-ac42-fc1d508e23fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: saveAs, visible: !(selectedView().Id > 0 &amp;&amp; selectedView().UserId > 0) &amp;&amp; (isDirty() || filter.isDirty())</value>
      <webElementGuid>0fc5a790-b0cd-41ce-81f3-de1f3558a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save these changes as a new view</value>
      <webElementGuid>2525e505-113c-45b4-8f68-300a031babb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptSaveNewView&quot;)</value>
      <webElementGuid>960645ae-0ef0-43b4-b8f5-9bbf2d2c540a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advOptSaveNewView']</value>
      <webElementGuid>3ded1afc-b474-459f-a44f-7e90e390ac4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedOptionsDiv']/p/button[6]</value>
      <webElementGuid>deddff14-b703-4575-a7e5-c04d13e4d9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save As'])[1]/following::button[1]</value>
      <webElementGuid>731da7a2-ea18-4889-b539-ecedea6ce3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[2]</value>
      <webElementGuid>196a0bb8-20f6-4828-a144-5c3d9a97203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[2]/preceding::button[1]</value>
      <webElementGuid>39641e36-9fe5-4ba6-83d8-835e90c4ac40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display in new tab'])[1]/preceding::button[2]</value>
      <webElementGuid>3679a167-00d4-497a-baba-48332de4d20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save these changes as a new view']/parent::*</value>
      <webElementGuid>530ecf07-9b6c-4fe9-a8fe-066540b81437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>4e94ffa1-1344-4041-b718-a99464312357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advOptSaveNewView' and @type = 'button' and @title = 'Save these changes as a new view']</value>
      <webElementGuid>f5cee6de-de80-4f33-b598-792c1782abcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
