<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show on Dashboard</name>
   <tag></tag>
   <elementGuidId>322d44d4-9a17-4fdc-9733-4c223f10e5a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='advOptShowOnDashboard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#advOptShowOnDashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dda1b50-0d1a-40d3-9f22-007228194866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptShowOnDashboard</value>
      <webElementGuid>868ea1c1-08a6-44fa-a001-9cde5a724ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>819f2eca-e8f1-4fb6-af30-36eb48a20da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: isCrossRegister(), css: { disabled: isCrossRegister() }, checked: !isCrossRegister() &amp;&amp; selectedView().DashboardOrder</value>
      <webElementGuid>83a6e566-fcb2-4bca-b7b7-b1a4e306ff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptShowOnDashboard&quot;)</value>
      <webElementGuid>56e12b38-cd77-4289-8a19-e112d7e14a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='advOptShowOnDashboard']</value>
      <webElementGuid>5a50d25d-3a5e-4c0d-a5b0-301da700e05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='advancedOptionsDiv']/ul[2]/li[3]/label/input</value>
      <webElementGuid>1d9ad8c7-0c44-4ab8-8d72-f4db33a7d1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/input</value>
      <webElementGuid>808fb2f9-b8ea-4269-aace-7a044d2d2549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'advOptShowOnDashboard' and @type = 'checkbox']</value>
      <webElementGuid>4598596f-fbd2-4704-b57a-aae492b80f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
