<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forename(s)_Forename</name>
   <tag></tag>
   <elementGuidId>2c09b46f-6ab4-4fcb-a22a-77c8cecdf77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Forename_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Forename_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b773dd-94dc-4fda-bb8d-35149b9e9744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>ae86c0e3-c3bc-4484-af52-5f3fb6bd64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr:{id: 'Forename_summary'}, value: model.Forename, style: {textTransform: 'capitalize'}</value>
      <webElementGuid>f7c8882b-c138-44da-9bef-d0f2248b95dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eee15a92-f175-4aad-b67a-a5927c664815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Forename(s) must be a string with a maximum length of 100.</value>
      <webElementGuid>0897aba4-7ca8-41aa-91b7-bc574c081cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b023b51d-692a-4438-9d8e-076d17ae456e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Forename_summary</value>
      <webElementGuid>0d5e6317-f3c4-48dd-9640-b31efcdaba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>00aea7ce-6f6f-4684-a853-82508986cb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Forename(s)</value>
      <webElementGuid>ee6bb1d2-d2fe-491c-b2db-a5d8749b1743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b27fe04-12bf-40b5-b9b2-c9e5055539e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Forename_summary&quot;)</value>
      <webElementGuid>53201483-aadb-4828-bac2-fd1430312165</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Forename_summary']</value>
      <webElementGuid>a2344a45-d467-44e9-9db0-5598840c2eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>18af0825-892e-491c-9976-059e8948c35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[7]/div[2]/input</value>
      <webElementGuid>86e40a0e-06dc-4013-8d26-01aa4f597a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Forename_summary' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text']</value>
      <webElementGuid>8a50e859-773f-4d80-8265-fda022688bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
