<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_Surname</name>
   <tag></tag>
   <elementGuidId>8b1e2e69-ca4c-4383-88cd-d228d7e7fae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Surname_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Surname_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>603ac2f0-5a7a-4711-94ff-65825b1eecde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>2ec39856-eb2d-45f7-85cc-72d27fa68432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Surname, attr:{id: 'Surname_summary'}</value>
      <webElementGuid>1b7595e9-56a4-47f3-89a7-ef48e628fc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eabbff67-311c-4d37-a709-e7088de9561a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Surname must be a string with a maximum length of 50.</value>
      <webElementGuid>c88e887e-b548-450c-8e76-7cd5bce716b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7e88cd77-7d03-4ab1-875d-1ae5b5c472e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname_summary</value>
      <webElementGuid>5f5db9d6-d8bb-4837-a153-238e0e4c81b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>65ee4c28-38b3-4c3b-bde0-a4e702deae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>a984c6bf-936b-48ca-a893-3f9501d37f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>462eb6c4-dbea-4946-9d01-777f4ec1bad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname_summary&quot;)</value>
      <webElementGuid>52ca9326-6973-49ea-bdc3-97f235182ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Surname_summary']</value>
      <webElementGuid>19a0d3df-ef22-4686-a9cd-23e680124b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>59edfa51-876b-43e8-a9d1-fbc4af48e071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>daa7d3e7-d1b8-474d-939a-6deb1797a448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname_summary' and @name = 'Surname' and @title = 'Surname' and @type = 'text']</value>
      <webElementGuid>deacba8e-3d58-455a-8a1f-11e263f93c9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
