<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OwnerTeam</name>
   <tag></tag>
   <elementGuidId>2792b4f3-136c-4d81-af04-3135abb257ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;CreatorTeam&quot;)[count(. | //*[@id = 'CreatorTeam']) = count(//*[@id = 'CreatorTeam'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CreatorTeam']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d993d849-3790-4b45-b642-275cec8aadf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreatorTeam</value>
      <webElementGuid>6d8cbe2c-8b84-4754-bdff-b7ca0148973c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreatorTeam</value>
      <webElementGuid>5757e29b-65f5-4061-b86d-3a0422bd7ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Owner Team</value>
      <webElementGuid>18493f53-877c-46be-befb-0b618faeceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreatorTeam&quot;)</value>
      <webElementGuid>411774be-a99e-4da4-b418-69c3e2aa560e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CreatorTeam']</value>
      <webElementGuid>d6aedd58-69a4-41a2-82a0-affe4b3eda6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset[3]/div[2]/ul/li[3]/div/div[2]/select</value>
      <webElementGuid>131e528c-27e0-4c76-98ca-43803cfd3eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner Team'])[1]/following::select[1]</value>
      <webElementGuid>ec83a234-3899-4d61-b93a-e3f928cdb52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator'])[1]/preceding::select[1]</value>
      <webElementGuid>beccff7f-23ff-4552-b009-86c0c58b068d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/select</value>
      <webElementGuid>6dc0db43-a95a-489f-8548-c023336c97f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
