<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Referral Notes Custom Field</name>
   <tag></tag>
   <elementGuidId>59d1eb61-b534-44f2-bb8f-4d4d15a67cee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field.span8 > #Custom2113</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Custom2113']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>341a9c15-a2e5-4a5d-9a7b-8f4b7cc1c873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>f88c676e-68ea-490b-94a1-dcda43a31280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.CustomFields()['Custom2113']</value>
      <webElementGuid>3a9b4b4d-efbb-4e6a-8f4e-091d93341974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Custom2113</value>
      <webElementGuid>b36b04e2-6c6c-4753-a634-96a793ec3c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Custom2113</value>
      <webElementGuid>be309244-835a-49ca-aa86-a87976dd6ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Referral Notes</value>
      <webElementGuid>1d12fe99-99ea-4860-afca-c18eaca59988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[5]/fieldset[2]/ul[@class=&quot;custom_fields&quot;]/li[10]/div[@id=&quot;Custom2113&quot;]/div[@class=&quot;field span8&quot;]/textarea[@id=&quot;Custom2113&quot;]</value>
      <webElementGuid>3108c0ad-8556-4e9a-99d2-3f0258d4d139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Custom2113']</value>
      <webElementGuid>f0c0fa95-6083-4b3d-95b4-1ddc91672b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Custom2113']/div[2]/textarea</value>
      <webElementGuid>7792d948-f179-4cfd-a508-8e61bfb02421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>940bc3aa-8162-494a-b45b-8ce263936dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Custom2113' and @name = 'Custom2113' and @title = 'Referral Notes']</value>
      <webElementGuid>7f95dad7-1748-4d4d-8846-7fe18c8acc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
