<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Incident</name>
   <tag></tag>
   <elementGuidId>ce40060f-d158-4469-897a-163107738c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Incident' or . = 'Incident')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>714fca80-bf8c-4a6e-973f-3b85bb10a41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incident</value>
      <webElementGuid>860a53a3-dc0d-4592-a9e9-f540728a384e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
