<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Next</name>
   <tag></tag>
   <elementGuidId>949cae89-a20c-4b01-8f28-c8e456823c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form5']/div[3]/div/table/tfoot/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Go to the next page&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5813114-995a-4118-a558-f029b4258cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>11b9de3f-ba70-443d-84e9-ac249ab082dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to the next page</value>
      <webElementGuid>11fefdc0-7aac-449b-9029-32bff01be953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: next</value>
      <webElementGuid>0de62a7e-0068-412e-832d-5a579af03804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>6e1ef896-182c-4632-a039-78b96c33c5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form5&quot;)/div[3]/div[@class=&quot;list maxWidth&quot;]/table[1]/tfoot[1]/tr[1]/td[1]/a[1]</value>
      <webElementGuid>bb752519-18f4-4828-a3d2-fd9a76307ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form5']/div[3]/div/table/tfoot/tr/td/a</value>
      <webElementGuid>f5544564-07aa-422d-a0cc-2c64fa0a5ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Next')]</value>
      <webElementGuid>0f25c7ce-9754-4637-9cea-2056907074ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='stevenk'])[2]/following::a[2]</value>
      <webElementGuid>8bfeb113-c836-4b5e-932e-ea91e914bb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10 of 652 records'])[1]/preceding::a[2]</value>
      <webElementGuid>81a4d95b-4bca-45d2-9aa0-704908364216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 10'])[1]/preceding::a[2]</value>
      <webElementGuid>9a84d813-7f95-493b-ab1e-e0fe65527309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[89]</value>
      <webElementGuid>5487ac52-7179-4159-b218-baa4d0bfc653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/td/a</value>
      <webElementGuid>6f11f606-10e8-4390-9586-8a8a483bc4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Go to the next page']</value>
      <webElementGuid>aecfe363-7242-40ad-8717-ede6cd189c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
