<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_Title</name>
   <tag></tag>
   <elementGuidId>d41e27d1-9d41-49fa-8250-c2f2de83305a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Title_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Title_summary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Title_summary' and @name = 'Title' and @title = 'Title' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e84b42e-694b-4d9c-9943-b4f30cbd861b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>9e477ea9-02cc-4b94-8efb-25c1b240e4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Title, attr:{id: 'Title_summary'}</value>
      <webElementGuid>33750c94-e4b3-4332-b5e1-9eb579e7f63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title_summary</value>
      <webElementGuid>a8bf793c-86a7-4e7e-9ea4-31b16a5c68f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>35768981-fac4-48fc-9758-21deea44f1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>43784008-93a4-4ec3-9387-c2b6692e731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7714b4da-dc51-41d2-a8e8-00f2f99fb209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title_summary&quot;)</value>
      <webElementGuid>4980f2f5-e9b0-4fff-b996-7b0887166a27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Title_summary']</value>
      <webElementGuid>be1aded4-9d60-4cbb-a802-5da481e00e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li[3]/label/span[2]/input</value>
      <webElementGuid>ca93d86b-e86a-46f8-bc45-683da426ab74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[3]/label/span[2]/input</value>
      <webElementGuid>38362fe1-86b8-439d-bda5-bc88dd87636b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Title_summary' and @name = 'Title' and @title = 'Title' and @type = 'text']</value>
      <webElementGuid>33f1e09f-fc3a-4048-9563-466d1ffe7a7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
