<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Given By_GivenByName</name>
   <tag></tag>
   <elementGuidId>a6339ee8-f171-4c28-9012-1569d0e5e508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GivenByName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GivenByName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'GivenByName' and @name = 'GivenByName' and @title = 'Given By' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>660c7a9b-182a-4d4f-85df-26887e4c36c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line disabled</value>
      <webElementGuid>b323ccc0-1633-4ac5-acc9-d445bc991730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>style:{backgroundColor:'#f0f0f0'}, attr:{readonly:'readonly'}, css:{disabled:true}, value: (model.GivenBy() ? model.GivenBy().Target().FullName : null)</value>
      <webElementGuid>eb061aab-c096-4ea3-8d45-811f3b12bd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>875fc9b9-ea6e-45e9-998e-581a84228dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Given By field is required.</value>
      <webElementGuid>25dc544e-541a-4d15-b209-eb5e32a55ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GivenByName</value>
      <webElementGuid>ce1cae93-5712-42d6-84f9-6a44e5476400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GivenByName</value>
      <webElementGuid>66f5d4b3-a42b-4c62-8907-7885b79f325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Given By</value>
      <webElementGuid>7c2f8bdb-794c-4168-bce1-c7cd65f48aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65ec303e-c742-439e-8991-4ebb94a9b7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>76a5d4a7-e4a7-4449-ae6b-dd352dc7f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GivenByName&quot;)</value>
      <webElementGuid>16c60083-a52a-4da0-a7bf-a565347f7e4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GivenByName']</value>
      <webElementGuid>0b0b7047-44ea-4c4b-8094-bc5d7a8c249e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-15']/div/form/fieldset/ul/li[4]/label/span[2]/input</value>
      <webElementGuid>dad33afb-26b3-4399-a312-c35188b8d5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[4]/label/span[2]/input</value>
      <webElementGuid>4a9e0603-948c-4577-a56c-d29b7e12dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GivenByName' and @name = 'GivenByName' and @title = 'Given By' and @type = 'text']</value>
      <webElementGuid>02f7e747-46ef-41f9-aee0-cbc39120b4b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
