<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Witness_Statement_Type</name>
   <tag></tag>
   <elementGuidId>b0e02d27-0532-4491-9e5d-55e01950da87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Type_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Type_summary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2ba8c4e8-d852-4dcb-b4f9-e185d62d8399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>efe6bd4f-e4c7-4515-9a14-4fc5f4099fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr:{id: 'Type_summary'}, options: clue.filteredLookup('4c46e027-3794-4184-b95f-733488a8fecd', model.Type), optionsText: 'Value', optionsValue: 'Value', value: model.Type,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'37dbdeda-5649-4053-b9bf-e4140aa5eb0e', model.Subtype, model.Type);}}</value>
      <webElementGuid>41b8b00a-f0d6-4e0d-9c45-ca4a1bb07bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa3c3b36-8a55-4365-9518-46bfd5483bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Type must be a string with a maximum length of 255.</value>
      <webElementGuid>2964d973-069c-441b-a27b-6dc00cb6a704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>3660ba23-642e-4ca6-9ce8-cb73f86b063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type_summary</value>
      <webElementGuid>0105271c-d2fb-4931-bffe-deff9512a9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>0e735a81-e5cb-4a80-b5a2-ad56f54d1edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>c137a3d0-4921-42a9-9f73-aeded7802be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Taped TranscriptWitnessWitness Statement
</value>
      <webElementGuid>6473eca4-ab07-4494-8f39-b3ae11673013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type_summary&quot;)</value>
      <webElementGuid>3de3fe26-1861-46c5-83ad-b8676054fb3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Type_summary']</value>
      <webElementGuid>7f57289b-de88-4a6b-94e5-784cb899c86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/form/fieldset/ul/li/label/span[2]/select</value>
      <webElementGuid>52eb15fa-0ede-4a4e-a168-59263a657ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type:'])[1]/following::select[1]</value>
      <webElementGuid>f66fd73e-5f21-44cd-851e-e3024adbb64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please correct the following:'])[3]/following::select[1]</value>
      <webElementGuid>35d48baa-5352-473c-8f69-81420415aab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtype:'])[1]/preceding::select[1]</value>
      <webElementGuid>e44fe48f-f3e9-4f7e-b33c-d875fdc8d822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title:'])[2]/preceding::select[2]</value>
      <webElementGuid>1160b34d-f1ac-4639-929a-060047cb9449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/select</value>
      <webElementGuid>cb6b3319-6998-4c3d-8523-301cc12a6b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Type_summary' and @name = 'Type' and @title = 'Type']</value>
      <webElementGuid>a69f3baa-c208-4efb-a47e-cd0b7cbb697e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
