<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open</name>
   <tag></tag>
   <elementGuidId>fc7bc073-ea4e-4ffe-8067-bd86d5b4b43a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='openNote(event,4)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93390120-ed69-4fe7-821f-c5078c90f56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openNote(event,4)</value>
      <webElementGuid>c5325f88-b83e-44c3-b9ac-eb3907e954ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-10 font-semibold rounded-sm text-sky-700 hand focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2 hover:underline hover:text-sky-500</value>
      <webElementGuid>b4620824-c328-4482-a1a7-79d0224d3a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Open
    </value>
      <webElementGuid>795e3ebf-796d-4527-a118-8fc411731683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes&quot;)/div[@class=&quot;flex flex-col h-screen lg:h-full&quot;]/div[@class=&quot;-mx-2 pb-4 overflow-auto&quot;]/div[@class=&quot;inline-block min-w-full align-middle lg:px-2.5&quot;]/div[@class=&quot;shadow border-sm ring-1 ring-black ring-opacity-5 md:rounded-lg&quot;]/table[@class=&quot;min-w-full table-auto border-separate&quot;]/tbody[@class=&quot;divide-y divide-gray-200 bg-white&quot;]/tr[@class=&quot;cursor-pointer relative hover:bg-gray-100/[0.3]&quot;]/td[@class=&quot;border-b border-gray-200 py-4 px-3 text-sm align-text-top text-gray-900&quot;]/a[@class=&quot;z-10 font-semibold rounded-sm text-sky-700 hand focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2 hover:underline hover:text-sky-500&quot;]</value>
      <webElementGuid>f6a27099-b7b7-4150-a07a-a2c8f1d74b26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='openNote(event,4)']</value>
      <webElementGuid>46684dd1-fdae-4435-96dc-a0caf8b4394d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Notes']/div/div/div/div/table/tbody/tr/td[6]/a</value>
      <webElementGuid>b7eca8dd-43d9-4972-b31d-75c1c1a8c8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open')]</value>
      <webElementGuid>71943b55-ff3a-4379-a9ee-b57386399c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emma Lancashire'])[1]/following::a[1]</value>
      <webElementGuid>aade831a-af9e-4f3b-a849-a35034f9ea71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Record'])[1]/following::a[1]</value>
      <webElementGuid>660992d4-70a8-4513-829d-e85a430b9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Note'])[1]/preceding::a[1]</value>
      <webElementGuid>6f490bb3-56c8-49b0-b7cb-fa0e2f6313d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::a[1]</value>
      <webElementGuid>7eef4b67-4801-42b5-a65e-2f67e0b06c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open']/parent::*</value>
      <webElementGuid>50b6405b-a75f-44ea-9441-d42a3491b8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>6610c0b8-8619-4951-b260-0c5a0fb870bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
