<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>a7191049-5876-4fa7-a798-919975a88bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99977208-304c-447d-a60a-d6872d4ad81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex justify-center rounded-md border border-transparent bg-blue-800 py-1 sm:py-2 px-2 sm:px-4 text-sm font-medium text-white shadow-sm hover:bg-blue-900 focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2 disabled:bg-gray-100 disabled:text-gray-400 disabled:border-gray-300 group</value>
      <webElementGuid>a19f825f-972a-4c8d-a84e-41a6ef1f31a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>5a91ff6a-413c-4843-bbb4-2ccc56b930a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>submitNoteCrudForm(event)</value>
      <webElementGuid>83aaa572-730b-4aa7-9dd0-85d71fe0f907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>50d21f81-7b9a-4538-89b7-fb8a142c958d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Add Working</value>
      <webElementGuid>1b22b236-5d06-49f2-b335-0770889ab191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Add&quot;)</value>
      <webElementGuid>fbb288ac-6199-45b1-9b83-044bdd3de3f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Add']</value>
      <webElementGuid>003d239a-29f7-44b5-9377-3eeeeaa714d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noteCrudModal']/div/div[2]/div/div[2]/button[3]</value>
      <webElementGuid>d5bd0e18-205d-4fd3-af78-f2c1b972a834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working'])[4]/following::button[1]</value>
      <webElementGuid>d4ed777d-edad-4eac-821b-450e674b8650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Another'])[1]/following::button[1]</value>
      <webElementGuid>350edefc-ebcd-40d9-b499-c839096f4ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[3]</value>
      <webElementGuid>bfac54a5-7b9f-4a5a-bede-85ef9ce9fd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Add' and @type = 'submit']</value>
      <webElementGuid>363f0897-5db8-471c-ad81-7aaf8d7e570c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
