<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DateTimeOfOccurrence(Notes UI)</name>
   <tag></tag>
   <elementGuidId>c8329520-a3e0-4175-b957-42300a565498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OccurrenceDateTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OccurrenceDateTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5b88094-695e-4672-a54a-41a4fe55fa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OccurrenceDateTime</value>
      <webElementGuid>1d93b558-9343-46cc-b7f3-55037e6c8435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OccurrenceDateTime</value>
      <webElementGuid>1fb42536-3ddb-4538-b3bb-6cb0672154cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select date</value>
      <webElementGuid>91e5b1a2-b6c5-4552-9377-1899f5ed804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OccurrenceDateTime&quot;)</value>
      <webElementGuid>4791729a-9a52-48f4-92bd-c8f3334f75f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OccurrenceDateTime']</value>
      <webElementGuid>2668d203-be76-4bb7-a33b-8f68943c2dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noteCrudModal']/div/main/div[5]/div/div/div/input</value>
      <webElementGuid>d4f5197a-6afd-4a5d-959e-70af3ada6fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[5]/div/div/div/input</value>
      <webElementGuid>246b215d-05e6-4b46-9612-bfa145939e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OccurrenceDateTime' and @name = 'OccurrenceDateTime' and @type = 'text']</value>
      <webElementGuid>41b70fef-1e87-4640-80cb-c7d64a1e48c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
