<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Note_Close</name>
   <tag></tag>
   <elementGuidId>1cd69c89-fedb-4a7b-8f42-5ae66e9ff46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Close</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Close&quot;)[count(. | //button[@id = 'Close' and @type = 'button' and @onclick = concat(&quot;closeModal(&quot; , &quot;'&quot; , &quot;viewModal&quot; , &quot;'&quot; , &quot;)&quot;)]) = count(//button[@id = 'Close' and @type = 'button' and @onclick = concat(&quot;closeModal(&quot; , &quot;'&quot; , &quot;viewModal&quot; , &quot;'&quot; , &quot;)&quot;)])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>578a46e8-9c98-4e09-9317-c6fc10f87464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>cf6fa376-5d3b-44e8-b0b0-95a9bb1082c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ce0be1f-d013-4f00-b297-a115d98cbb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closeModal('viewModal')</value>
      <webElementGuid>b308e37d-f1ba-4d54-ab14-018ed3b0e9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Close&quot;)</value>
      <webElementGuid>35d44b1b-1b6d-41da-a028-6fdf3cca9482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Close']</value>
      <webElementGuid>de91fe5b-0436-45f8-a9c8-cceacaa47a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='viewModal']/div/div[2]/div/div[2]/button</value>
      <webElementGuid>d594e2de-9b42-43ea-927d-8b556ff53791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date/Time of Occurrence'])[7]/following::button[1]</value>
      <webElementGuid>f2d29e62-0b61-48aa-b1e6-8efdb6a980da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Record'])[2]/following::button[1]</value>
      <webElementGuid>4a98f954-83ff-4db2-903e-35c78220da0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clue Computing Company Ltd'])[1]/preceding::button[1]</value>
      <webElementGuid>d61e64a8-a75d-44b6-bcf8-2ee82fddb055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>a17c6bb7-0643-4673-a677-2433d7464e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Close' and @type = 'button']</value>
      <webElementGuid>5dbb8b4b-56d2-4c77-8bf0-d3289ec9b4eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
