<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox(FieldManagement)</name>
   <tag></tag>
   <elementGuidId>1d06b0dd-80d0-45f3-af86-da1275d48743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='FieldList']/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4311285-7bd2-4e2c-a51b-3ed1900edcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5f07e44-32d6-4918-8610-89a5a9ea463e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>disable: $parent.allowDbNull($data.Setting().IsRequired) || $parent.disableEdit(), css: {disabled: $parent.allowDbNull($data.Setting().IsRequired) || $parent.disableEdit()}, checked: $data.Setting().Mandatory</value>
      <webElementGuid>2c551ef2-f85d-4c8e-bb1f-83bd27c8cb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FieldList&quot;)/tr[1]/td[@class=&quot;text-center&quot;]/input[1]</value>
      <webElementGuid>537e893a-ef3e-4632-a635-8e8396266f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>3e2f232a-78d3-4cf8-91cf-ec2822f55e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='FieldList']/tr/td[2]/input</value>
      <webElementGuid>5efeb244-f8c7-4b1a-b265-465cca77a1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>da8fc81b-52a5-4357-80c1-04085ed2693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>0d0c7505-89f2-454e-bb65-b847f489d56c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
