<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MoveRight(Lists)</name>
   <tag></tag>
   <elementGuidId>a5b4ba75-0734-4d8a-a1db-2325d9511f75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.moveRight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bbbb8b5-d27a-496f-a6d4-ec6e154456a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moveRight</value>
      <webElementGuid>72fdaba2-581c-49fd-899c-1666a39b10a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9265a052-82f1-4df5-a0a4-a3db8f31333e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: addField, disable: !selectedAvailableField(), css: { disabled: !selectedAvailableField() }</value>
      <webElementGuid>004f5d7e-1857-4df6-8abf-a3efc33fe8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnsDiv&quot;)/ul[1]/li[1]/div[1]/div[@class=&quot;span1 span1-custom&quot;]/button[@class=&quot;moveRight&quot;]</value>
      <webElementGuid>4aac15f1-32de-4ba5-8c45-2a92b39ac596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>5a0c29a5-ea42-45b5-8414-9809169e8f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='columnsDiv']/ul/li/div/div[3]/button</value>
      <webElementGuid>cca0291c-4bab-48a4-9e33-f0f27900501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>119aed2b-e4ef-48ca-949a-9d2e3b55cd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>f843afa2-5875-4eaa-baa2-f23631cfb6b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
