<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ScheduleDropDown</name>
   <tag></tag>
   <elementGuidId>706d5efd-de08-4632-8d96-2da2cc3f4407</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AvailableSchedulePrintLayoutSelector</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AvailableSchedulePrintLayoutSelector']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d91521ac-880a-42d0-a3e0-34da92b2c353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AvailableSchedulePrintLayoutSelector</value>
      <webElementGuid>869a8787-1554-4180-b01c-05c4da06fe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box</value>
      <webElementGuid>9fa8961d-6f2c-4e12-8a26-99912384130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>69136991-6774-44a6-ae23-ff25aa221b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options:availableSchedulePrintLayouts, value:selectedSchedulePrintLayout, css: { hidden: availableSchedulePrintLayouts().length &lt; 1 }</value>
      <webElementGuid>cfb82897-f4f6-4f23-9f7b-3ac63be440fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MG12 Exhibit ListMG6C Unused non-sensitiveMG6D Unused sensitiveMG6E Disclosure officer’s reportMG9 Witness List </value>
      <webElementGuid>954a3157-2ec5-437e-acca-1cb9316ed0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AvailableSchedulePrintLayoutSelector&quot;)</value>
      <webElementGuid>d063c915-fe2d-493f-a60a-13a2d396a0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AvailableSchedulePrintLayoutSelector']</value>
      <webElementGuid>001d7e3f-a8f2-4780-bfc6-770247d8a659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span[5]/span/select</value>
      <webElementGuid>2c3c0070-ecbe-432d-b0ff-3ebc88e6a823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Word'])[1]/following::select[1]</value>
      <webElementGuid>9841ad66-2e7b-4b14-afb2-01edb80ec1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::select[1]</value>
      <webElementGuid>78bd9275-5dc2-4509-85db-cb6b0744a3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classification'])[1]/preceding::select[1]</value>
      <webElementGuid>6973b280-7f93-4b58-b119-8d139833d9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Last Synced 09/11/2023 15:00:16)'])[1]/preceding::select[1]</value>
      <webElementGuid>f4c61d48-8dc8-4c81-b2e1-c6b1b9370430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/span/select</value>
      <webElementGuid>f44410e0-2587-41ee-b481-0082478019a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AvailableSchedulePrintLayoutSelector']</value>
      <webElementGuid>441797ed-7370-4bac-8370-def7a0d2294b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
