<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectWitness_1</name>
   <tag></tag>
   <elementGuidId>4c46a2b6-c83e-4b55-8fa0-62b65effcbed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6be57c1-9f96-4419-bb74-10e16d093210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-1</value>
      <webElementGuid>a967f6ab-1cda-4e25-b6b2-a9b24561ed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>986830aa-e08f-44bc-b461-8c2315f0673a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectRow(event,1)</value>
      <webElementGuid>7c6acc1f-102d-4804-926e-a1aa118e50b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f550215-7182-460c-bed0-3f841ef5ab4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute left-4 top-1/2 -mt-2 sm:left-6 h-4 w-4 rounded border-gray-300 text-sky-600 focus:ring-sky-500 focus:outline-none focus-visible:ring-sky-500 focus-visible:border-sky-500 disabled:bg-gray-300 disabled:cursor-not-allowed</value>
      <webElementGuid>70ee235e-c9ec-4db0-aba1-56788486dac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-1&quot;)</value>
      <webElementGuid>97862e69-17d2-464d-965c-ad02bd849138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-1']</value>
      <webElementGuid>1711f354-ddcc-4a1c-9d37-7b48f458bc1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td/input</value>
      <webElementGuid>d84e0672-e9d2-4784-96df-6fcc30fd9f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>5a7fb5ca-6b81-44a8-a067-5c4b1e73971c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb-1' and @type = 'checkbox' and @title = 'checkbox']</value>
      <webElementGuid>63b83c86-088f-432c-91dc-63143cc38d30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
