<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OperationNameNumber</name>
   <tag></tag>
   <elementGuidId>fd56f268-a4b8-4cea-b2f1-047d0f310927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;OperationNameNumber&quot;)[count(. | //*[@id = 'OperationNameNumber' and @title = 'Investigation']) = count(//*[@id = 'OperationNameNumber' and @title = 'Investigation'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15f02ec1-9ebd-4cc4-9647-6b83bb021f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>1f9e1a29-9f70-4f51-a16f-97404804b166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.OperationNameNumber, attr:{maxlength: '255'}</value>
      <webElementGuid>0f9e60bf-5784-43ee-8273-d87da9112ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OperationNameNumber</value>
      <webElementGuid>54a72652-46a4-4e5d-a1bd-4df9448fad2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OperationNameNumber</value>
      <webElementGuid>ee5b76b2-bcfa-4bae-8ef3-47d33d72133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Investigation</value>
      <webElementGuid>10280e64-ae10-472b-a495-7f3d2c87df91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1441b20-d4a9-4a93-8002-10c36c96a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>589e5392-8173-4252-9582-cb4ba3788d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OperationNameNumber&quot;)</value>
      <webElementGuid>1b10da44-f06d-431f-acc2-bbf4f9e894d0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
