<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReportTitle</name>
   <tag></tag>
   <elementGuidId>4a4b6089-b1e7-4107-9f86-34b54cf7218b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ReportTitle&quot;)[count(. | //input[@id = 'ReportTitle' and @title = 'Title' and @type = 'text']) = count(//input[@id = 'ReportTitle' and @title = 'Title' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bb5c214-3a84-4ddd-afd1-dc01cca1ecbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>394efe0f-945d-469c-8ddc-5627f26a59f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.ReportTitle, attr:{maxlength: '255'}</value>
      <webElementGuid>7b3e4caa-18c8-4c1c-9e6e-a60b6cceebb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReportTitle</value>
      <webElementGuid>acc293cd-3906-483f-a63c-4f9c68cfa305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReportTitle</value>
      <webElementGuid>a83b3ec2-329b-40e8-b0be-b14d85a5e61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>83d98b20-8fde-4415-bec1-6d7f86c23433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6531629f-2853-4525-a866-bf90d9ed1c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>89669d4f-68bf-4e8b-a090-edea99b10553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportTitle&quot;)</value>
      <webElementGuid>f4c74c66-fade-4ba6-9fb5-da5698827b23</webElementGuid>
   </webElementProperties>
</WebElementEntity>
