<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Details(Inv.Notes)</name>
   <tag></tag>
   <elementGuidId>73caca67-9ed3-411f-a896-a1624203c6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='Notes'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.field.span13 > #Notes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>db26fbb3-4f78-43d4-a4d9-82cd2291859e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>7f84b2e6-3039-476c-89fa-8a723ddd1532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Notes</value>
      <webElementGuid>4a0c5b12-a9c5-41af-b60a-5bc83e8f6900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>e53ca4b7-092c-4bc3-b113-49f59b12ac4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>bb171d4b-71f5-4356-8ebd-68f9044415ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Details</value>
      <webElementGuid>67390d50-a9a7-41ff-b0c5-c2cda306cf8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog1&quot;)/form[1]/fieldset[1]/ul[1]/li[4]/div[@class=&quot;field span13&quot;]/textarea[@id=&quot;Notes&quot;]</value>
      <webElementGuid>a182e57d-eec9-45b7-8487-9d529df80991</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='Notes'])[2]</value>
      <webElementGuid>7b8df214-986a-4676-993e-dac6d3a859b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog1']/form/fieldset/ul/li[4]/div[2]/textarea</value>
      <webElementGuid>db95629c-732d-408c-b9f4-ec2c268390df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/textarea</value>
      <webElementGuid>a5d30402-c170-4259-9367-aa27e65e33ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Notes' and @name = 'Notes' and @title = 'Details']</value>
      <webElementGuid>a46a5256-1f85-4eaf-a94a-7f01faeb0abe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
