<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnteredBy(Inv.Notes)</name>
   <tag></tag>
   <elementGuidId>8a9fbf67-757c-411b-b057-8bb64dacc942</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Personnel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Personnel</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Personnel&quot;)[count(. | //select[@class = 'combo-box editable' and @id = 'Personnel' and @name = 'Personnel' and @title = 'Entered By']) = count(//select[@class = 'combo-box editable' and @id = 'Personnel' and @name = 'Personnel' and @title = 'Entered By'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48ed0770-f0f9-4610-9ad5-8b899ef55a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>88c50c52-f958-441a-9d33-94f616352bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('cccb777e-06e7-4e2c-b54e-02ab304439ba', model.Personnel()), value: model.Personnel</value>
      <webElementGuid>27cfae6d-498c-4ed4-bc73-3c0276984fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e610dd3-a6ff-40b2-a0c3-361e51080332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Personnel</value>
      <webElementGuid>7407fe26-54e8-4f9c-909c-20a00b55a925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Personnel</value>
      <webElementGuid>13fba813-c89d-4a01-a4a6-15424081be51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Entered By</value>
      <webElementGuid>6c38e2d1-2191-4d55-b22c-637f255dba18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Personnel&quot;)</value>
      <webElementGuid>d881aa2d-0231-4d7d-a7a3-68a2ab6b2376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Personnel']</value>
      <webElementGuid>2d000a45-01e3-4eda-b2b1-7b588e3f2e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog1']/form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>6598fec5-cfb4-4706-9699-f69a27252369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entered By'])[1]/following::select[1]</value>
      <webElementGuid>222442f7-091b-4eb8-b91e-a619f3541423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[2]/preceding::select[1]</value>
      <webElementGuid>bbf5cf6d-8268-40df-af26-225e82d3f4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>bc834ab0-dab6-4848-9f40-38a2e8cae9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Personnel' and @name = 'Personnel' and @title = 'Entered By']</value>
      <webElementGuid>7a32fdb1-1813-40ef-8fb6-4c7169319041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
