<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reference(Inv.Notes)</name>
   <tag></tag>
   <elementGuidId>f97de012-c8d0-46ec-a979-9b3b3cec403f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='Reference'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'Reference' and @name = 'Reference' and @title = 'Reference' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a2a206f-3f8e-476b-9572-92900a0e192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>b950da11-d103-48f3-a451-02b295be262b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>eabc22c6-acbf-477f-9181-33491ef3bf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>05fe79e3-34b5-4e8c-b70e-fb6ae237d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>91d4ac66-38a8-48c7-8d08-c4e7e21f797b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='Reference'])[2]</value>
      <webElementGuid>cee7e4b3-c8eb-4e53-8561-190a5d2c4959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog1']/form/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>470aaef8-dee8-4e0e-a927-4805e1f98958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>4effbc2e-043e-4a5d-881d-d5f83a7d0ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Reference' and @name = 'Reference' and @title = 'Reference' and @type = 'text']</value>
      <webElementGuid>508ff0b9-39b5-45be-b913-41f7e80d1836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
