<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname</name>
   <tag></tag>
   <elementGuidId>915ff7ba-1a07-42b1-8ff6-da9b368e021e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Surname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Surname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66eef16c-555c-4213-a938-10719521a98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-fieldmanagementrequired-dependentproperty</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>e25901b1-9f74-4b36-8e7a-f88cd84f9012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>cc472b60-e5fa-4752-96d3-4b5a49854a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>234a7410-5ea5-43dc-b43c-4c7faf73b84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Surname</value>
      <webElementGuid>e8f7ac3f-46e3-4ca2-91ca-3aa4328de9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57f31c01-b3cb-402f-b891-6b44fd79e68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Surname&quot;)</value>
      <webElementGuid>8e2e1ace-c333-49a9-84a9-bf8f00e59ba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Surname']</value>
      <webElementGuid>c0460bc7-e933-4788-880d-7670953e1d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[5]/div[2]/input</value>
      <webElementGuid>00565e5f-57b4-43db-8628-cb981b087e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[2]/input</value>
      <webElementGuid>eaba7d29-a9f8-4e60-963c-2b0798921e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Surname' and @name = 'Surname' and @title = 'Surname' and @type = 'text']</value>
      <webElementGuid>5e553adc-eb03-41cd-b421-0d618d2818de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
