<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference</name>
   <tag></tag>
   <elementGuidId>f498136c-0ba7-49f5-a330-95c3cdeb9236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0848230-2307-4a60-a441-e4cdf45c329c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>bb1b50c7-b3b1-46e9-82e5-8eb491dd58c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>300ad04e-1c4c-4081-a3d3-806a606c0959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>07dd43b1-e63c-44b1-9f5d-bbea299749a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6872e3a0-f9a2-4147-b023-50754ceb3a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reference&quot;)</value>
      <webElementGuid>d92a5ee8-7903-45fc-8404-d2f612fd7802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Reference']</value>
      <webElementGuid>9db68688-436e-45fc-b751-80a6611f90e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[3]/div[2]/input</value>
      <webElementGuid>b99ccb10-9992-4b18-b800-3cf74e7d8190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c098cd5a-2f17-4893-857a-965f81f19778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Reference' and @name = 'Reference' and @title = 'Reference' and @type = 'text']</value>
      <webElementGuid>28afa74b-c86a-40ba-a0d6-ee5b84548f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
