<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forename(s)_Forename</name>
   <tag></tag>
   <elementGuidId>082284e6-4053-484b-8567-3dbb946764f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Forename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Forename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>225bdb6c-ef57-4e8f-982e-86936ddec1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>5620d431-7ed5-498b-aa96-b544b5dafd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Forename, style: {textTransform: 'capitalize'}</value>
      <webElementGuid>439c343f-9300-47be-8073-460368939ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1f65a03-308b-4558-bc60-a693f5b316c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Forename(s) must be a string with a maximum length of 100.</value>
      <webElementGuid>718f0342-e18a-4ae1-9ecf-4a5b7ff30a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ce77f310-5ec0-4aef-aee3-52eaa0da51e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>0bce4cb0-5b72-4f13-af39-e1c136f1cf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>ffb187f2-49ab-4971-9dc0-339abd8de06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Forename(s)</value>
      <webElementGuid>782289a3-bb84-4a4d-a05c-cc371da8462c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6bcbeb7f-d9e8-459d-834f-970d2eac819f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Forename&quot;)</value>
      <webElementGuid>db8452e9-ddea-4a05-9451-8a709add94d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Forename']</value>
      <webElementGuid>f28c5e1e-afa6-4ff4-8b1b-4992a3451b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[6]/div[2]/input</value>
      <webElementGuid>ae5ed766-4f22-4c02-a162-edcd0a46c9fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[2]/input</value>
      <webElementGuid>851c62eb-0931-41ed-a7d0-c6189a473f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Forename' and @name = 'Forename' and @title = 'Forename(s)' and @type = 'text']</value>
      <webElementGuid>5bdb1686-5b5b-4f5b-bac1-b40b57413392</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
