<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FemaleMaleUnknown</name>
   <tag></tag>
   <elementGuidId>ac5170a9-58eb-43cf-a8ab-a31404253bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Gender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>047481e0-a033-4f8d-98a4-fc0862f75dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>c12d1683-f3c2-4b79-aafb-ec17f0459a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('52e78012-cd5f-4f7f-87ea-85e2bd925f18', model.Gender()), value: model.Gender</value>
      <webElementGuid>a1c0fae7-a9fb-4dd0-90d5-8a4cb187d78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d15f2171-6151-4157-a63f-37ea7923ae92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Sex must be a string with a maximum length of 255.</value>
      <webElementGuid>9e5da450-e1c0-4187-9763-30ccbeb37652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>952fbcdb-6195-4f53-8c1a-4b29e74d5745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>858f6b2e-fb75-4713-b3f9-fffb13ff07da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>78b080d2-c6fc-4d26-8a1c-dbc110729468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>4cd3119f-1255-4463-ae1a-92d8d332a7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FemaleMaleUnknown
</value>
      <webElementGuid>bb207405-cc60-41e1-a39b-5ac44e652964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Gender&quot;)</value>
      <webElementGuid>4939a261-5e2b-43f0-a49a-2da36fc4e543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Gender']</value>
      <webElementGuid>903a7b4a-3bb5-41ba-b35b-1b8f5605cac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[9]/div[2]/select</value>
      <webElementGuid>e158587f-a394-4870-ba99-40f479db7d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sex'])[1]/following::select[1]</value>
      <webElementGuid>09d5cf06-e981-4a03-b965-4bbf608a23b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Height (imp | met)'])[1]/preceding::select[1]</value>
      <webElementGuid>2c2f4e20-93a5-42ec-8f0d-0d7d90a1dd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div[2]/select</value>
      <webElementGuid>f2f0ed97-4d27-4b60-97d1-eff96c3cfd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Gender' and @name = 'Gender' and @title = 'Sex']</value>
      <webElementGuid>c095fd2c-356e-48a3-bca8-796095ae78bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
