<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AgentBettorPerson of InterestBlighty_f4d8e3</name>
   <tag></tag>
   <elementGuidId>5b5d2836-fc8d-4706-b50f-8817499954e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecordType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RecordType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4651d267-4e55-4e4d-99d9-7acdf853234a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>65b0ee09-7017-4025-acf6-c17ada7786e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.filteredLookup('85e533b5-4674-4f26-b38a-5afe8f268cc8', model.RecordType), optionsText: 'Value', optionsValue: 'Value', value: model.RecordType,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'b4f527a5-f678-499e-8528-bb046ef37a7e', model.Subtype, model.RecordType);}}</value>
      <webElementGuid>fcbf6f90-1383-458a-8020-ae5591441fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5255f02b-a5ea-405f-a2ce-85fde2c09df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Type must be a string with a maximum length of 255.</value>
      <webElementGuid>83f09d7e-9ac6-4168-91cd-f41ace69c5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>23d4818c-883d-4ab4-ad3e-8292c7131724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecordType</value>
      <webElementGuid>aa1dcc9e-e5fc-4093-aa70-6ffaf1edc3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RecordType</value>
      <webElementGuid>95b653f0-2bd2-4dff-b304-da3e663e56eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>284ac064-3e8f-4a35-a879-791a9062a42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AgentBettorPerson of InterestBlightyManagerMember Of PublicOfficialOtherPlayerReferee
</value>
      <webElementGuid>b5bfb486-526e-4d09-8e50-d66efe6917d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecordType&quot;)</value>
      <webElementGuid>84c31dc5-25a1-4cbc-9104-e433cc5cb5ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RecordType']</value>
      <webElementGuid>0d351173-948c-4333-b55a-a4a783f68878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li/div[2]/select</value>
      <webElementGuid>203026b5-b08e-4f2e-b24f-c3277b5eb07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>e6a12e2c-e8a2-4a5b-9dbf-9c44901e2f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>42f79276-98bd-4029-b647-d7c66586e87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>cc8e55a6-d813-4dfc-a269-436b098efdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RecordType' and @name = 'RecordType' and @title = 'Type']</value>
      <webElementGuid>bbe29d1e-2beb-4416-ae29-c986be610d34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
