<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DrMissMrMrsMs</name>
   <tag></tag>
   <elementGuidId>4fcf44e7-cf28-4895-ac9c-339958a56484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9b6d249-239f-4c86-9ffd-1ad6be195a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>d5349c1d-2744-4714-9728-d507478bde66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('018b96c0-3a36-4d93-b01c-17be84d714b9', model.Title()), value: model.Title</value>
      <webElementGuid>21688158-cea2-479b-a8b6-184f7f29ebfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aacb1528-0c96-4020-a418-d1189f840c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Title must be a string with a maximum length of 255.</value>
      <webElementGuid>46a795a5-54fe-4a3a-9289-9af637e3384f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>f82b342a-2b62-4747-a496-bf1f45194b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>e6a9a718-1af2-4f0d-b1ba-f3b1272b7139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>606ce54d-a375-4b1e-aa59-8514fcd377a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Title</value>
      <webElementGuid>d44f029c-1659-4714-8557-ac8764dd14d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DrMissMrMrsMs
</value>
      <webElementGuid>c1f9b357-0c8a-405e-9a9b-e1496e0df6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Title&quot;)</value>
      <webElementGuid>820df127-8591-433e-b7d1-31bbecc243f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Title']</value>
      <webElementGuid>8503bb93-3c49-44ab-8d84-84542d2b8dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[4]/div[2]/select</value>
      <webElementGuid>623ae1b7-8324-4e2c-a079-964305b52920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>84790327-7d8c-4e55-b4ed-a9092211c973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/preceding::select[1]</value>
      <webElementGuid>32dd0cfc-115c-466d-9bb4-01593c635d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/select</value>
      <webElementGuid>864f6d69-761c-4449-9198-9c79178f3733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Title' and @name = 'Title' and @title = 'Title']</value>
      <webElementGuid>921a0797-5e63-4986-b727-52f2929eb260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
