<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_Notes</name>
   <tag></tag>
   <elementGuidId>53bf9047-028c-4960-b1e0-7bf7e449588b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aba9d6fa-6606-487b-a3f9-b1cf2768ef60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>99fbd8d5-95b6-4adc-919e-97fd605a6ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Notes</value>
      <webElementGuid>b685fce5-cac2-4887-8d63-6f8e433b9129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>13a90982-49cb-48ca-ba86-69b8e4556439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>4f23478c-6627-4a0d-ad9b-83420b2f62c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>771066db-261d-4051-a240-d907e35ecdb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Notes&quot;)</value>
      <webElementGuid>2476647f-bde8-4932-b95a-717af4f8a7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Notes']</value>
      <webElementGuid>d144720e-6d64-4a92-80f8-7c04f91ee357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[25]/div[2]/textarea</value>
      <webElementGuid>c04502f3-c539-4a88-9241-236cbe875ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[25]/div[2]/textarea</value>
      <webElementGuid>c057d4a8-1b4d-4103-99d7-2c0d2b54b07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Notes' and @name = 'Notes' and @title = 'Notes']</value>
      <webElementGuid>ba3cc963-d3a9-4dd1-9488-18fcb6eddd80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
