<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click Preview on a case</name>
   <tag></tag>
   <elementGuidId>aa56e410-93cd-4009-9f73-275e588e9920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'button' and @id = 'preview']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;preview&quot;)[count(. | //input[@type = 'button' and @id = 'preview' and @value = 'Preview']) = count(//input[@type = 'button' and @id = 'preview' and @value = 'Preview'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff0f798c-b7aa-4369-a0c0-006375cda602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd09bda3-32a8-4b07-98f1-f14428d8a477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview</value>
      <webElementGuid>81eb4926-0c12-455a-9c03-be04b14c990f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>1855b5de-6c5a-476d-9b6d-7046cee9f1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview&quot;)</value>
      <webElementGuid>b46d647f-a70d-4a47-81d9-4e2c5ab56223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='preview']</value>
      <webElementGuid>6b11b5af-bd5f-482b-99cb-57f996acfffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span[5]/input</value>
      <webElementGuid>a171e9a8-66a5-40a1-89a3-5c7bcc0d46ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input</value>
      <webElementGuid>c8b37f5b-99cd-488f-aba3-322e9feda6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'preview']</value>
      <webElementGuid>18a69dcd-110a-4602-9539-f229e7f9a6b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
