<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click submit on a case</name>
   <tag></tag>
   <elementGuidId>c61afdd0-6401-433b-8d1a-5a7bd5cfa068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;submit&quot;)[count(. | //input[@type = 'button' and @id = 'submit']) = count(//input[@type = 'button' and @id = 'submit'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5184ca10-f269-4818-b122-843196a8ac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76474c49-1d29-401f-bd5e-e36a842a2420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e69ecf56-ed9a-4e2f-9e99-64ef4d0c765c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>08433f4c-9a23-4b63-b0d9-f65a4a3edb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>css: { hidden: !settings.EditUrl || !availableSchedulePrintLayouts().length },click: function() {submitAndPrintRecord(($('#AvailableSchedulePrintLayoutSelector option:selected').text().length > 0) ? $('#AvailableSchedulePrintLayoutSelector option:selected').text() : settings.AvailableSchedulePrintLayouts[0].Name, {'showFilePreview':true,'context':10,'submitCaseOutputInDocx':false})}</value>
      <webElementGuid>aba02dd6-2cf4-4dc2-a294-5d2122689d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit&quot;)</value>
      <webElementGuid>439f7460-66e8-4580-b8f7-caa841d8f074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit']</value>
      <webElementGuid>ef27cd42-f288-4f1f-91c2-57c9c537683e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/ul/li/span[5]/input[2]</value>
      <webElementGuid>2d278436-baf1-4f37-a2d1-155bd9660409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/input[2]</value>
      <webElementGuid>f26cc20d-f11e-416e-b37f-971077753dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'submit']</value>
      <webElementGuid>d93e0b4d-c080-4e54-abbd-e2499912b52d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
