<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Type</name>
   <tag></tag>
   <elementGuidId>cf6cc64b-7255-48f3-b550-246af91291d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Type&quot;)[count(. | //*[@id = 'Type' and @title = 'Type']) = count(//*[@id = 'Type' and @title = 'Type'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>96002671-012a-4718-a08f-8aebd30c8906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>b569a66b-509c-4869-aa57-4bc464acf777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.filteredLookup('aa4ca58b-8326-4eac-9747-87ebb1d380c1', model.Type), optionsText: 'Value', optionsValue: 'Value', value: model.Type,event: {change: function() {clue.SetSubtypeEmpty(model.SubtypeVisible,'6400fa8a-a78b-467b-8f2d-2602a113e911', model.Subtype, model.Type);}}</value>
      <webElementGuid>f0bbe35b-ad05-4926-b847-6cfb6eb2d596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02a78066-04e7-4800-85ff-645898ace8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Type must be a string with a maximum length of 255.</value>
      <webElementGuid>04762d3a-b10c-4062-9b11-da0fb678df7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>2bf88008-2690-4ded-997c-db461c9a47b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>76ecf3fe-db5f-40b7-b5ac-ad4905d22d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>e48d68bb-a5e6-4ae1-947b-c8f8e148f487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Type</value>
      <webElementGuid>d4765f8e-6219-4287-8a97-233aed9b3b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Type&quot;)</value>
      <webElementGuid>ec5e9183-7820-4052-82d4-31bf5acef085</webElementGuid>
   </webElementProperties>
</WebElementEntity>
