<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SecurityClassification</name>
   <tag></tag>
   <elementGuidId>b44af16e-2e53-408b-b529-8ae58184ab39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'SecurityClassification' and @name = 'SecurityClassification' and @title = 'Security Classification']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd320765-66cc-49fb-8a1a-255d57d12fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable input-validation-error</value>
      <webElementGuid>9885526c-3af2-4759-9cce-2e57f4bfa451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('1a8522d7-810f-4d81-93c4-9dd8a6c7a161', model.SecurityClassification()), value: model.SecurityClassification</value>
      <webElementGuid>2ef373db-728c-4051-9d8a-4bdb279a6e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>946f4f2c-26b3-4330-acf4-eb271a6da67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>The Security Classification field is required.</value>
      <webElementGuid>c89a17df-97f9-46ec-a015-c87ed297e98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>e861fa83-7d38-4ad0-a806-ac1a4ac34eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>46fb2ede-f21a-40d3-94b5-0341d0ff6be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>9fc2f364-4bc2-4a37-88f1-09a78a8ff465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Security Classification</value>
      <webElementGuid>7e0defbc-8fb1-4d03-83c8-9f97f50eac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>SecurityClassification-error SecurityClassification-error</value>
      <webElementGuid>4c33ddc1-ddab-41cd-8e0a-862e79f7e8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd6aac3f-599b-4f55-aab0-34bca5c22f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SecurityClassification&quot;)</value>
      <webElementGuid>6c9952c1-7e2c-4f1e-af67-2225666d1b9c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
