<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_Custom3</name>
   <tag></tag>
   <elementGuidId>b3589788-b2a5-4c40-92cc-e28fdc0b06ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Custom3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Custom3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c6b5b8d1-0557-4e07-b37b-fc7b3431ec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>bc91e1c4-7077-4936-9eae-2282b8175920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.CustomFields()['Custom3']</value>
      <webElementGuid>71627a7a-4cb9-432e-8cb2-afb33dbae2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Custom3</value>
      <webElementGuid>1e270cf0-8458-46bd-b01c-4691b167a858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Custom3</value>
      <webElementGuid>93602f14-104a-481a-a521-8cf7f2f32c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>85efa3a8-0658-4ccd-99c5-ce085cfe7305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Custom3&quot;)</value>
      <webElementGuid>b68e70f5-6e86-4eef-802f-a21f5dfb0750</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Custom3']</value>
      <webElementGuid>9aeb3ce3-91ab-423b-971a-e53b7a33974d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog1']/form/fieldset/ul/li[3]/div[2]/textarea</value>
      <webElementGuid>e8d4c7e9-f5c1-4638-8eab-52dfc34357f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/textarea</value>
      <webElementGuid>923511f1-cd2e-4fe1-8ed8-fef1774bfb3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Custom3' and @name = 'Custom3' and @title = 'Notes']</value>
      <webElementGuid>1cca732d-4b62-4431-8ecf-825cbe55e67f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
