<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AttachmentLink</name>
   <tag></tag>
   <elementGuidId>6963d689-8b46-43da-b512-7bcdc429b383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='resultsBody']/tr/td[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a20afc6c-ae65-495d-83cb-2454ed165650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ade9d815-a982-45a8-8ac9-fb7eecb49368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $parents[2].format(result[field.Name], field), click: function () { clue.previewFile(result.attachmentId, null, $root.componentName); return true; }, clickBubble: false</value>
      <webElementGuid>c3686f7b-5213-4335-8c02-4af590d9c064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>e06651c3-8654-46fe-b935-fe8dfd1ee773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultsBody&quot;)/tr[1]/td[@class=&quot;clickable&quot;]/a[1]</value>
      <webElementGuid>55be0844-1e5b-4bd5-a69d-2ac6dab494ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='resultsBody']/tr/td[6]/a</value>
      <webElementGuid>ae8682b4-324b-4d95-bf9d-3e4e5d99a8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'logo')]</value>
      <webElementGuid>328d8fc4-09e5-48f4-98fa-f26e96310b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='orchestrate jacques Qui aut minus voluptate culpa.'])[1]/following::a[1]</value>
      <webElementGuid>7f495e13-c486-427d-bf14-ce06d89ee1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::a[18]</value>
      <webElementGuid>aee06b03-596b-46a7-9755-1a99b0dbcec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[3]/preceding::a[1]</value>
      <webElementGuid>db78a329-16a2-45b9-98c3-3e1fb7565d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='incentivize chaya Expedita quod omnis molestias voluptatem sequi ipsa impedit repellat.'])[1]/preceding::a[18]</value>
      <webElementGuid>fdf9cc69-1091-407c-8306-cf042927fa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='logo']/parent::*</value>
      <webElementGuid>777b3b70-c525-4093-a67e-321dd16d2793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>70004ed1-b227-49ee-bc6a-f9bb4d6877cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td[6]/a</value>
      <webElementGuid>b32ec702-429d-4e78-876f-b44bc9687ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
