<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ColumnsMoveRight(Selected)</name>
   <tag></tag>
   <elementGuidId>59b20b84-5213-4c5f-8cce-c1b070317c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#advOptColumnsMoveRight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='advOptColumnsMoveRight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4eaa0b8f-98a6-401a-b444-da5b8caa36f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>advOptColumnsMoveRight</value>
      <webElementGuid>7191beba-5253-4043-9644-7a0ad3975c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Move Right Button</value>
      <webElementGuid>13e8d5c2-d07d-4549-9bca-469d70ec86df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>moveButtons1 fas fa-arrow-right fa-2x</value>
      <webElementGuid>f3bd287f-2494-4091-bc83-9f4f84c125b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>561164d1-8517-42bb-8d9f-1b3a9b42b31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: { height:'34px', width:'20px'},click: addField, disable: isSearching() || !selectedAvailableField(), css: { disabled: isSearching() || !selectedAvailableField() }</value>
      <webElementGuid>0616d18e-4e81-4ccf-884c-c54e68596b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>34px</value>
      <webElementGuid>e061fb8f-c499-4ee7-9534-10126aea49c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>1de8f309-c684-415e-937f-824390bf9b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;advOptColumnsMoveRight&quot;)</value>
      <webElementGuid>6278955b-e2b5-431b-ba14-7d88e801858c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='advOptColumnsMoveRight']</value>
      <webElementGuid>3edad57c-ed01-4cde-aa32-da9772ac399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='columnsDiv']/ul/li/div/div[3]/button</value>
      <webElementGuid>c6e8d518-2f49-4423-a90d-6eaff1128511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/button</value>
      <webElementGuid>24c5839a-9d26-4e01-afec-b095806e3c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'advOptColumnsMoveRight' and @type = 'button']</value>
      <webElementGuid>f6dded6e-f27c-4fa2-9151-22e216264162</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
