<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Performed By</name>
   <tag></tag>
   <elementGuidId>1a7e02c5-6eb6-42fe-a522-35662dc09768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PerformedByName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PerformedByName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1705ba0a-00d4-478e-89e4-db2c37583c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PerformedByName</value>
      <webElementGuid>b11fc8d4-2310-42c4-91f5-3ac43abfc0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PerformedByName</value>
      <webElementGuid>f75dcd28-00d3-46c1-b9a7-dfbab960a4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Performed By</value>
      <webElementGuid>e7f9a47a-e477-496d-bb8e-91ea00e1225b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f0a2194-fc87-4708-95a6-111684c84161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PerformedByName&quot;)</value>
      <webElementGuid>c7a74204-1aae-435c-a7fc-38bba1d60ab9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PerformedByName']</value>
      <webElementGuid>b47a2bd0-d98a-4cd0-bc7a-8fd7fba43450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[4]/div[2]/input</value>
      <webElementGuid>23e0c41a-06e4-423d-9c5a-9b850a2dbcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/input</value>
      <webElementGuid>5d9d2c62-ef47-4669-9b21-82707b9ba482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PerformedByName' and @name = 'PerformedByName' and @title = 'Performed By' and @type = 'text']</value>
      <webElementGuid>7c7e9048-120a-460b-8ef4-f6df082d840c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
