<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Outcome</name>
   <tag></tag>
   <elementGuidId>85f01e55-55f9-4764-8c67-61d5597ac767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Outcome</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Outcome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ad9d0b8-84bd-4886-8ff9-05c6c3a14fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>c763168b-1932-4bae-8bfe-1fe10ac33ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Outcome</value>
      <webElementGuid>8902729a-ca12-4632-a301-5c258e75e3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Outcome</value>
      <webElementGuid>9365f1f9-488d-4a76-a8cf-d3e030c552b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Outcome</value>
      <webElementGuid>82479368-b037-42fe-ab2c-380f3feead74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DillanOutcome IStewart
</value>
      <webElementGuid>f93940f7-aa94-4777-a59c-31c7fbcc5b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Outcome&quot;)</value>
      <webElementGuid>bdb70da0-87a4-4605-a0fe-595b4b434b86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Outcome']</value>
      <webElementGuid>9d912d1f-6c36-4638-b6d2-16eed2436a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[5]/fieldset/ul/li[6]/div[2]/select</value>
      <webElementGuid>aea41016-8dc1-4488-816b-a6065ec030a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outcome'])[2]/following::select[1]</value>
      <webElementGuid>a6908c6f-72a6-4413-9a73-99d42eca4c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviewed By'])[1]/preceding::select[1]</value>
      <webElementGuid>5591d942-b9bd-4986-b524-5bb7736ed2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[2]/select</value>
      <webElementGuid>1b658daa-a1e3-40fb-a2a6-3c541152b646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Outcome' and @name = 'Outcome' and @title = 'Outcome']</value>
      <webElementGuid>12d154bd-4f23-4106-8a09-827eed5292e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
