<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Redact - 1</name>
   <tag></tag>
   <elementGuidId>db41f5f6-6266-4ce0-9e0e-d2210a062642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redact-button-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='redact-button-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba198e02-25b0-4394-a432-c7d02858a684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b15b8812-fe1d-48de-9bbd-a8c58ea2b427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden sm:inline-flex justify-center
                                                        rounded-md border border-gray-300 bg-white
                                                        py-1 sm:py-2 px-2 sm:px-4
                                                        text-sm font-medium text-gray-900 shadow-sm
                                                        hover:bg-gray-100 focus:ring-transparent focus:outline-none focus-visible:ring-sky-500 focus-visible:ring-2 focus-visible:ring-offset-2
                                                        disabled:bg-gray-200 disabled:text-gray-400</value>
      <webElementGuid>30ac515b-9823-47eb-844b-002498868948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>80104037-3a7b-4218-8b55-8f09ecefa91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: function () { $parent.confirmRedaction($index()); }, attr: { 'id': 'redact-button-' + $index() }</value>
      <webElementGuid>4bc80b6f-8f4d-4593-9745-7adf5a256458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redact-button-0</value>
      <webElementGuid>45bde932-9904-48d2-98e0-f6125fa4d6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Redact
                                        </value>
      <webElementGuid>37aeaae2-8421-403b-a684-32ea1ab0160e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redact-button-0&quot;)</value>
      <webElementGuid>7d938121-47c8-4276-980d-b1f413f24ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='redact-button-1']</value>
      <webElementGuid>a3d1d996-b06a-4496-a94f-8bf4c35966f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='result-content-0']/div/div[2]/button</value>
      <webElementGuid>d88c7bde-0ed9-43c7-b88b-8428b328fcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Person | 894 | Gbenga Foxtrot'])[1]/following::button[1]</value>
      <webElementGuid>b004f21c-6066-4154-87ed-85399dec9042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='matches on this page of results'])[1]/following::button[1]</value>
      <webElementGuid>9aaeaf91-df10-4e43-9061-5e1dd3a590a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[1]/preceding::button[2]</value>
      <webElementGuid>a2316665-4961-47de-9f35-79c9970b1a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open'])[1]/preceding::button[2]</value>
      <webElementGuid>787a65ad-ed3f-417e-8b0d-ac702df80392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>6e7beed4-323a-49c2-944a-e952c9bbb1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'redact-button-1']</value>
      <webElementGuid>a85e7ac5-d071-4b3a-915f-97508d280528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
