<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email(Task_SearchTerms)</name>
   <tag></tag>
   <elementGuidId>09a0de72-68fc-423d-afa0-305c86049881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='email'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>089e2479-3bc7-4efc-9651-58a03ebb4eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $data</value>
      <webElementGuid>d4d4d2fb-486b-4596-81fd-db85fb717416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>praise.jenson@gmail.com</value>
      <webElementGuid>7104ca63-13eb-4a0d-bfcb-5aa43cc57881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[1]/fieldset[2]/ul[1]/li[2]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[3]/td[2]</value>
      <webElementGuid>9f53ac85-38a3-49e1-b017-c8d276aec014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset[2]/ul/li[2]/div[2]/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>05f19118-0247-4ced-b960-38cb7d1225c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='email'])[1]/following::td[1]</value>
      <webElementGuid>6d443dbb-21a6-49dc-86dc-6de1c9f1bafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenson'])[1]/following::td[2]</value>
      <webElementGuid>91740bae-885f-463b-a7a3-a362700c1f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Fields'])[2]/preceding::td[1]</value>
      <webElementGuid>6f5a7ce3-4a6e-4165-a71b-554c13ec1add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='praise.jenson@gmail.com']/parent::*</value>
      <webElementGuid>e7410272-de89-4d73-a2d4-6b6fb60def1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]</value>
      <webElementGuid>2a01ade4-e99d-412e-8331-099ace687b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
