<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Forename(Task_SearchTerms)</name>
   <tag></tag>
   <elementGuidId>68afbe87-828b-4796-a95c-a2fb95efcc2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='forename'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d51d3ac6-9a8b-4409-b9a8-4b9beff5964c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $data[1]()</value>
      <webElementGuid>1c7f7b86-988b-4ff9-b44b-93077134978d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[1]/fieldset[2]/ul[1]/li[2]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[2]</value>
      <webElementGuid>8a1b96b5-3092-4279-a5b3-a547f76b8d2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset[2]/ul/li[2]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>b47a92e0-938c-44b9-9875-9659616f0203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='forename'])[1]/following::td[1]</value>
      <webElementGuid>74b34f3e-67c3-48bf-a57b-01f80e7b59c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PII Value'])[1]/following::td[2]</value>
      <webElementGuid>a4e8665a-e747-47cf-a025-76aca01522e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='surname'])[1]/preceding::td[1]</value>
      <webElementGuid>4d5376e3-820b-458c-8a88-a02fddba37fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenson'])[1]/preceding::td[2]</value>
      <webElementGuid>b86e0f76-9764-4981-9320-2ec823d38313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Praise']/parent::*</value>
      <webElementGuid>d649626a-6c26-4e50-9e53-ae89a0d35311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>ace51cff-9457-4ce6-9e7f-33f9377926b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
