<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forename(SearchResults)</name>
   <tag></tag>
   <elementGuidId>61fbf6df-6c6d-4d6b-a62d-be6f09884b3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='forename']/parent::*</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[(text() = 'Forename' or . = 'Forename')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>702cca6b-2685-44f2-bb66-64df6ea7b5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: $data[1]</value>
      <webElementGuid>6345fa6b-181f-44d1-808e-8c7bf5ed465b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forename</value>
      <webElementGuid>23e41413-9474-4ede-9e6e-8b4d71d8f026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[1]/fieldset[2]/ul[1]/li[2]/div[@class=&quot;list maxWidth&quot;]/table[1]/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>9e04614a-6cd4-4e5c-9113-109e472e5b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form1']/div/fieldset[2]/ul/li[2]/div[2]/table/tbody/tr/td</value>
      <webElementGuid>628b6200-b8a5-4c5f-8ef6-059b9964ca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PII Value'])[1]/following::td[1]</value>
      <webElementGuid>cbdbf7f8-64a0-461e-bf54-58ded1d608ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PII Term'])[1]/following::td[1]</value>
      <webElementGuid>6b5e98c5-a340-4c58-92cb-0c791b2f0251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pamela'])[1]/preceding::td[1]</value>
      <webElementGuid>45a6d035-1fac-4b53-a993-bc1c19e2cbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='surname'])[1]/preceding::td[2]</value>
      <webElementGuid>73f226e8-748b-43b3-a854-803133f4ff39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='forename']/parent::*</value>
      <webElementGuid>89e86833-299e-483f-a559-787118a9cfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>b71722a7-221c-4077-8bfd-dbdc1876e1ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
