<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Investigation</name>
   <tag></tag>
   <elementGuidId>66098934-3194-4324-953b-4f92f1e54e47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#result-content-2 > div.flex.items-center.justify-between.gap-x-2 > div.flex.items-center.justify-start.gap-x-2.min-w-0 > #searchResult</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//h4[@id='searchResult' and contains(text(),'Investigation')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>309e2873-16bb-49e9-abdf-32aa0812f2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base font-medium leading-6 text-gray-900 truncate</value>
      <webElementGuid>7891fceb-43fb-4837-83f4-3f0b81f89113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchResult</value>
      <webElementGuid>54fab1eb-594f-4c63-8e39-7b187c82a893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: (item.Register()||'') + ' | ' + (item.Urn()||'') + ' | ' + (item.RecordTitle()||'')</value>
      <webElementGuid>9667621b-ee59-491b-af35-6f74591a7557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Investigation | 37 | Case and disclosure witness list - Arnold Clarkton</value>
      <webElementGuid>c4334f4e-1021-462d-bffb-86a4b52bf998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;result-content-2&quot;)/div[@class=&quot;flex items-center justify-between gap-x-2&quot;]/div[@class=&quot;flex items-center justify-start gap-x-2 min-w-0&quot;]/h4[@id=&quot;searchResult&quot;]</value>
      <webElementGuid>a0acc9fc-c48f-4bf5-b6b2-e093648c3597</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//h4[@id='searchResult'])[3]</value>
      <webElementGuid>b8b9ee56-dbf0-4605-99cf-d8262c242222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='result-content-2']/div/div/h4</value>
      <webElementGuid>6512f7fb-f4a2-4e75-93b9-44e94088da52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redaction successful'])[2]/following::h4[1]</value>
      <webElementGuid>0342a362-21a1-454f-945f-937abf37904b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try again'])[2]/following::h4[1]</value>
      <webElementGuid>b813c1d5-2262-4476-9e58-308e9db8527f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redact'])[8]/preceding::h4[1]</value>
      <webElementGuid>35759d01-f275-4eb0-9d9a-f83821f25957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[3]/preceding::h4[1]</value>
      <webElementGuid>62b4fc7d-108b-4233-8046-db210acd5755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Investigation | 37 | Case and disclosure witness list - Arnold Clarkton']/parent::*</value>
      <webElementGuid>1031a756-a9db-40e0-9d6b-d1bafc94e12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/h4</value>
      <webElementGuid>f4945f95-9ab4-411d-b257-64cc005a97ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@id = 'searchResult']</value>
      <webElementGuid>17fd153d-cce1-4287-b94d-54b92fe12a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
