<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Record Properties_Expand_New</name>
   <tag></tag>
   <elementGuidId>bd1dfcc2-12bc-4d21-8b9e-e676eebbd3cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recordPropertiesExpand']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-plus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c17e494a-5774-4a80-a788-ba4d5df400a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-plus</value>
      <webElementGuid>313ad8e2-fd9f-4a35-8799-57b590d7ddb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recordPropertiesExpand&quot;)/i[@class=&quot;fas fa-plus&quot;]</value>
      <webElementGuid>7c344109-cabe-4608-9224-40f95c6213eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recordPropertiesExpand']/i</value>
      <webElementGuid>dbc2cc5f-3c5f-4d24-a9a5-e54b4471469e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>30761e20-af57-4945-b7e5-8e237238aa22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
