<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Redaction Success Confirmation</name>
   <tag></tag>
   <elementGuidId>e989ffa8-f0bb-4fef-9524-8a1ecb41a6af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dialog-title-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='dialog-title-success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>df159640-17bb-42c1-aa65-159417c3b459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dialog-title-success</value>
      <webElementGuid>c6a04e24-e340-4a83-a7de-55bcc76ced08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-lg font-medium leading-6 text-gray-900</value>
      <webElementGuid>ae672234-9c3c-421b-b49d-c4dda9f9061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Redaction successful</value>
      <webElementGuid>3d7bca78-e1cf-494d-a47b-87280f28c6e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redact-state-success-0&quot;)/div[@class=&quot;flex flex-col items-center max-w-sm px-2&quot;]/h3[@id=&quot;dialog-title-success&quot;]</value>
      <webElementGuid>c1331368-012c-46e4-bcd7-1d0b7d89dad7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='dialog-title-success']</value>
      <webElementGuid>18597036-dc85-49a0-b68b-99460e7fa913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='redact-state-success-0']/div/h3</value>
      <webElementGuid>a159bd1a-efb4-4ef5-9f1e-02e4c9b3e208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try again'])[1]/following::h3[1]</value>
      <webElementGuid>92cecbdf-8baf-4e4f-8471-678bfa925fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error'])[1]/following::h3[1]</value>
      <webElementGuid>151cac66-fc92-4cf0-9f4e-65dbe4e6dcc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident | 227 | Your first impression of me: I looked like butter wouldn’t melt.'])[1]/preceding::h3[1]</value>
      <webElementGuid>d8e0f450-d089-4424-8872-a42ace3aec9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Redact'])[4]/preceding::h3[1]</value>
      <webElementGuid>46d2164f-0891-4b53-b445-28c637794dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Redaction successful']/parent::*</value>
      <webElementGuid>fc2c442a-ea3e-4547-861c-eb0cab04f659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/h3</value>
      <webElementGuid>c21bd924-89b9-443b-9e6a-959bb5d7100c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'dialog-title-success']</value>
      <webElementGuid>b074713c-f175-4fa6-88f1-099cbb1f04ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
