<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Owner_Record</name>
   <tag></tag>
   <elementGuidId>b4c6ece7-c213-4454-b774-bf0125d623d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CreatorTeam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CreatorTeam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44210d52-c4dd-4339-ad8a-70708c2f3b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>e504ac78-7f7a-4155-8f64-21efd74d4961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: model.userStructuralTeams, value: model.CreatorTeam, event: {change: function(){clue.creatorTeamChanged(model);} }</value>
      <webElementGuid>981a84e8-ff22-4fe4-8342-f959eeade7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CreatorTeam</value>
      <webElementGuid>2da0a0fe-6388-4bb2-8545-ce603de55945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreatorTeam</value>
      <webElementGuid>cd5bfa1a-ddb9-4990-b801-464f8612586c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Owner Team</value>
      <webElementGuid>51756149-2c4b-4c3d-af5c-e0fd45341f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Intelligence Source ManagementRedact
</value>
      <webElementGuid>2de4cd17-898f-4b48-9d75-17d9b39fd74e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreatorTeam&quot;)</value>
      <webElementGuid>1996f463-8151-40c8-a450-5e7fe67ad4b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CreatorTeam']</value>
      <webElementGuid>b6bf7e3c-ce18-4655-addd-3ed79f22f565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[6]/fieldset[3]/div[2]/ul/li[3]/div/div[2]/select</value>
      <webElementGuid>32c430c3-ec40-427d-9da0-910d18f4b108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner Team'])[1]/following::select[1]</value>
      <webElementGuid>ec8da761-84a4-47e6-82a0-0b4bacdeb28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creator'])[1]/preceding::select[1]</value>
      <webElementGuid>292098bd-d179-44b3-9f10-387176b71b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/select</value>
      <webElementGuid>4ace5107-de6b-4e4e-906f-1daadd036051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CreatorTeam' and @name = 'CreatorTeam' and @title = 'Owner Team']</value>
      <webElementGuid>16ee574b-9d25-4575-885d-d91f20e409c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
