<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>surname(Redact Pop-Up)</name>
   <tag></tag>
   <elementGuidId>9c87a36b-866e-41d9-b07e-e28c140d5552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>802110fe-b7aa-40e6-8669-7d278b4db10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>whitespace-nowrap py-2 px-3 text-sm text-gray-600</value>
      <webElementGuid>014fa6bb-dfbf-412d-aa3c-c6198cf59d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text:$data[1]</value>
      <webElementGuid>26da775d-c3bd-4ae8-b3eb-4abd7e6d0908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Houston</value>
      <webElementGuid>ad256138-48ae-4fc7-b6e8-15e5c243f2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-3&quot;)/div[@class=&quot;tailwind&quot;]/div[@class=&quot;bg-white min-h-full&quot;]/div[@class=&quot;flex h-[calc(100vh-7.34rem)] flex-col overflow-hidden&quot;]/header[@class=&quot;border-b z-20 bg-gray-50&quot;]/div[@class=&quot;relative mx-auto max-w-screen-xl py-3 px-4&quot;]/details[@class=&quot;w-full group&quot;]/div[@class=&quot;border-t sm:border sm:rounded-md sm:shadow-sm mt-2 -mb-3 sm:mb-0 -mx-4 sm:mx-0&quot;]/table[@class=&quot;table-fixed min-w-full divide-y divide-gray-200 sm:border sm:rounded-sm overflow-hidden&quot;]/tbody[@class=&quot;divide-y divide-gray-200 bg-white&quot;]/tr[2]/td[@class=&quot;whitespace-nowrap py-2 px-3 text-sm text-gray-600&quot;]</value>
      <webElementGuid>e998e99c-4692-4a36-9646-0c3130cc1a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-id-3']/div/div/div/header/div/details/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>ca0f8b1d-758b-4f56-bbd7-b7d4b2f6b826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Surname'])[1]/following::td[1]</value>
      <webElementGuid>d4bfe3e6-b89d-4937-8b27-57703a637114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cassidy'])[2]/following::td[2]</value>
      <webElementGuid>0b8ec9a8-0927-4bb3-8778-be1b7335f0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='matches on this page of results'])[1]/preceding::td[1]</value>
      <webElementGuid>e3e2f21c-f3b2-4a2f-89e2-df98f5d2cd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Incident | 709 | Suspected betting scam on a tennis match'])[1]/preceding::td[1]</value>
      <webElementGuid>e53741d3-7eef-4caf-a767-03138071b014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>30e06fcc-4b6e-437c-8a3b-0980b107b2f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
