<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Occupation</name>
   <tag></tag>
   <elementGuidId>d26c7bf6-28c1-41d2-863c-a46039478103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Occupation&quot;)[count(. | //*[@id = 'Occupation' and @name = 'Occupation' and @title = 'Occupation' and @type = 'text']) = count(//*[@id = 'Occupation' and @name = 'Occupation' and @title = 'Occupation' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da54da74-2074-4f11-b2cf-b82736576943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>0938ca01-b3a2-477e-8a52-2525788b6c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Occupation</value>
      <webElementGuid>ca7bc4cc-68ba-479f-afe9-87469f2a0897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c3b9e77-de66-42af-9eb7-c2d4c569be71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Occupation must be a string with a maximum length of 255.</value>
      <webElementGuid>ec8731c5-9fda-4b08-b8b2-06bca6d20139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e4c49be0-7110-45dd-9256-e769ec5334c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>55f4522f-2292-46c7-bed1-6d190333b16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>9124f55d-dbf7-474c-b13a-582dfa25a721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Occupation</value>
      <webElementGuid>1acc574e-4520-4d70-94d7-f8cebb86d96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71b0576d-0f92-42f3-9b63-51a044c9e605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Occupation&quot;)</value>
      <webElementGuid>80cdd877-9060-4158-84be-bd39df64f139</webElementGuid>
   </webElementProperties>
</WebElementEntity>
