<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Source</name>
   <tag></tag>
   <elementGuidId>671d3356-604f-46b5-ab9e-820f5c801265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Source&quot;)[count(. | //*[@id = 'Source' and @name = 'Source' and @title = 'Source' and @type = 'text']) = count(//*[@id = 'Source' and @name = 'Source' and @title = 'Source' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fd1630b-b4b6-4e98-9755-250ac8bfd361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>8740fb45-b293-4f59-a643-632fed9e11ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: model.Source</value>
      <webElementGuid>a6937708-7884-4cd7-94c4-482e06e90caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb2ef8b1-e6bc-4783-a92f-ccc631555dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Source must be a string with a maximum length of 255.</value>
      <webElementGuid>027cf080-25ce-4289-8afc-5792cd337ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e6680f28-5aa2-4788-ac2e-0028519aa0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Source</value>
      <webElementGuid>40f88a13-a3cc-4f89-b67f-421f2d6485e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Source</value>
      <webElementGuid>4dc8d1c8-d2f8-4909-a2ef-1d18d33a67e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Source</value>
      <webElementGuid>af42f8f8-55cd-4b81-91ce-3fa2d3839c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fcaae77-1673-4154-937b-a678f6d46ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Source&quot;)</value>
      <webElementGuid>9ac913cd-bc46-4362-bb3a-b57d58358b18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
