<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SecurityClassification</name>
   <tag></tag>
   <elementGuidId>4242bd7c-b2f3-4451-b678-5a473173b060</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eca5695f-1285-442f-86b5-0360862a8312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>aba2ed9d-b43b-498d-87ad-2a0f045d19ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('1a8522d7-810f-4d81-93c4-9dd8a6c7a161', model.SecurityClassification()), value: model.SecurityClassification</value>
      <webElementGuid>34effad6-3b25-4182-bbae-391a05b9001c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1b7226c-87bc-4db2-9fbc-4ed20f3a2c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif</name>
      <type>Main</type>
      <value>The Security Classification field is required.</value>
      <webElementGuid>0564e70e-2b3c-4b98-b915-48e7a0168b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-requiredif-dependentproperty</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>5fb4b6a1-b4e4-406c-841d-d36a942964c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>ec822c75-d878-4661-802d-162367a33d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SecurityClassification</value>
      <webElementGuid>9c525b99-f655-43f9-a13e-556bb384a22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Security Classification</value>
      <webElementGuid>df01bebe-3cbb-42b4-a87b-5f5dba04bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SecurityClassification&quot;)</value>
      <webElementGuid>a49e9198-b203-4171-b883-1a4a1cac1f5c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
