<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Deceased</name>
   <tag></tag>
   <elementGuidId>ecc05e26-f035-4eaf-8759-d8f166cbc121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'IsDeceased' and @name = 'IsDeceased' and @title = 'Deceased?' and (text() = 'NoYes
' or . = 'NoYes
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>44333826-2a4b-4c46-bc10-c687cacfe144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>fde557b1-ae0d-4bb9-86a5-af2cd4227653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.keyedLookup('nullyesno', model.IsDeceased), optionsText: 'Value', optionsValue: 'Key', value: model.IsDeceased</value>
      <webElementGuid>31057a14-48f7-400a-a366-c550382e978d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsDeceased</value>
      <webElementGuid>c0372291-3623-4f93-9ac2-ae9c8db3350e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsDeceased</value>
      <webElementGuid>052f27e1-75ae-4c45-913e-f854532c4f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Deceased?</value>
      <webElementGuid>7614069f-a12a-4b6f-ad26-2712131b3752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsDeceased&quot;)</value>
      <webElementGuid>1c4ba85d-b60b-489c-a4b7-755664501604</webElementGuid>
   </webElementProperties>
</WebElementEntity>
