<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Religion</name>
   <tag></tag>
   <elementGuidId>090d818f-5938-48ca-94e5-f7446176f025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Religion&quot;)[count(. | //*[@id = 'Religion' and @title = 'Religion']) = count(//*[@id = 'Religion' and @title = 'Religion'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45ecb7c5-629b-41f5-afbc-f4c6c5a8989b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combo-box editable</value>
      <webElementGuid>c4795d04-9fec-4ca4-8760-2659a6585e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>options: clue.lookup('bcf0d948-0794-4b48-8f7a-f6cdef75d689', model.Religion()), value: model.Religion</value>
      <webElementGuid>57e4a8f6-373f-4a82-92e2-150b983ea085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7f68344-4722-4f25-a244-4efe24450ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Religion must be a string with a maximum length of 255.</value>
      <webElementGuid>9e3d4f97-e598-4ea0-be75-990216487b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>92db960f-862a-4a01-a771-8cdbd26fa23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Religion</value>
      <webElementGuid>d08729f1-3626-4f40-946f-f3b97c25098f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Religion</value>
      <webElementGuid>cbda3ad6-2515-40a4-ab5f-e218520ca220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Religion</value>
      <webElementGuid>02636e83-8436-4aef-a3d7-ebca2d3f7f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Religion&quot;)</value>
      <webElementGuid>06308297-efb0-4aa2-93de-a96e086b01dc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
