<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Person</name>
   <tag></tag>
   <elementGuidId>424ead9a-8077-48d6-a228-edc398c66481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addRecord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='addRecord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>168a340c-6eb7-4401-9e8f-195c3819e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Person/Create/0</value>
      <webElementGuid>cb10112d-f39e-46e9-80fd-cce58c51ae7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addRecord</value>
      <webElementGuid>1cbc5859-0b16-43e4-bedd-2632459e39d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>visible: !containerId() || component.Name == 'Case'</value>
      <webElementGuid>fde7cbeb-a691-4748-a140-2f03ab67f18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Person</value>
      <webElementGuid>15d2fb56-5fb0-4134-9172-ffe817c3653e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addRecord&quot;)</value>
      <webElementGuid>ae59d4f2-5dcd-4cae-86a1-f0acb78b466e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='addRecord']</value>
      <webElementGuid>2178909e-f815-4820-9ee0-75387ff17d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/p/a[2]</value>
      <webElementGuid>bbc64b4d-01ef-4f45-9978-646b83f5303c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add Person')])[2]</value>
      <webElementGuid>ecb5cddc-b2b8-4f76-b022-b6abacc854c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Person Register'])[1]/following::a[2]</value>
      <webElementGuid>5f75d5c8-cbdf-4da3-9b7c-18a94475c205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>ba83e9bf-5221-490a-90be-d4ffa7d60230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Options'])[1]/preceding::a[1]</value>
      <webElementGuid>b4ebcde1-9554-4db6-bc21-c054d324ad96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Options'])[2]/preceding::a[1]</value>
      <webElementGuid>99f76924-f4f4-42a1-ab2a-a495a80185b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Person/Create/0')]</value>
      <webElementGuid>5948ab88-2b97-4e33-88c0-11121ce3ebce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a[2]</value>
      <webElementGuid>bc1d4848-b3ca-4534-82ba-3f9243b82226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'addRecord']</value>
      <webElementGuid>2ffdd467-5276-4ff4-a1ac-5fd30532e769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
