<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_PhoneNumber</name>
   <tag></tag>
   <elementGuidId>8a2de7a3-9237-45c1-8823-7291eccba695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0a25b4b-4ce6-40e5-abf8-6b2f8f47e9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box single-line</value>
      <webElementGuid>2bfa5869-ba94-4c59-a7c5-6a954a6a896f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: phoneNumber</value>
      <webElementGuid>9b23644c-e8d2-4cb1-ae0e-42c003fb2041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>94f5bf04-f838-4683-8b9d-1c20d571d27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Phone Number must be a string with a maximum length of 25.</value>
      <webElementGuid>19d4504f-be1e-43e5-b92a-0bc8eb640db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3d681b61-82bd-4c34-9e00-a2c61101a250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>da45521e-91e9-446f-a3ec-b61fa1dbb483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>ee3fc03f-b200-406f-89f9-2db6175facb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>f8c87a51-6e54-44f7-b99c-412d77a1df7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>231078aa-5219-4601-bac6-5f36fad2afea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneNumber&quot;)</value>
      <webElementGuid>0209c6d1-30be-403e-9489-b860ae588ebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhoneNumber']</value>
      <webElementGuid>771e0d55-8a5e-4def-b706-f4deb5a6f5e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dialog1form']/fieldset/ul/li[4]/div[2]/input</value>
      <webElementGuid>4c495d82-3e70-42e4-aec5-44fcd4a47d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/input</value>
      <webElementGuid>5ae1dd54-ae58-481b-a712-bb7827a90047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneNumber' and @name = 'PhoneNumber' and @title = 'Phone Number' and @type = 'text']</value>
      <webElementGuid>19fd8076-cf82-435f-b09a-f72e6226da48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
