<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_Description</name>
   <tag></tag>
   <elementGuidId>0a20c185-16e5-4b8a-8c25-962e17028587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>61fa2d6e-160c-4a99-8fee-e7f6f1964ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-box multi-line</value>
      <webElementGuid>3c8779cd-0914-4a15-b5c6-ff9e5555233d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: description</value>
      <webElementGuid>4fdaa8a6-af8b-41e2-8f5c-ae4e9c64b272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93294e00-f1c1-4a54-9f68-448b646a6817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Description must be a string with a maximum length of 1000.</value>
      <webElementGuid>481958d0-8c02-4a04-bdc0-d215aa7c4d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>29fe5854-6f03-4d39-a7a7-8d6fe1e9bc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>68045da4-9c1e-4c94-9b04-b02da78bbc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>015805cb-4e19-4c8f-a49d-6bfa524f3d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>54573d2d-4954-4082-b4f4-0dd59223cd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Description&quot;)</value>
      <webElementGuid>fbd8d0ff-39d3-4982-ba63-1ec163eb52d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Description']</value>
      <webElementGuid>d22dbd1b-260b-4ce2-8740-b07fcdbcfd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dialog1form']/fieldset/ul/li[6]/div[2]/textarea</value>
      <webElementGuid>b549a43e-1059-49e3-a230-7dec0625b292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>561530e9-5792-4c38-a06f-ae2b284ef2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Description' and @name = 'Description' and @title = 'Description']</value>
      <webElementGuid>76807963-af14-41d7-b98e-9de161a28c49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
