<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Person</name>
   <tag></tag>
   <elementGuidId>43623238-a873-4a39-9782-bde126dda3a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/fieldset[3]/div[14]/div/table/caption/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4cd438e4-e6f3-4091-aad2-3775489072f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>38f06dbe-7a6d-4d6d-90a8-a867a9ef9e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>visible: !$root.model._disableAll &amp;&amp; !$root.model._disableLinks &amp;&amp; ($data.name != 'Investigation' || $parent.inContainer($root)) &amp;&amp; ($data.name != 'Case' || (!$root.model.ContainerId() || $parent.inContainer($root))) || ($data.name == 'Case' &amp;&amp; ($root &amp;&amp; $root.model &amp;&amp; $root.model.$type() == 'CaseCreateEditViewModel')) || $data.showOverride, text: 'Add ' + name, click: function () { $parent.createLinkEx($data, $root); }</value>
      <webElementGuid>76f7249e-86ab-4a7a-a7ef-4afe407a973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Person</value>
      <webElementGuid>942654a3-4e73-4758-8d42-001b4b49f259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/fieldset[3]/div[14]/div/table/caption/a</value>
      <webElementGuid>172e2945-15fd-48fd-ab5a-02233abf382a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add Person')])[2]</value>
      <webElementGuid>08b851e5-4539-4a5c-b93b-05d2e8ef3b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/following::a[1]</value>
      <webElementGuid>4e1315e7-66f9-4ba5-87f3-72e317115543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisations'])[1]/following::a[2]</value>
      <webElementGuid>0a13b956-b7d3-43cd-a138-2104fd422516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sources'])[1]/preceding::a[1]</value>
      <webElementGuid>31df5daa-498e-40c4-a1b8-145b9d44ca50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Staff'])[2]/preceding::a[2]</value>
      <webElementGuid>36b63810-e038-467e-9a27-27eeca7157f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[43]</value>
      <webElementGuid>9385ae1b-b484-486c-86a3-0f2c73453705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/table/caption/a</value>
      <webElementGuid>c5cffd85-2b03-49fd-91e6-3b2bf9542f88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
